import { resolve } from "node:path";
import { writeFileSync } from "node:fs";

import { ENTITY_TYPES } from "@serenityjs/data";

const enums = resolve(__dirname, "../src/enums");

let EntityTypesFile = `// WARNING, DO NOT EDIT!\n// This file is automatically generated on start up.\n\n`;

EntityTypesFile += `export enum EntityIdentifier {\n`;

for (const type of ENTITY_TYPES) {
	// TitleCase the identifier.
	const name = type.identifier
		.split(":")[1]
		?.split("_")
		.map((word) => word[0]?.toUpperCase() + word.slice(1))
		.join("");

	EntityTypesFile += `	${name} = "${type.identifier}",\n`;
}

EntityTypesFile += `}\n`;

writeFileSync(resolve(enums, "identifier.ts"), EntityTypesFile);
