enum WorldEvent {
	WorldInitialize,
	WorldTick,
	EntitySpawned,
	EntityDespawned,
	EntityEffectAdd,
	EntityEffectRemove,
	EntityDie,
	EntityTeleport,
	PlayerJoin,
	PlayerLeave,
	PlayerInitialize,
	PlayerChat,
	PlayerExecuteCommand,
	PlayerPlaceBlock,
	PlayerBreakBlock,
	PlayerInteractWithEntity,
	PlayerInteractWithBlock,
	PlayerButtonPush,
	PlayerItemConsume,
	PlayerMissSwing,
	PlayerOpenDoor,
	PlayerJump,
	BlockUpdate,
	FurnaceSmelt,
	ProjectileHitBlock,
	ProjectileHitEntity,
	ChunkRead,
	ChunkWrite
}

export { WorldEvent };
