enum WorldEvent {
	WorldInitialize,
	WorldTick,
	WorldMessage,
	EntitySpawned,
	EntityDespawned,
	EntityEffectAdd,
	EntityEffectRemove,
	EntityDie,
	EntityTeleport,
	PlayerJoin,
	PlayerLeave,
	PlayerInitialize,
	PlayerDataWrite,
	PlayerChat,
	PlayerExecuteCommand,
	PlayerPlaceBlock,
	PlayerStartBreakBlock,
	PlayerBreakBlock,
	PlayerInteractWithEntity,
	PlayerInteractWithBlock,
	PlayerButtonPush,
	PlayerItemConsume,
	PlayerMissSwing,
	PlayerOpenDoor,
	PlayerJump,
	PlayerStartSwimming,
	PlayerStopSwimming,
	BlockUpdate,
	FurnaceSmelt,
	ChunkRead,
	ChunkWrite
}

export { WorldEvent };
