// WARNING, DO NOT EDIT!
// This file is automatically generated on start up.

import { BlockIdentifier } from "../../enums/block-identifier";

export type GenericBlockState = Record<string, string | number | boolean>;

export interface BlockState {
  [BlockIdentifier.PinkTulip]: import("./blocks").PinkTulipBlock;
  [BlockIdentifier.BuddingAmethyst]: GenericBlockState;
  [BlockIdentifier.LightBlueConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Gravel]: GenericBlockState;
  [BlockIdentifier.DetectorRail]: import("./blocks").DetectorRailBlock;
  [BlockIdentifier.CyanTerracotta]: GenericBlockState;
  [BlockIdentifier.HardPinkStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.LightGrayCandle]: import("./blocks").LightGrayCandleBlock;
  [BlockIdentifier.NetherGoldOre]: GenericBlockState;
  [BlockIdentifier.PolishedBasalt]: import("./blocks").PolishedBasaltBlock;
  [BlockIdentifier.BlueCandle]: import("./blocks").BlueCandleBlock;
  [BlockIdentifier.DarkOakWood]: import("./blocks").DarkOakWoodBlock;
  [BlockIdentifier.TuffBrickWall]: import("./blocks").TuffBrickWallBlock;
  [BlockIdentifier.AcaciaWallSign]: import("./blocks").AcaciaWallSignBlock;
  [BlockIdentifier.BambooPressurePlate]: import("./blocks").BambooPressurePlateBlock;
  [BlockIdentifier.MelonBlock]: GenericBlockState;
  [BlockIdentifier.RedWool]: GenericBlockState;
  [BlockIdentifier.GoldOre]: GenericBlockState;
  [BlockIdentifier.BirchStandingSign]: import("./blocks").BirchStandingSignBlock;
  [BlockIdentifier.Element93]: GenericBlockState;
  [BlockIdentifier.WaxedCutCopperStairs]: import("./blocks").WaxedCutCopperStairsBlock;
  [BlockIdentifier.Cornflower]: import("./blocks").CornflowerBlock;
  [BlockIdentifier.RedNetherBrick]: GenericBlockState;
  [BlockIdentifier.OxidizedCutCopperStairs]: import("./blocks").OxidizedCutCopperStairsBlock;
  [BlockIdentifier.WarpedDoor]: import("./blocks").WarpedDoorBlock;
  [BlockIdentifier.PolishedGraniteStairs]: import("./blocks").PolishedGraniteStairsBlock;
  [BlockIdentifier.RedMushroomBlock]: import("./blocks").RedMushroomBlockBlock;
  [BlockIdentifier.Element30]: GenericBlockState;
  [BlockIdentifier.DeadBubbleCoralWallFan]: import("./blocks").DeadBubbleCoralWallFanBlock;
  [BlockIdentifier.BlueCarpet]: GenericBlockState;
  [BlockIdentifier.BambooBlock]: import("./blocks").BambooBlockBlock;
  [BlockIdentifier.DeepslateBricks]: GenericBlockState;
  [BlockIdentifier.WaxedCopper]: GenericBlockState;
  [BlockIdentifier.WhiteWool]: GenericBlockState;
  [BlockIdentifier.WoodenDoor]: import("./blocks").WoodenDoorBlock;
  [BlockIdentifier.PistonArmCollision]: import("./blocks").PistonArmCollisionBlock;
  [BlockIdentifier.RedSandstoneSlab]: import("./blocks").RedSandstoneSlabBlock;
  [BlockIdentifier.DarkPrismarineStairs]: import("./blocks").DarkPrismarineStairsBlock;
  [BlockIdentifier.EndBricks]: GenericBlockState;
  [BlockIdentifier.SculkShrieker]: import("./blocks").SculkShriekerBlock;
  [BlockIdentifier.BambooMosaicStairs]: import("./blocks").BambooMosaicStairsBlock;
  [BlockIdentifier.Vine]: import("./blocks").VineBlock;
  [BlockIdentifier.WaxedOxidizedChiseledCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WhiteTulip]: import("./blocks").WhiteTulipBlock;
  [BlockIdentifier.Granite]: GenericBlockState;
  [BlockIdentifier.PolishedTuffSlab]: import("./blocks").PolishedTuffSlabBlock;
  [BlockIdentifier.BrownMushroom]: GenericBlockState;
  [BlockIdentifier.CutCopperStairs]: import("./blocks").CutCopperStairsBlock;
  [BlockIdentifier.BlueStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Element0]: GenericBlockState;
  [BlockIdentifier.ExposedCopperDoor]: import("./blocks").ExposedCopperDoorBlock;
  [BlockIdentifier.BlackstoneDoubleSlab]: import("./blocks").BlackstoneDoubleSlabBlock;
  [BlockIdentifier.SpruceStandingSign]: import("./blocks").SpruceStandingSignBlock;
  [BlockIdentifier.Element118]: GenericBlockState;
  [BlockIdentifier.FenceGate]: import("./blocks").FenceGateBlock;
  [BlockIdentifier.DeepslateTileSlab]: import("./blocks").DeepslateTileSlabBlock;
  [BlockIdentifier.PowderSnow]: GenericBlockState;
  [BlockIdentifier.MagentaCandle]: import("./blocks").MagentaCandleBlock;
  [BlockIdentifier.DeepslateTileDoubleSlab]: import("./blocks").DeepslateTileDoubleSlabBlock;
  [BlockIdentifier.Calcite]: GenericBlockState;
  [BlockIdentifier.GrayTerracotta]: GenericBlockState;
  [BlockIdentifier.CyanCarpet]: GenericBlockState;
  [BlockIdentifier.CyanStainedGlass]: GenericBlockState;
  [BlockIdentifier.DarkOakButton]: import("./blocks").DarkOakButtonBlock;
  [BlockIdentifier.DeepslateCopperOre]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.StoneBrickStairs]: import("./blocks").StoneBrickStairsBlock;
  [BlockIdentifier.WaxedOxidizedCutCopperSlab]: import("./blocks").WaxedOxidizedCutCopperSlabBlock;
  [BlockIdentifier.WarpedWallSign]: import("./blocks").WarpedWallSignBlock;
  [BlockIdentifier.Ladder]: import("./blocks").LadderBlock;
  [BlockIdentifier.ChiseledStoneBricks]: import("./blocks").ChiseledStoneBricksBlock;
  [BlockIdentifier.SprucePressurePlate]: import("./blocks").SprucePressurePlateBlock;
  [BlockIdentifier.DiamondOre]: GenericBlockState;
  [BlockIdentifier.WaxedOxidizedCutCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DeadHornCoralWallFan]: import("./blocks").DeadHornCoralWallFanBlock;
  [BlockIdentifier.GrayConcrete]: GenericBlockState;
  [BlockIdentifier.Element73]: GenericBlockState;
  [BlockIdentifier.CobblestoneSlab]: import("./blocks").CobblestoneSlabBlock;
  [BlockIdentifier.GreenTerracotta]: GenericBlockState;
  [BlockIdentifier.HardPurpleStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WaxedCopperTrapdoor]: import("./blocks").WaxedCopperTrapdoorBlock;
  [BlockIdentifier.NetherBrickStairs]: import("./blocks").NetherBrickStairsBlock;
  [BlockIdentifier.HardBlueStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.YellowShulkerBox]: GenericBlockState;
  [BlockIdentifier.ChiseledCopper]: GenericBlockState;
  [BlockIdentifier.GraniteStairs]: import("./blocks").GraniteStairsBlock;
  [BlockIdentifier.GrayWool]: GenericBlockState;
  [BlockIdentifier.GreenConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.LimeStainedGlass]: GenericBlockState;
  [BlockIdentifier.OxidizedCopperBulb]: import("./blocks").OxidizedCopperBulbBlock;
  [BlockIdentifier.CobbledDeepslateStairs]: import("./blocks").CobbledDeepslateStairsBlock;
  [BlockIdentifier.WaxedExposedCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.StrippedAcaciaWood]: import("./blocks").StrippedAcaciaWoodBlock;
  [BlockIdentifier.Element16]: GenericBlockState;
  [BlockIdentifier.JungleButton]: import("./blocks").JungleButtonBlock;
  [BlockIdentifier.DeadBubbleCoralFan]: import("./blocks").DeadBubbleCoralFanBlock;
  [BlockIdentifier.PoweredRepeater]: import("./blocks").PoweredRepeaterBlock;
  [BlockIdentifier.SpruceStairs]: import("./blocks").SpruceStairsBlock;
  [BlockIdentifier.Loom]: import("./blocks").LoomBlock;
  [BlockIdentifier.HardGreenStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Element104]: GenericBlockState;
  [BlockIdentifier.YellowStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.OxidizedDoubleCutCopperSlab]: import("./blocks").OxidizedDoubleCutCopperSlabBlock;
  [BlockIdentifier.JungleDoor]: import("./blocks").JungleDoorBlock;
  [BlockIdentifier.Diorite]: GenericBlockState;
  [BlockIdentifier.DarkoakWallSign]: import("./blocks").DarkoakWallSignBlock;
  [BlockIdentifier.InfoUpdate2]: GenericBlockState;
  [BlockIdentifier.DripstoneBlock]: GenericBlockState;
  [BlockIdentifier.GrayCandleCake]: import("./blocks").GrayCandleCakeBlock;
  [BlockIdentifier.ExposedCopperTrapdoor]: import("./blocks").ExposedCopperTrapdoorBlock;
  [BlockIdentifier.BlueTerracotta]: GenericBlockState;
  [BlockIdentifier.HangingRoots]: GenericBlockState;
  [BlockIdentifier.SmoothSandstone]: import("./blocks").SmoothSandstoneBlock;
  [BlockIdentifier.PolishedBlackstoneButton]: import("./blocks").PolishedBlackstoneButtonBlock;
  [BlockIdentifier.StrippedBirchWood]: import("./blocks").StrippedBirchWoodBlock;
  [BlockIdentifier.RedCandleCake]: import("./blocks").RedCandleCakeBlock;
  [BlockIdentifier.MossyStoneBricks]: import("./blocks").MossyStoneBricksBlock;
  [BlockIdentifier.HardLightBlueStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CherryPressurePlate]: import("./blocks").CherryPressurePlateBlock;
  [BlockIdentifier.HardBrownStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CherryHangingSign]: import("./blocks").CherryHangingSignBlock;
  [BlockIdentifier.YellowWool]: GenericBlockState;
  [BlockIdentifier.BlackCandleCake]: import("./blocks").BlackCandleCakeBlock;
  [BlockIdentifier.CrimsonWallSign]: import("./blocks").CrimsonWallSignBlock;
  [BlockIdentifier.PolishedBlackstoneBrickStairs]: import("./blocks").PolishedBlackstoneBrickStairsBlock;
  [BlockIdentifier.LightBlock1]: import("./blocks").LightBlock1Block;
  [BlockIdentifier.Element46]: GenericBlockState;
  [BlockIdentifier.SmoothSandstoneSlab]: import("./blocks").SmoothSandstoneSlabBlock;
  [BlockIdentifier.GrayCarpet]: GenericBlockState;
  [BlockIdentifier.DarkOakDoor]: import("./blocks").DarkOakDoorBlock;
  [BlockIdentifier.Wheat]: import("./blocks").WheatBlock;
  [BlockIdentifier.Grindstone]: import("./blocks").GrindstoneBlock;
  [BlockIdentifier.OakFence]: GenericBlockState;
  [BlockIdentifier.YellowStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DarkOakSlab]: import("./blocks").DarkOakSlabBlock;
  [BlockIdentifier.PolishedGraniteDoubleSlab]: import("./blocks").PolishedGraniteDoubleSlabBlock;
  [BlockIdentifier.HoneycombBlock]: GenericBlockState;
  [BlockIdentifier.EndGateway]: GenericBlockState;
  [BlockIdentifier.AzureBluet]: import("./blocks").AzureBluetBlock;
  [BlockIdentifier.StoneStairs]: import("./blocks").StoneStairsBlock;
  [BlockIdentifier.Beacon]: GenericBlockState;
  [BlockIdentifier.PolishedBlackstoneBrickWall]: import("./blocks").PolishedBlackstoneBrickWallBlock;
  [BlockIdentifier.SnowLayer]: import("./blocks").SnowLayerBlock;
  [BlockIdentifier.HardPinkStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BrickDoubleSlab]: import("./blocks").BrickDoubleSlabBlock;
  [BlockIdentifier.WhiteCarpet]: GenericBlockState;
  [BlockIdentifier.BlackCandle]: import("./blocks").BlackCandleBlock;
  [BlockIdentifier.Cactus]: import("./blocks").CactusBlock;
  [BlockIdentifier.GlowFrame]: import("./blocks").GlowFrameBlock;
  [BlockIdentifier.MudBrickDoubleSlab]: import("./blocks").MudBrickDoubleSlabBlock;
  [BlockIdentifier.BambooMosaicSlab]: import("./blocks").BambooMosaicSlabBlock;
  [BlockIdentifier.BambooFence]: GenericBlockState;
  [BlockIdentifier.DarkPrismarineSlab]: import("./blocks").DarkPrismarineSlabBlock;
  [BlockIdentifier.PrismarineBricksStairs]: import("./blocks").PrismarineBricksStairsBlock;
  [BlockIdentifier.Mycelium]: GenericBlockState;
  [BlockIdentifier.DioriteSlab]: import("./blocks").DioriteSlabBlock;
  [BlockIdentifier.RedConcrete]: GenericBlockState;
  [BlockIdentifier.CrimsonHyphae]: import("./blocks").CrimsonHyphaeBlock;
  [BlockIdentifier.BlackTerracotta]: GenericBlockState;
  [BlockIdentifier.StrippedDarkOakLog]: import("./blocks").StrippedDarkOakLogBlock;
  [BlockIdentifier.HardOrangeStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.OxidizedCopperGrate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.JungleLog]: import("./blocks").JungleLogBlock;
  [BlockIdentifier.BubbleCoralFan]: import("./blocks").BubbleCoralFanBlock;
  [BlockIdentifier.BambooSlab]: import("./blocks").BambooSlabBlock;
  [BlockIdentifier.LitRedstoneOre]: GenericBlockState;
  [BlockIdentifier.NetherWart]: import("./blocks").NetherWartBlock;
  [BlockIdentifier.OrangeStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.StrippedMangroveWood]: import("./blocks").StrippedMangroveWoodBlock;
  [BlockIdentifier.CutRedSandstone]: import("./blocks").CutRedSandstoneBlock;
  [BlockIdentifier.LimeShulkerBox]: GenericBlockState;
  [BlockIdentifier.HardBlackStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.SmoothRedSandstone]: import("./blocks").SmoothRedSandstoneBlock;
  [BlockIdentifier.LilyOfTheValley]: import("./blocks").LilyOfTheValleyBlock;
  [BlockIdentifier.BlueOrchid]: import("./blocks").BlueOrchidBlock;
  [BlockIdentifier.LimeGlazedTerracotta]: import("./blocks").LimeGlazedTerracottaBlock;
  [BlockIdentifier.Trapdoor]: import("./blocks").TrapdoorBlock;
  [BlockIdentifier.HardGlassPane]: GenericBlockState;
  [BlockIdentifier.DeadBrainCoralFan]: import("./blocks").DeadBrainCoralFanBlock;
  [BlockIdentifier.AcaciaStandingSign]: import("./blocks").AcaciaStandingSignBlock;
  [BlockIdentifier.UndyedShulkerBox]: GenericBlockState;
  [BlockIdentifier.QuartzOre]: GenericBlockState;
  [BlockIdentifier.InfoUpdate]: GenericBlockState;
  [BlockIdentifier.Seagrass]: import("./blocks").SeagrassBlock;
  [BlockIdentifier.TubeCoralFan]: import("./blocks").TubeCoralFanBlock;
  [BlockIdentifier.Unknown]: GenericBlockState;
  [BlockIdentifier.CherryStairs]: import("./blocks").CherryStairsBlock;
  [BlockIdentifier.Barrel]: import("./blocks").BarrelBlock;
  [BlockIdentifier.BigDripleaf]: import("./blocks").BigDripleafBlock;
  [BlockIdentifier.QuartzSlab]: import("./blocks").QuartzSlabBlock;
  [BlockIdentifier.FireCoralBlock]: import("./blocks").FireCoralBlockBlock;
  [BlockIdentifier.WaxedExposedCutCopperSlab]: import("./blocks").WaxedExposedCutCopperSlabBlock;
  [BlockIdentifier.DeadHornCoral]: import("./blocks").DeadHornCoralBlock;
  [BlockIdentifier.InfestedMossyStoneBricks]: import("./blocks").InfestedMossyStoneBricksBlock;
  [BlockIdentifier.Element68]: GenericBlockState;
  [BlockIdentifier.RedstoneLamp]: GenericBlockState;
  [BlockIdentifier.MossyCobblestone]: GenericBlockState;
  [BlockIdentifier.Element113]: GenericBlockState;
  [BlockIdentifier.BlueStainedGlass]: GenericBlockState;
  [BlockIdentifier.Cake]: import("./blocks").CakeBlock;
  [BlockIdentifier.DarkOakDoubleSlab]: import("./blocks").DarkOakDoubleSlabBlock;
  [BlockIdentifier.StrippedCrimsonHyphae]: import("./blocks").StrippedCrimsonHyphaeBlock;
  [BlockIdentifier.DarkOakHangingSign]: import("./blocks").DarkOakHangingSignBlock;
  [BlockIdentifier.GreenConcrete]: GenericBlockState;
  [BlockIdentifier.Deepslate]: import("./blocks").DeepslateBlock;
  [BlockIdentifier.StrippedOakWood]: import("./blocks").StrippedOakWoodBlock;
  [BlockIdentifier.PurpurSlab]: import("./blocks").PurpurSlabBlock;
  [BlockIdentifier.MagentaCarpet]: GenericBlockState;
  [BlockIdentifier.PitcherCrop]: import("./blocks").PitcherCropBlock;
  [BlockIdentifier.BrownWool]: GenericBlockState;
  [BlockIdentifier.PinkWool]: GenericBlockState;
  [BlockIdentifier.WarpedStandingSign]: import("./blocks").WarpedStandingSignBlock;
  [BlockIdentifier.Deadbush]: GenericBlockState;
  [BlockIdentifier.EnderChest]: import("./blocks").EnderChestBlock;
  [BlockIdentifier.WaxedExposedChiseledCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.TuffSlab]: import("./blocks").TuffSlabBlock;
  [BlockIdentifier.RedstoneWire]: import("./blocks").RedstoneWireBlock;
  [BlockIdentifier.WarpedPressurePlate]: import("./blocks").WarpedPressurePlateBlock;
  [BlockIdentifier.GreenCandleCake]: import("./blocks").GreenCandleCakeBlock;
  [BlockIdentifier.DiamondBlock]: GenericBlockState;
  [BlockIdentifier.ExposedCopperBulb]: import("./blocks").ExposedCopperBulbBlock;
  [BlockIdentifier.Element58]: GenericBlockState;
  [BlockIdentifier.BambooMosaicDoubleSlab]: import("./blocks").BambooMosaicDoubleSlabBlock;
  [BlockIdentifier.DarkPrismarineDoubleSlab]: import("./blocks").DarkPrismarineDoubleSlabBlock;
  [BlockIdentifier.CryingObsidian]: GenericBlockState;
  [BlockIdentifier.OakStairs]: import("./blocks").OakStairsBlock;
  [BlockIdentifier.HardGrayStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.OakLog]: import("./blocks").OakLogBlock;
  [BlockIdentifier.WaxedWeatheredCutCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Andesite]: GenericBlockState;
  [BlockIdentifier.BrownStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.SculkVein]: import("./blocks").SculkVeinBlock;
  [BlockIdentifier.PinkStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.ExposedDoubleCutCopperSlab]: import("./blocks").ExposedDoubleCutCopperSlabBlock;
  [BlockIdentifier.CandleCake]: import("./blocks").CandleCakeBlock;
  [BlockIdentifier.MagentaShulkerBox]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PurpleTerracotta]: GenericBlockState;
  [BlockIdentifier.SmoothQuartz]: import("./blocks").SmoothQuartzBlock;
  [BlockIdentifier.PackedIce]: GenericBlockState;
  [BlockIdentifier.IronBars]: GenericBlockState;
  [BlockIdentifier.OxidizedCutCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PolishedGranite]: GenericBlockState;
  [BlockIdentifier.Element39]: GenericBlockState;
  [BlockIdentifier.LightBlueStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Fern]: import("./blocks").FernBlock;
  [BlockIdentifier.PackedMud]: GenericBlockState;
  [BlockIdentifier.LightBlueCandleCake]: import("./blocks").LightBlueCandleCakeBlock;
  [BlockIdentifier.Element1]: GenericBlockState;
  [BlockIdentifier.Poppy]: import("./blocks").PoppyBlock;
  [BlockIdentifier.MossCarpet]: GenericBlockState;
  [BlockIdentifier.CrimsonStairs]: import("./blocks").CrimsonStairsBlock;
  [BlockIdentifier.GreenStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WarpedFungus]: GenericBlockState;
  [BlockIdentifier.Element102]: GenericBlockState;
  [BlockIdentifier.StoneBrickDoubleSlab]: import("./blocks").StoneBrickDoubleSlabBlock;
  [BlockIdentifier.CopperOre]: GenericBlockState;
  [BlockIdentifier.GrayCandle]: import("./blocks").GrayCandleBlock;
  [BlockIdentifier.PolishedDeepslateSlab]: import("./blocks").PolishedDeepslateSlabBlock;
  [BlockIdentifier.BambooDoor]: import("./blocks").BambooDoorBlock;
  [BlockIdentifier.BlackConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.MelonStem]: import("./blocks").MelonStemBlock;
  [BlockIdentifier.AmethystBlock]: GenericBlockState;
  [BlockIdentifier.GoldBlock]: GenericBlockState;
  [BlockIdentifier.StrippedOakLog]: import("./blocks").StrippedOakLogBlock;
  [BlockIdentifier.FlowerPot]: import("./blocks").FlowerPotBlock;
  [BlockIdentifier.ChiseledBookshelf]: import("./blocks").ChiseledBookshelfBlock;
  [BlockIdentifier.JungleFence]: GenericBlockState;
  [BlockIdentifier.SpruceLog]: import("./blocks").SpruceLogBlock;
  [BlockIdentifier.PolishedDeepslateStairs]: import("./blocks").PolishedDeepslateStairsBlock;
  [BlockIdentifier.HardLimeStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.ShortGrass]: import("./blocks").ShortGrassBlock;
  [BlockIdentifier.LapisBlock]: GenericBlockState;
  [BlockIdentifier.WeatheredChiseledCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CoarseDirt]: GenericBlockState;
  [BlockIdentifier.SmallAmethystBud]: import("./blocks").SmallAmethystBudBlock;
  [BlockIdentifier.ActivatorRail]: import("./blocks").ActivatorRailBlock;
  [BlockIdentifier.Podzol]: GenericBlockState;
  [BlockIdentifier.MangroveButton]: import("./blocks").MangroveButtonBlock;
  [BlockIdentifier.IronTrapdoor]: import("./blocks").IronTrapdoorBlock;
  [BlockIdentifier.Potatoes]: import("./blocks").PotatoesBlock;
  [BlockIdentifier.LargeAmethystBud]: import("./blocks").LargeAmethystBudBlock;
  [BlockIdentifier.MuddyMangroveRoots]: import("./blocks").MuddyMangroveRootsBlock;
  [BlockIdentifier.HardLightBlueStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.TrialSpawner]: import("./blocks").TrialSpawnerBlock;
  [BlockIdentifier.StrippedJungleWood]: import("./blocks").StrippedJungleWoodBlock;
  [BlockIdentifier.DeadTubeCoralBlock]: import("./blocks").DeadTubeCoralBlockBlock;
  [BlockIdentifier.Noteblock]: GenericBlockState;
  [BlockIdentifier.Tuff]: GenericBlockState;
  [BlockIdentifier.Reserved6]: GenericBlockState;
  [BlockIdentifier.SoulTorch]: import("./blocks").SoulTorchBlock;
  [BlockIdentifier.QuartzBricks]: GenericBlockState;
  [BlockIdentifier.MangroveLog]: import("./blocks").MangroveLogBlock;
  [BlockIdentifier.SandstoneSlab]: import("./blocks").SandstoneSlabBlock;
  [BlockIdentifier.WhiteShulkerBox]: GenericBlockState;
  [BlockIdentifier.BirchWood]: import("./blocks").BirchWoodBlock;
  [BlockIdentifier.PolishedBlackstonePressurePlate]: import("./blocks").PolishedBlackstonePressurePlateBlock;
  [BlockIdentifier.MossyStoneBrickSlab]: import("./blocks").MossyStoneBrickSlabBlock;
  [BlockIdentifier.RawGoldBlock]: GenericBlockState;
  [BlockIdentifier.Allium]: import("./blocks").AlliumBlock;
  [BlockIdentifier.CrackedPolishedBlackstoneBricks]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.MobSpawner]: GenericBlockState;
  [BlockIdentifier.CopperGrate]: GenericBlockState;
  [BlockIdentifier.WeatheredDoubleCutCopperSlab]: import("./blocks").WeatheredDoubleCutCopperSlabBlock;
  [BlockIdentifier.DeepslateTiles]: GenericBlockState;
  [BlockIdentifier.BlackWool]: GenericBlockState;
  [BlockIdentifier.Lava]: import("./blocks").LavaBlock;
  [BlockIdentifier.LightBlock14]: import("./blocks").LightBlock14Block;
  [BlockIdentifier.AcaciaFenceGate]: import("./blocks").AcaciaFenceGateBlock;
  [BlockIdentifier.CyanCandleCake]: import("./blocks").CyanCandleCakeBlock;
  [BlockIdentifier.OrangeCandle]: import("./blocks").OrangeCandleBlock;
  [BlockIdentifier.ColoredTorchBp]: import("./blocks").ColoredTorchBpBlock;
  [BlockIdentifier.Scaffolding]: import("./blocks").ScaffoldingBlock;
  [BlockIdentifier.PoweredComparator]: import("./blocks").PoweredComparatorBlock;
  [BlockIdentifier.LightBlock8]: import("./blocks").LightBlock8Block;
  [BlockIdentifier.SpruceSapling]: import("./blocks").SpruceSaplingBlock;
  [BlockIdentifier.CutSandstoneDoubleSlab]: import("./blocks").CutSandstoneDoubleSlabBlock;
  [BlockIdentifier.BlastFurnace]: import("./blocks").BlastFurnaceBlock;
  [BlockIdentifier.CutSandstoneSlab]: import("./blocks").CutSandstoneSlabBlock;
  [BlockIdentifier.SpruceFence]: GenericBlockState;
  [BlockIdentifier.HardYellowStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.HardGreenStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DarkOakSapling]: import("./blocks").DarkOakSaplingBlock;
  [BlockIdentifier.SandstoneDoubleSlab]: import("./blocks").SandstoneDoubleSlabBlock;
  [BlockIdentifier.PinkPetals]: import("./blocks").PinkPetalsBlock;
  [BlockIdentifier.SoulFire]: import("./blocks").SoulFireBlock;
  [BlockIdentifier.PinkCarpet]: GenericBlockState;
  [BlockIdentifier.MangroveDoubleSlab]: import("./blocks").MangroveDoubleSlabBlock;
  [BlockIdentifier.BrownCarpet]: GenericBlockState;
  [BlockIdentifier.GreenCandle]: import("./blocks").GreenCandleBlock;
  [BlockIdentifier.PurpleStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.SmoothQuartzDoubleSlab]: import("./blocks").SmoothQuartzDoubleSlabBlock;
  [BlockIdentifier.OxidizedCopperTrapdoor]: import("./blocks").OxidizedCopperTrapdoorBlock;
  [BlockIdentifier.LightGrayStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BrainCoral]: import("./blocks").BrainCoralBlock;
  [BlockIdentifier.Obsidian]: GenericBlockState;
  [BlockIdentifier.Chest]: import("./blocks").ChestBlock;
  [BlockIdentifier.DeadBubbleCoralBlock]: import("./blocks").DeadBubbleCoralBlockBlock;
  [BlockIdentifier.LightGrayStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BlackstoneSlab]: import("./blocks").BlackstoneSlabBlock;
  [BlockIdentifier.StrippedSpruceWood]: import("./blocks").StrippedSpruceWoodBlock;
  [BlockIdentifier.Cauldron]: import("./blocks").CauldronBlock;
  [BlockIdentifier.Glowingobsidian]: GenericBlockState;
  [BlockIdentifier.DeepslateBrickWall]: import("./blocks").DeepslateBrickWallBlock;
  [BlockIdentifier.DarkoakStandingSign]: import("./blocks").DarkoakStandingSignBlock;
  [BlockIdentifier.WaxedExposedCopperGrate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.TubeCoralBlock]: import("./blocks").TubeCoralBlockBlock;
  [BlockIdentifier.AcaciaPlanks]: GenericBlockState;
  [BlockIdentifier.Element85]: GenericBlockState;
  [BlockIdentifier.JungleWallSign]: import("./blocks").JungleWallSignBlock;
  [BlockIdentifier.EndBrickStairs]: import("./blocks").EndBrickStairsBlock;
  [BlockIdentifier.PolishedBlackstoneDoubleSlab]: import("./blocks").PolishedBlackstoneDoubleSlabBlock;
  [BlockIdentifier.OrangeCarpet]: GenericBlockState;
  [BlockIdentifier.ExposedCopper]: GenericBlockState;
  [BlockIdentifier.PolishedDeepslateDoubleSlab]: import("./blocks").PolishedDeepslateDoubleSlabBlock;
  [BlockIdentifier.NetherBrickSlab]: import("./blocks").NetherBrickSlabBlock;
  [BlockIdentifier.HeavyWeightedPressurePlate]: import("./blocks").HeavyWeightedPressurePlateBlock;
  [BlockIdentifier.Element89]: GenericBlockState;
  [BlockIdentifier.StoneButton]: import("./blocks").StoneButtonBlock;
  [BlockIdentifier.Stone]: GenericBlockState;
  [BlockIdentifier.RedNetherBrickDoubleSlab]: import("./blocks").RedNetherBrickDoubleSlabBlock;
  [BlockIdentifier.PitcherPlant]: import("./blocks").PitcherPlantBlock;
  [BlockIdentifier.Element101]: GenericBlockState;
  [BlockIdentifier.WaxedCopperBulb]: import("./blocks").WaxedCopperBulbBlock;
  [BlockIdentifier.AndesiteStairs]: import("./blocks").AndesiteStairsBlock;
  [BlockIdentifier.Sponge]: import("./blocks").SpongeBlock;
  [BlockIdentifier.BoneBlock]: import("./blocks").BoneBlockBlock;
  [BlockIdentifier.NormalStoneStairs]: import("./blocks").NormalStoneStairsBlock;
  [BlockIdentifier.WarpedHangingSign]: import("./blocks").WarpedHangingSignBlock;
  [BlockIdentifier.GreenStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DioriteDoubleSlab]: import("./blocks").DioriteDoubleSlabBlock;
  [BlockIdentifier.GrayStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.EndStoneBrickSlab]: import("./blocks").EndStoneBrickSlabBlock;
  [BlockIdentifier.Frame]: import("./blocks").FrameBlock;
  [BlockIdentifier.Smoker]: import("./blocks").SmokerBlock;
  [BlockIdentifier.HardenedClay]: GenericBlockState;
  [BlockIdentifier.BirchHangingSign]: import("./blocks").BirchHangingSignBlock;
  [BlockIdentifier.PolishedTuffWall]: import("./blocks").PolishedTuffWallBlock;
  [BlockIdentifier.UnlitRedstoneTorch]: import("./blocks").UnlitRedstoneTorchBlock;
  [BlockIdentifier.StrippedJungleLog]: import("./blocks").StrippedJungleLogBlock;
  [BlockIdentifier.LapisOre]: GenericBlockState;
  [BlockIdentifier.HardBlueStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PolishedGraniteSlab]: import("./blocks").PolishedGraniteSlabBlock;
  [BlockIdentifier.LightBlock9]: import("./blocks").LightBlock9Block;
  [BlockIdentifier.OxidizedCutCopperSlab]: import("./blocks").OxidizedCutCopperSlabBlock;
  [BlockIdentifier.Beehive]: import("./blocks").BeehiveBlock;
  [BlockIdentifier.LimeStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.LightBlock7]: import("./blocks").LightBlock7Block;
  [BlockIdentifier.CherryDoubleSlab]: import("./blocks").CherryDoubleSlabBlock;
  [BlockIdentifier.LightBlock6]: import("./blocks").LightBlock6Block;
  [BlockIdentifier.LightBlock5]: import("./blocks").LightBlock5Block;
  [BlockIdentifier.WaxedOxidizedCutCopperStairs]: import("./blocks").WaxedOxidizedCutCopperStairsBlock;
  [BlockIdentifier.LightBlock4]: import("./blocks").LightBlock4Block;
  [BlockIdentifier.WarpedRoots]: GenericBlockState;
  [BlockIdentifier.SmallDripleafBlock]: import("./blocks").SmallDripleafBlockBlock;
  [BlockIdentifier.GreenWool]: GenericBlockState;
  [BlockIdentifier.LimeCandleCake]: import("./blocks").LimeCandleCakeBlock;
  [BlockIdentifier.MangroveLeaves]: import("./blocks").MangroveLeavesBlock;
  [BlockIdentifier.LightBlock3]: import("./blocks").LightBlock3Block;
  [BlockIdentifier.AcaciaLeaves]: import("./blocks").AcaciaLeavesBlock;
  [BlockIdentifier.Barrier]: GenericBlockState;
  [BlockIdentifier.RawIronBlock]: GenericBlockState;
  [BlockIdentifier.Dispenser]: import("./blocks").DispenserBlock;
  [BlockIdentifier.CrimsonRoots]: GenericBlockState;
  [BlockIdentifier.LightBlock2]: import("./blocks").LightBlock2Block;
  [BlockIdentifier.LightBlock0]: import("./blocks").LightBlock0Block;
  [BlockIdentifier.Stonecutter]: GenericBlockState;
  [BlockIdentifier.AndesiteDoubleSlab]: import("./blocks").AndesiteDoubleSlabBlock;
  [BlockIdentifier.UnpoweredRepeater]: import("./blocks").UnpoweredRepeaterBlock;
  [BlockIdentifier.OakSapling]: import("./blocks").OakSaplingBlock;
  [BlockIdentifier.LightGrayTerracotta]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PinkStainedGlass]: GenericBlockState;
  [BlockIdentifier.HardMagentaStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BrownStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.FireCoral]: import("./blocks").FireCoralBlock;
  [BlockIdentifier.CobbledDeepslate]: GenericBlockState;
  [BlockIdentifier.Element99]: GenericBlockState;
  [BlockIdentifier.BirchLog]: import("./blocks").BirchLogBlock;
  [BlockIdentifier.OrangeStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.OrangeWool]: GenericBlockState;
  [BlockIdentifier.PolishedBlackstoneBrickDoubleSlab]: import("./blocks").PolishedBlackstoneBrickDoubleSlabBlock;
  [BlockIdentifier.BubbleCoralBlock]: import("./blocks").BubbleCoralBlockBlock;
  [BlockIdentifier.CrimsonDoubleSlab]: import("./blocks").CrimsonDoubleSlabBlock;
  [BlockIdentifier.Kelp]: import("./blocks").KelpBlock;
  [BlockIdentifier.UnderwaterTorch]: import("./blocks").UnderwaterTorchBlock;
  [BlockIdentifier.RespawnAnchor]: import("./blocks").RespawnAnchorBlock;
  [BlockIdentifier.DeadFireCoralWallFan]: import("./blocks").DeadFireCoralWallFanBlock;
  [BlockIdentifier.LightGrayConcrete]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BirchPlanks]: GenericBlockState;
  [BlockIdentifier.SeaPickle]: import("./blocks").SeaPickleBlock;
  [BlockIdentifier.RedSandstoneDoubleSlab]: import("./blocks").RedSandstoneDoubleSlabBlock;
  [BlockIdentifier.Element74]: GenericBlockState;
  [BlockIdentifier.RedSand]: import("./blocks").RedSandBlock;
  [BlockIdentifier.HayBlock]: import("./blocks").HayBlockBlock;
  [BlockIdentifier.SuspiciousGravel]: import("./blocks").SuspiciousGravelBlock;
  [BlockIdentifier.HeavyCore]: GenericBlockState;
  [BlockIdentifier.JungleWood]: import("./blocks").JungleWoodBlock;
  [BlockIdentifier.RedStainedGlass]: GenericBlockState;
  [BlockIdentifier.PurpleShulkerBox]: GenericBlockState;
  [BlockIdentifier.PolishedTuffDoubleSlab]: import("./blocks").PolishedTuffDoubleSlabBlock;
  [BlockIdentifier.OxidizedCopperDoor]: import("./blocks").OxidizedCopperDoorBlock;
  [BlockIdentifier.WaxedWeatheredCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.ChiseledQuartzBlock]: import("./blocks").ChiseledQuartzBlockBlock;
  [BlockIdentifier.InfestedCrackedStoneBricks]: import("./blocks").InfestedCrackedStoneBricksBlock;
  [BlockIdentifier.LightBlueTerracotta]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DeepslateBrickSlab]: import("./blocks").DeepslateBrickSlabBlock;
  [BlockIdentifier.FloweringAzalea]: GenericBlockState;
  [BlockIdentifier.InvisibleBedrock]: GenericBlockState;
  [BlockIdentifier.OakLeaves]: import("./blocks").OakLeavesBlock;
  [BlockIdentifier.BrainCoralFan]: import("./blocks").BrainCoralFanBlock;
  [BlockIdentifier.BambooStairs]: import("./blocks").BambooStairsBlock;
  [BlockIdentifier.Torch]: import("./blocks").TorchBlock;
  [BlockIdentifier.GlowLichen]: import("./blocks").GlowLichenBlock;
  [BlockIdentifier.CopperTrapdoor]: import("./blocks").CopperTrapdoorBlock;
  [BlockIdentifier.RedCandle]: import("./blocks").RedCandleBlock;
  [BlockIdentifier.MudBrickWall]: import("./blocks").MudBrickWallBlock;
  [BlockIdentifier.HoneyBlock]: GenericBlockState;
  [BlockIdentifier.CherryTrapdoor]: import("./blocks").CherryTrapdoorBlock;
  [BlockIdentifier.BrownConcrete]: GenericBlockState;
  [BlockIdentifier.LitPumpkin]: import("./blocks").LitPumpkinBlock;
  [BlockIdentifier.PinkConcrete]: GenericBlockState;
  [BlockIdentifier.YellowGlazedTerracotta]: import("./blocks").YellowGlazedTerracottaBlock;
  [BlockIdentifier.SmoothBasalt]: GenericBlockState;
  [BlockIdentifier.WarpedPlanks]: GenericBlockState;
  [BlockIdentifier.Piston]: import("./blocks").PistonBlock;
  [BlockIdentifier.CherryFence]: GenericBlockState;
  [BlockIdentifier.MangrovePlanks]: GenericBlockState;
  [BlockIdentifier.HardLightGrayStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.RedTerracotta]: GenericBlockState;
  [BlockIdentifier.Water]: import("./blocks").WaterBlock;
  [BlockIdentifier.WeatheredCopperTrapdoor]: import("./blocks").WeatheredCopperTrapdoorBlock;
  [BlockIdentifier.Element77]: GenericBlockState;
  [BlockIdentifier.WeatheredCopperGrate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.SpruceButton]: import("./blocks").SpruceButtonBlock;
  [BlockIdentifier.WallBanner]: import("./blocks").WallBannerBlock;
  [BlockIdentifier.DeadFireCoralBlock]: import("./blocks").DeadFireCoralBlockBlock;
  [BlockIdentifier.MagentaWool]: GenericBlockState;
  [BlockIdentifier.WaxedWeatheredCopperGrate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WaxedWeatheredCopperBulb]: import("./blocks").WaxedWeatheredCopperBulbBlock;
  [BlockIdentifier.VerdantFroglight]: import("./blocks").VerdantFroglightBlock;
  [BlockIdentifier.MossyCobblestoneSlab]: import("./blocks").MossyCobblestoneSlabBlock;
  [BlockIdentifier.MagentaGlazedTerracotta]: import("./blocks").MagentaGlazedTerracottaBlock;
  [BlockIdentifier.PolishedAndesite]: GenericBlockState;
  [BlockIdentifier.PurpleStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.QuartzDoubleSlab]: import("./blocks").QuartzDoubleSlabBlock;
  [BlockIdentifier.MangroveSlab]: import("./blocks").MangroveSlabBlock;
  [BlockIdentifier.WallSign]: import("./blocks").WallSignBlock;
  [BlockIdentifier.InfestedDeepslate]: import("./blocks").InfestedDeepslateBlock;
  [BlockIdentifier.OrangeGlazedTerracotta]: import("./blocks").OrangeGlazedTerracottaBlock;
  [BlockIdentifier.BirchSapling]: import("./blocks").BirchSaplingBlock;
  [BlockIdentifier.ClientRequestPlaceholderBlock]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.HardBrownStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Torchflower]: GenericBlockState;
  [BlockIdentifier.SporeBlossom]: GenericBlockState;
  [BlockIdentifier.Waterlily]: GenericBlockState;
  [BlockIdentifier.EmeraldBlock]: GenericBlockState;
  [BlockIdentifier.Conduit]: GenericBlockState;
  [BlockIdentifier.Anvil]: import("./blocks").AnvilBlock;
  [BlockIdentifier.SuspiciousSand]: import("./blocks").SuspiciousSandBlock;
  [BlockIdentifier.AncientDebris]: GenericBlockState;
  [BlockIdentifier.DarkOakPlanks]: GenericBlockState;
  [BlockIdentifier.JungleLeaves]: import("./blocks").JungleLeavesBlock;
  [BlockIdentifier.LightningRod]: import("./blocks").LightningRodBlock;
  [BlockIdentifier.NetherBrickFence]: GenericBlockState;
  [BlockIdentifier.BlackStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.MagentaConcrete]: GenericBlockState;
  [BlockIdentifier.CobblestoneWall]: import("./blocks").CobblestoneWallBlock;
  [BlockIdentifier.LightBlueStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DeepslateBrickDoubleSlab]: import("./blocks").DeepslateBrickDoubleSlabBlock;
  [BlockIdentifier.TubeCoralWallFan]: import("./blocks").TubeCoralWallFanBlock;
  [BlockIdentifier.SpruceDoubleSlab]: import("./blocks").SpruceDoubleSlabBlock;
  [BlockIdentifier.RedSandstone]: import("./blocks").RedSandstoneBlock;
  [BlockIdentifier.DarkOakLog]: import("./blocks").DarkOakLogBlock;
  [BlockIdentifier.OakPlanks]: GenericBlockState;
  [BlockIdentifier.RedstoneOre]: GenericBlockState;
  [BlockIdentifier.AcaciaHangingSign]: import("./blocks").AcaciaHangingSignBlock;
  [BlockIdentifier.LightBlock13]: import("./blocks").LightBlock13Block;
  [BlockIdentifier.OchreFroglight]: import("./blocks").OchreFroglightBlock;
  [BlockIdentifier.PolishedBlackstoneStairs]: import("./blocks").PolishedBlackstoneStairsBlock;
  [BlockIdentifier.TuffWall]: import("./blocks").TuffWallBlock;
  [BlockIdentifier.MangrovePressurePlate]: import("./blocks").MangrovePressurePlateBlock;
  [BlockIdentifier.Observer]: import("./blocks").ObserverBlock;
  [BlockIdentifier.PinkGlazedTerracotta]: import("./blocks").PinkGlazedTerracottaBlock;
  [BlockIdentifier.YellowTerracotta]: GenericBlockState;
  [BlockIdentifier.BrownGlazedTerracotta]: import("./blocks").BrownGlazedTerracottaBlock;
  [BlockIdentifier.BrownCandleCake]: import("./blocks").BrownCandleCakeBlock;
  [BlockIdentifier.PinkCandleCake]: import("./blocks").PinkCandleCakeBlock;
  [BlockIdentifier.QuartzBlock]: import("./blocks").QuartzBlockBlock;
  [BlockIdentifier.RedstoneTorch]: import("./blocks").RedstoneTorchBlock;
  [BlockIdentifier.BirchLeaves]: import("./blocks").BirchLeavesBlock;
  [BlockIdentifier.SilverGlazedTerracotta]: import("./blocks").SilverGlazedTerracottaBlock;
  [BlockIdentifier.CyanConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.OxidizedCopper]: GenericBlockState;
  [BlockIdentifier.BirchPressurePlate]: import("./blocks").BirchPressurePlateBlock;
  [BlockIdentifier.Element19]: GenericBlockState;
  [BlockIdentifier.SandstoneStairs]: import("./blocks").SandstoneStairsBlock;
  [BlockIdentifier.StrippedBambooBlock]: import("./blocks").StrippedBambooBlockBlock;
  [BlockIdentifier.CrackedStoneBricks]: import("./blocks").CrackedStoneBricksBlock;
  [BlockIdentifier.DeadTubeCoralWallFan]: import("./blocks").DeadTubeCoralWallFanBlock;
  [BlockIdentifier.BirchFenceGate]: import("./blocks").BirchFenceGateBlock;
  [BlockIdentifier.SculkCatalyst]: import("./blocks").SculkCatalystBlock;
  [BlockIdentifier.Element115]: GenericBlockState;
  [BlockIdentifier.Cobblestone]: GenericBlockState;
  [BlockIdentifier.HornCoral]: import("./blocks").HornCoralBlock;
  [BlockIdentifier.WhiteConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.YellowConcrete]: GenericBlockState;
  [BlockIdentifier.OakDoubleSlab]: import("./blocks").OakDoubleSlabBlock;
  [BlockIdentifier.StrippedWarpedStem]: import("./blocks").StrippedWarpedStemBlock;
  [BlockIdentifier.DaylightDetector]: import("./blocks").DaylightDetectorBlock;
  [BlockIdentifier.SmoothSandstoneStairs]: import("./blocks").SmoothSandstoneStairsBlock;
  [BlockIdentifier.JunglePressurePlate]: import("./blocks").JunglePressurePlateBlock;
  [BlockIdentifier.HardWhiteStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DoubleCutCopperSlab]: import("./blocks").DoubleCutCopperSlabBlock;
  [BlockIdentifier.BirchButton]: import("./blocks").BirchButtonBlock;
  [BlockIdentifier.CrimsonPlanks]: GenericBlockState;
  [BlockIdentifier.Sandstone]: import("./blocks").SandstoneBlock;
  [BlockIdentifier.BlackstoneWall]: import("./blocks").BlackstoneWallBlock;
  [BlockIdentifier.LightWeightedPressurePlate]: import("./blocks").LightWeightedPressurePlateBlock;
  [BlockIdentifier.PolishedBlackstone]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Bamboo]: import("./blocks").BambooBlock;
  [BlockIdentifier.RedNetherBrickSlab]: import("./blocks").RedNetherBrickSlabBlock;
  [BlockIdentifier.IronOre]: GenericBlockState;
  [BlockIdentifier.WaxedWeatheredChiseledCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Element17]: GenericBlockState;
  [BlockIdentifier.StickyPistonArmCollision]: import("./blocks").StickyPistonArmCollisionBlock;
  [BlockIdentifier.Element51]: GenericBlockState;
  [BlockIdentifier.GrayStainedGlass]: GenericBlockState;
  [BlockIdentifier.ExposedCutCopperSlab]: import("./blocks").ExposedCutCopperSlabBlock;
  [BlockIdentifier.Element52]: GenericBlockState;
  [BlockIdentifier.WarpedStairs]: import("./blocks").WarpedStairsBlock;
  [BlockIdentifier.Bedrock]: import("./blocks").BedrockBlock;
  [BlockIdentifier.SmithingTable]: GenericBlockState;
  [BlockIdentifier.LightBlock10]: import("./blocks").LightBlock10Block;
  [BlockIdentifier.TuffBrickSlab]: import("./blocks").TuffBrickSlabBlock;
  [BlockIdentifier.RoseBush]: import("./blocks").RoseBushBlock;
  [BlockIdentifier.GreenCarpet]: GenericBlockState;
  [BlockIdentifier.PurpleCandleCake]: import("./blocks").PurpleCandleCakeBlock;
  [BlockIdentifier.PrismarineBrickSlab]: import("./blocks").PrismarineBrickSlabBlock;
  [BlockIdentifier.CyanConcrete]: GenericBlockState;
  [BlockIdentifier.NetheriteBlock]: GenericBlockState;
  [BlockIdentifier.RedstoneBlock]: GenericBlockState;
  [BlockIdentifier.PolishedBlackstoneWall]: import("./blocks").PolishedBlackstoneWallBlock;
  [BlockIdentifier.QuartzPillar]: import("./blocks").QuartzPillarBlock;
  [BlockIdentifier.WaxedExposedCutCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.GildedBlackstone]: GenericBlockState;
  [BlockIdentifier.JungleHangingSign]: import("./blocks").JungleHangingSignBlock;
  [BlockIdentifier.BlueConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CherryWood]: import("./blocks").CherryWoodBlock;
  [BlockIdentifier.BirchSlab]: import("./blocks").BirchSlabBlock;
  [BlockIdentifier.EndStone]: GenericBlockState;
  [BlockIdentifier.CrimsonDoor]: import("./blocks").CrimsonDoorBlock;
  [BlockIdentifier.JungleSlab]: import("./blocks").JungleSlabBlock;
  [BlockIdentifier.WaxedOxidizedCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Glowstone]: GenericBlockState;
  [BlockIdentifier.StonePressurePlate]: import("./blocks").StonePressurePlateBlock;
  [BlockIdentifier.QuartzStairs]: import("./blocks").QuartzStairsBlock;
  [BlockIdentifier.WaxedExposedCutCopperStairs]: import("./blocks").WaxedExposedCutCopperStairsBlock;
  [BlockIdentifier.HardLimeStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.MudBrickSlab]: import("./blocks").MudBrickSlabBlock;
  [BlockIdentifier.CrackedDeepslateTiles]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Farmland]: import("./blocks").FarmlandBlock;
  [BlockIdentifier.DeadBrainCoralWallFan]: import("./blocks").DeadBrainCoralWallFanBlock;
  [BlockIdentifier.PinkCandle]: import("./blocks").PinkCandleBlock;
  [BlockIdentifier.NormalStoneDoubleSlab]: import("./blocks").NormalStoneDoubleSlabBlock;
  [BlockIdentifier.BrownCandle]: import("./blocks").BrownCandleBlock;
  [BlockIdentifier.LightBlock12]: import("./blocks").LightBlock12Block;
  [BlockIdentifier.Rail]: import("./blocks").RailBlock;
  [BlockIdentifier.SoulLantern]: import("./blocks").SoulLanternBlock;
  [BlockIdentifier.Carrots]: import("./blocks").CarrotsBlock;
  [BlockIdentifier.AcaciaTrapdoor]: import("./blocks").AcaciaTrapdoorBlock;
  [BlockIdentifier.StoneBricks]: import("./blocks").StoneBricksBlock;
  [BlockIdentifier.MossyCobblestoneStairs]: import("./blocks").MossyCobblestoneStairsBlock;
  [BlockIdentifier.HardMagentaStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PinkTerracotta]: GenericBlockState;
  [BlockIdentifier.WaxedWeatheredCopperDoor]: import("./blocks").WaxedWeatheredCopperDoorBlock;
  [BlockIdentifier.DarkPrismarine]: import("./blocks").DarkPrismarineBlock;
  [BlockIdentifier.InfestedCobblestone]: import("./blocks").InfestedCobblestoneBlock;
  [BlockIdentifier.BrainCoralWallFan]: import("./blocks").BrainCoralWallFanBlock;
  [BlockIdentifier.MangroveWood]: import("./blocks").MangroveWoodBlock;
  [BlockIdentifier.CraftingTable]: GenericBlockState;
  [BlockIdentifier.RedGlazedTerracotta]: import("./blocks").RedGlazedTerracottaBlock;
  [BlockIdentifier.DarkOakFenceGate]: import("./blocks").DarkOakFenceGateBlock;
  [BlockIdentifier.CherryButton]: import("./blocks").CherryButtonBlock;
  [BlockIdentifier.CrimsonNylium]: GenericBlockState;
  [BlockIdentifier.WarpedDoubleSlab]: import("./blocks").WarpedDoubleSlabBlock;
  [BlockIdentifier.StructureVoid]: import("./blocks").StructureVoidBlock;
  [BlockIdentifier.BambooFenceGate]: import("./blocks").BambooFenceGateBlock;
  [BlockIdentifier.PurpleConcrete]: GenericBlockState;
  [BlockIdentifier.WhiteStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WaxedExposedCopperBulb]: import("./blocks").WaxedExposedCopperBulbBlock;
  [BlockIdentifier.BubbleCoral]: import("./blocks").BubbleCoralBlock;
  [BlockIdentifier.CoalOre]: GenericBlockState;
  [BlockIdentifier.PolishedBlackstoneBrickSlab]: import("./blocks").PolishedBlackstoneBrickSlabBlock;
  [BlockIdentifier.NormalStoneSlab]: import("./blocks").NormalStoneSlabBlock;
  [BlockIdentifier.PurpleCandle]: import("./blocks").PurpleCandleBlock;
  [BlockIdentifier.Snow]: GenericBlockState;
  [BlockIdentifier.CalibratedSculkSensor]: import("./blocks").CalibratedSculkSensorBlock;
  [BlockIdentifier.YellowConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.OakSlab]: import("./blocks").OakSlabBlock;
  [BlockIdentifier.Sand]: import("./blocks").SandBlock;
  [BlockIdentifier.MangroveStandingSign]: import("./blocks").MangroveStandingSignBlock;
  [BlockIdentifier.Slime]: GenericBlockState;
  [BlockIdentifier.Element117]: GenericBlockState;
  [BlockIdentifier.JungleStairs]: import("./blocks").JungleStairsBlock;
  [BlockIdentifier.MossyStoneBrickDoubleSlab]: import("./blocks").MossyStoneBrickDoubleSlabBlock;
  [BlockIdentifier.CutRedSandstoneDoubleSlab]: import("./blocks").CutRedSandstoneDoubleSlabBlock;
  [BlockIdentifier.AzaleaLeaves]: import("./blocks").AzaleaLeavesBlock;
  [BlockIdentifier.BambooDoubleSlab]: import("./blocks").BambooDoubleSlabBlock;
  [BlockIdentifier.ChiseledPolishedBlackstone]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.SmoothStoneSlab]: import("./blocks").SmoothStoneSlabBlock;
  [BlockIdentifier.InfestedChiseledStoneBricks]: import("./blocks").InfestedChiseledStoneBricksBlock;
  [BlockIdentifier.BrownConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PinkConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CrackedDeepslateBricks]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DeadTubeCoral]: import("./blocks").DeadTubeCoralBlock;
  [BlockIdentifier.AcaciaDoor]: import("./blocks").AcaciaDoorBlock;
  [BlockIdentifier.OrangeShulkerBox]: GenericBlockState;
  [BlockIdentifier.NetherWartBlock]: GenericBlockState;
  [BlockIdentifier.LightBlueGlazedTerracotta]: import("./blocks").LightBlueGlazedTerracottaBlock;
  [BlockIdentifier.PrismarineSlab]: import("./blocks").PrismarineSlabBlock;
  [BlockIdentifier.PrismarineDoubleSlab]: import("./blocks").PrismarineDoubleSlabBlock;
  [BlockIdentifier.LightBlock11]: import("./blocks").LightBlock11Block;
  [BlockIdentifier.CherryDoor]: import("./blocks").CherryDoorBlock;
  [BlockIdentifier.WeatheredCutCopperStairs]: import("./blocks").WeatheredCutCopperStairsBlock;
  [BlockIdentifier.AcaciaLog]: import("./blocks").AcaciaLogBlock;
  [BlockIdentifier.FlowingLava]: import("./blocks").FlowingLavaBlock;
  [BlockIdentifier.WhiteTerracotta]: GenericBlockState;
  [BlockIdentifier.CrimsonTrapdoor]: import("./blocks").CrimsonTrapdoorBlock;
  [BlockIdentifier.BlueShulkerBox]: GenericBlockState;
  [BlockIdentifier.Basalt]: import("./blocks").BasaltBlock;
  [BlockIdentifier.WaxedWeatheredCopperTrapdoor]: import("./blocks").WaxedWeatheredCopperTrapdoorBlock;
  [BlockIdentifier.HardCyanStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PolishedDiorite]: GenericBlockState;
  [BlockIdentifier.Element13]: GenericBlockState;
  [BlockIdentifier.CyanGlazedTerracotta]: import("./blocks").CyanGlazedTerracottaBlock;
  [BlockIdentifier.LitRedstoneLamp]: GenericBlockState;
  [BlockIdentifier.HardPurpleStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.YellowCandleCake]: import("./blocks").YellowCandleCakeBlock;
  [BlockIdentifier.StickyPiston]: import("./blocks").StickyPistonBlock;
  [BlockIdentifier.MediumAmethystBud]: import("./blocks").MediumAmethystBudBlock;
  [BlockIdentifier.BrownShulkerBox]: GenericBlockState;
  [BlockIdentifier.PinkShulkerBox]: GenericBlockState;
  [BlockIdentifier.LightBlueCandle]: import("./blocks").LightBlueCandleBlock;
  [BlockIdentifier.DeepslateTileStairs]: import("./blocks").DeepslateTileStairsBlock;
  [BlockIdentifier.SculkSensor]: import("./blocks").SculkSensorBlock;
  [BlockIdentifier.CopperBulb]: import("./blocks").CopperBulbBlock;
  [BlockIdentifier.Element6]: GenericBlockState;
  [BlockIdentifier.Element97]: GenericBlockState;
  [BlockIdentifier.DioriteStairs]: import("./blocks").DioriteStairsBlock;
  [BlockIdentifier.SmoothStoneDoubleSlab]: import("./blocks").SmoothStoneDoubleSlabBlock;
  [BlockIdentifier.SpruceLeaves]: import("./blocks").SpruceLeavesBlock;
  [BlockIdentifier.RedStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.FrogSpawn]: GenericBlockState;
  [BlockIdentifier.Element111]: GenericBlockState;
  [BlockIdentifier.CrimsonFenceGate]: import("./blocks").CrimsonFenceGateBlock;
  [BlockIdentifier.RedCarpet]: GenericBlockState;
  [BlockIdentifier.SmoothSandstoneDoubleSlab]: import("./blocks").SmoothSandstoneDoubleSlabBlock;
  [BlockIdentifier.RedShulkerBox]: GenericBlockState;
  [BlockIdentifier.DirtWithRoots]: GenericBlockState;
  [BlockIdentifier.StrippedCherryLog]: import("./blocks").StrippedCherryLogBlock;
  [BlockIdentifier.HornCoralWallFan]: import("./blocks").HornCoralWallFanBlock;
  [BlockIdentifier.CopperDoor]: import("./blocks").CopperDoorBlock;
  [BlockIdentifier.CrimsonButton]: import("./blocks").CrimsonButtonBlock;
  [BlockIdentifier.MagentaConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PrismarineStairs]: import("./blocks").PrismarineStairsBlock;
  [BlockIdentifier.IronDoor]: import("./blocks").IronDoorBlock;
  [BlockIdentifier.MangroveTrapdoor]: import("./blocks").MangroveTrapdoorBlock;
  [BlockIdentifier.DaylightDetectorInverted]: import("./blocks").DaylightDetectorInvertedBlock;
  [BlockIdentifier.JunglePlanks]: GenericBlockState;
  [BlockIdentifier.ChorusFlower]: import("./blocks").ChorusFlowerBlock;
  [BlockIdentifier.TorchflowerCrop]: import("./blocks").TorchflowerCropBlock;
  [BlockIdentifier.CrackedNetherBricks]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Pumpkin]: import("./blocks").PumpkinBlock;
  [BlockIdentifier.SmoothStone]: GenericBlockState;
  [BlockIdentifier.GraniteSlab]: import("./blocks").GraniteSlabBlock;
  [BlockIdentifier.LimeConcrete]: GenericBlockState;
  [BlockIdentifier.WaxedWeatheredCutCopperSlab]: import("./blocks").WaxedWeatheredCutCopperSlabBlock;
  [BlockIdentifier.RedMushroom]: GenericBlockState;
  [BlockIdentifier.HardYellowStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.MagentaTerracotta]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BlackCarpet]: GenericBlockState;
  [BlockIdentifier.ExposedCutCopperStairs]: import("./blocks").ExposedCutCopperStairsBlock;
  [BlockIdentifier.MangroveStairs]: import("./blocks").MangroveStairsBlock;
  [BlockIdentifier.PolishedDioriteSlab]: import("./blocks").PolishedDioriteSlabBlock;
  [BlockIdentifier.RedSandstoneStairs]: import("./blocks").RedSandstoneStairsBlock;
  [BlockIdentifier.LightBlueConcrete]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.MangroveFenceGate]: import("./blocks").MangroveFenceGateBlock;
  [BlockIdentifier.BubbleColumn]: import("./blocks").BubbleColumnBlock;
  [BlockIdentifier.Sunflower]: import("./blocks").SunflowerBlock;
  [BlockIdentifier.Allow]: GenericBlockState;
  [BlockIdentifier.GrayConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BambooHangingSign]: import("./blocks").BambooHangingSignBlock;
  [BlockIdentifier.WitherRose]: GenericBlockState;
  [BlockIdentifier.CopperBlock]: GenericBlockState;
  [BlockIdentifier.BirchDoubleSlab]: import("./blocks").BirchDoubleSlabBlock;
  [BlockIdentifier.WaxedWeatheredDoubleCutCopperSlab]: import("./blocks").WaxedWeatheredDoubleCutCopperSlabBlock;
  [BlockIdentifier.PolishedBlackstoneBricks]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CutCopper]: GenericBlockState;
  [BlockIdentifier.FrostedIce]: import("./blocks").FrostedIceBlock;
  [BlockIdentifier.SpruceDoor]: import("./blocks").SpruceDoorBlock;
  [BlockIdentifier.ChiseledSandstone]: import("./blocks").ChiseledSandstoneBlock;
  [BlockIdentifier.ChippedAnvil]: import("./blocks").ChippedAnvilBlock;
  [BlockIdentifier.WarpedTrapdoor]: import("./blocks").WarpedTrapdoorBlock;
  [BlockIdentifier.OrangeConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.FlowingWater]: import("./blocks").FlowingWaterBlock;
  [BlockIdentifier.BrickBlock]: GenericBlockState;
  [BlockIdentifier.HardGlass]: GenericBlockState;
  [BlockIdentifier.CaveVines]: import("./blocks").CaveVinesBlock;
  [BlockIdentifier.MagentaStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Element62]: GenericBlockState;
  [BlockIdentifier.LightBlueCarpet]: GenericBlockState;
  [BlockIdentifier.OakHangingSign]: import("./blocks").OakHangingSignBlock;
  [BlockIdentifier.StrippedDarkOakWood]: import("./blocks").StrippedDarkOakWoodBlock;
  [BlockIdentifier.WhiteStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.OakWood]: import("./blocks").OakWoodBlock;
  [BlockIdentifier.WaxedExposedDoubleCutCopperSlab]: import("./blocks").WaxedExposedDoubleCutCopperSlabBlock;
  [BlockIdentifier.WaxedOxidizedCopperTrapdoor]: import("./blocks").WaxedOxidizedCopperTrapdoorBlock;
  [BlockIdentifier.Jukebox]: GenericBlockState;
  [BlockIdentifier.StrippedCherryWood]: import("./blocks").StrippedCherryWoodBlock;
  [BlockIdentifier.AcaciaPressurePlate]: import("./blocks").AcaciaPressurePlateBlock;
  [BlockIdentifier.SmoothRedSandstoneSlab]: import("./blocks").SmoothRedSandstoneSlabBlock;
  [BlockIdentifier.Jigsaw]: import("./blocks").JigsawBlock;
  [BlockIdentifier.BorderBlock]: import("./blocks").BorderBlockBlock;
  [BlockIdentifier.Shroomlight]: GenericBlockState;
  [BlockIdentifier.YellowCandle]: import("./blocks").YellowCandleBlock;
  [BlockIdentifier.DarkOakStairs]: import("./blocks").DarkOakStairsBlock;
  [BlockIdentifier.DeepslateTileWall]: import("./blocks").DeepslateTileWallBlock;
  [BlockIdentifier.GlassPane]: GenericBlockState;
  [BlockIdentifier.ChiseledDeepslate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CutCopperSlab]: import("./blocks").CutCopperSlabBlock;
  [BlockIdentifier.InfestedStoneBricks]: import("./blocks").InfestedStoneBricksBlock;
  [BlockIdentifier.BambooTrapdoor]: import("./blocks").BambooTrapdoorBlock;
  [BlockIdentifier.OxidizedChiseledCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DarkOakTrapdoor]: import("./blocks").DarkOakTrapdoorBlock;
  [BlockIdentifier.MangroveWallSign]: import("./blocks").MangroveWallSignBlock;
  [BlockIdentifier.Beetroot]: import("./blocks").BeetrootBlock;
  [BlockIdentifier.RawCopperBlock]: GenericBlockState;
  [BlockIdentifier.HornCoralBlock]: import("./blocks").HornCoralBlockBlock;
  [BlockIdentifier.Skull]: import("./blocks").SkullBlock;
  [BlockIdentifier.LightGrayCandleCake]: import("./blocks").LightGrayCandleCakeBlock;
  [BlockIdentifier.Element95]: GenericBlockState;
  [BlockIdentifier.WhiteCandle]: import("./blocks").WhiteCandleBlock;
  [BlockIdentifier.GoldenRail]: import("./blocks").GoldenRailBlock;
  [BlockIdentifier.LitFurnace]: import("./blocks").LitFurnaceBlock;
  [BlockIdentifier.CyanWool]: GenericBlockState;
  [BlockIdentifier.PetrifiedOakDoubleSlab]: import("./blocks").PetrifiedOakDoubleSlabBlock;
  [BlockIdentifier.StructureBlock]: import("./blocks").StructureBlockBlock;
  [BlockIdentifier.TintedGlass]: GenericBlockState;
  [BlockIdentifier.DeprecatedAnvil]: import("./blocks").DeprecatedAnvilBlock;
  [BlockIdentifier.GrayShulkerBox]: GenericBlockState;
  [BlockIdentifier.FireCoralWallFan]: import("./blocks").FireCoralWallFanBlock;
  [BlockIdentifier.JungleFenceGate]: import("./blocks").JungleFenceGateBlock;
  [BlockIdentifier.ExposedCopperGrate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WaxedCopperGrate]: GenericBlockState;
  [BlockIdentifier.DeadBrainCoral]: import("./blocks").DeadBrainCoralBlock;
  [BlockIdentifier.JungleTrapdoor]: import("./blocks").JungleTrapdoorBlock;
  [BlockIdentifier.SpruceWallSign]: import("./blocks").SpruceWallSignBlock;
  [BlockIdentifier.CoalBlock]: GenericBlockState;
  [BlockIdentifier.WarpedFenceGate]: import("./blocks").WarpedFenceGateBlock;
  [BlockIdentifier.Composter]: import("./blocks").ComposterBlock;
  [BlockIdentifier.Element44]: GenericBlockState;
  [BlockIdentifier.WaxedDoubleCutCopperSlab]: import("./blocks").WaxedDoubleCutCopperSlabBlock;
  [BlockIdentifier.WaxedExposedCopperDoor]: import("./blocks").WaxedExposedCopperDoorBlock;
  [BlockIdentifier.BlueGlazedTerracotta]: import("./blocks").BlueGlazedTerracottaBlock;
  [BlockIdentifier.BlueWool]: GenericBlockState;
  [BlockIdentifier.Clay]: GenericBlockState;
  [BlockIdentifier.WeepingVines]: import("./blocks").WeepingVinesBlock;
  [BlockIdentifier.ChorusPlant]: GenericBlockState;
  [BlockIdentifier.MudBrickStairs]: import("./blocks").MudBrickStairsBlock;
  [BlockIdentifier.SmoothRedSandstoneStairs]: import("./blocks").SmoothRedSandstoneStairsBlock;
  [BlockIdentifier.Element100]: GenericBlockState;
  [BlockIdentifier.Element103]: GenericBlockState;
  [BlockIdentifier.Element105]: GenericBlockState;
  [BlockIdentifier.CrimsonPressurePlate]: import("./blocks").CrimsonPressurePlateBlock;
  [BlockIdentifier.Element106]: GenericBlockState;
  [BlockIdentifier.Element107]: GenericBlockState;
  [BlockIdentifier.HardGrayStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Element108]: GenericBlockState;
  [BlockIdentifier.Element109]: GenericBlockState;
  [BlockIdentifier.LightGrayShulkerBox]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Element112]: GenericBlockState;
  [BlockIdentifier.Element110]: GenericBlockState;
  [BlockIdentifier.Element116]: GenericBlockState;
  [BlockIdentifier.Element114]: GenericBlockState;
  [BlockIdentifier.WhiteGlazedTerracotta]: import("./blocks").WhiteGlazedTerracottaBlock;
  [BlockIdentifier.StrippedWarpedHyphae]: import("./blocks").StrippedWarpedHyphaeBlock;
  [BlockIdentifier.Element50]: GenericBlockState;
  [BlockIdentifier.PumpkinStem]: import("./blocks").PumpkinStemBlock;
  [BlockIdentifier.Lever]: import("./blocks").LeverBlock;
  [BlockIdentifier.MovingBlock]: GenericBlockState;
  [BlockIdentifier.TrappedChest]: import("./blocks").TrappedChestBlock;
  [BlockIdentifier.LightGrayConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BrainCoralBlock]: import("./blocks").BrainCoralBlockBlock;
  [BlockIdentifier.StandingSign]: import("./blocks").StandingSignBlock;
  [BlockIdentifier.PurpleConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BambooPlanks]: GenericBlockState;
  [BlockIdentifier.CommandBlock]: import("./blocks").CommandBlockBlock;
  [BlockIdentifier.TwistingVines]: import("./blocks").TwistingVinesBlock;
  [BlockIdentifier.AcaciaDoubleSlab]: import("./blocks").AcaciaDoubleSlabBlock;
  [BlockIdentifier.PolishedAndesiteDoubleSlab]: import("./blocks").PolishedAndesiteDoubleSlabBlock;
  [BlockIdentifier.Magma]: GenericBlockState;
  [BlockIdentifier.Dirt]: GenericBlockState;
  [BlockIdentifier.Reeds]: import("./blocks").ReedsBlock;
  [BlockIdentifier.Deny]: GenericBlockState;
  [BlockIdentifier.BeeNest]: import("./blocks").BeeNestBlock;
  [BlockIdentifier.Campfire]: import("./blocks").CampfireBlock;
  [BlockIdentifier.SoulSoil]: GenericBlockState;
  [BlockIdentifier.Element8]: GenericBlockState;
  [BlockIdentifier.Element28]: GenericBlockState;
  [BlockIdentifier.DarkOakPressurePlate]: import("./blocks").DarkOakPressurePlateBlock;
  [BlockIdentifier.SoulSand]: GenericBlockState;
  [BlockIdentifier.CobbledDeepslateDoubleSlab]: import("./blocks").CobbledDeepslateDoubleSlabBlock;
  [BlockIdentifier.SpruceHangingSign]: import("./blocks").SpruceHangingSignBlock;
  [BlockIdentifier.ReinforcedDeepslate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.EndRod]: import("./blocks").EndRodBlock;
  [BlockIdentifier.FletchingTable]: GenericBlockState;
  [BlockIdentifier.CherryLeaves]: import("./blocks").CherryLeavesBlock;
  [BlockIdentifier.BlackGlazedTerracotta]: import("./blocks").BlackGlazedTerracottaBlock;
  [BlockIdentifier.StrippedAcaciaLog]: import("./blocks").StrippedAcaciaLogBlock;
  [BlockIdentifier.SnifferEgg]: import("./blocks").SnifferEggBlock;
  [BlockIdentifier.WarpedFence]: GenericBlockState;
  [BlockIdentifier.CaveVinesBodyWithBerries]: import("./blocks").CaveVinesBodyWithBerriesBlock;
  [BlockIdentifier.CherryStandingSign]: import("./blocks").CherryStandingSignBlock;
  [BlockIdentifier.MangroveHangingSign]: import("./blocks").MangroveHangingSignBlock;
  [BlockIdentifier.WaxedExposedCopperTrapdoor]: import("./blocks").WaxedExposedCopperTrapdoorBlock;
  [BlockIdentifier.MossyStoneBrickStairs]: import("./blocks").MossyStoneBrickStairsBlock;
  [BlockIdentifier.CrimsonStem]: import("./blocks").CrimsonStemBlock;
  [BlockIdentifier.ColoredTorchRg]: import("./blocks").ColoredTorchRgBlock;
  [BlockIdentifier.TuffBrickDoubleSlab]: import("./blocks").TuffBrickDoubleSlabBlock;
  [BlockIdentifier.Vault]: import("./blocks").VaultBlock;
  [BlockIdentifier.AzaleaLeavesFlowered]: import("./blocks").AzaleaLeavesFloweredBlock;
  [BlockIdentifier.Element18]: GenericBlockState;
  [BlockIdentifier.CrimsonSlab]: import("./blocks").CrimsonSlabBlock;
  [BlockIdentifier.WarpedHyphae]: import("./blocks").WarpedHyphaeBlock;
  [BlockIdentifier.OxeyeDaisy]: import("./blocks").OxeyeDaisyBlock;
  [BlockIdentifier.BambooButton]: import("./blocks").BambooButtonBlock;
  [BlockIdentifier.WarpedWartBlock]: GenericBlockState;
  [BlockIdentifier.TuffStairs]: import("./blocks").TuffStairsBlock;
  [BlockIdentifier.YellowCarpet]: GenericBlockState;
  [BlockIdentifier.BlackStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WaxedOxidizedCopperDoor]: import("./blocks").WaxedOxidizedCopperDoorBlock;
  [BlockIdentifier.GrassBlock]: GenericBlockState;
  [BlockIdentifier.TripwireHook]: import("./blocks").TripwireHookBlock;
  [BlockIdentifier.HardBlackStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.StrippedBirchLog]: import("./blocks").StrippedBirchLogBlock;
  [BlockIdentifier.RedTulip]: import("./blocks").RedTulipBlock;
  [BlockIdentifier.CutSandstone]: import("./blocks").CutSandstoneBlock;
  [BlockIdentifier.LimeWool]: GenericBlockState;
  [BlockIdentifier.BlueCandleCake]: import("./blocks").BlueCandleCakeBlock;
  [BlockIdentifier.LargeFern]: import("./blocks").LargeFernBlock;
  [BlockIdentifier.SweetBerryBush]: import("./blocks").SweetBerryBushBlock;
  [BlockIdentifier.PolishedBlackstoneSlab]: import("./blocks").PolishedBlackstoneSlabBlock;
  [BlockIdentifier.BlackShulkerBox]: GenericBlockState;
  [BlockIdentifier.JungleSapling]: import("./blocks").JungleSaplingBlock;
  [BlockIdentifier.BlueConcrete]: GenericBlockState;
  [BlockIdentifier.JungleStandingSign]: import("./blocks").JungleStandingSignBlock;
  [BlockIdentifier.Web]: GenericBlockState;
  [BlockIdentifier.WeatheredCutCopperSlab]: import("./blocks").WeatheredCutCopperSlabBlock;
  [BlockIdentifier.Cocoa]: import("./blocks").CocoaBlock;
  [BlockIdentifier.DarkOakLeaves]: import("./blocks").DarkOakLeavesBlock;
  [BlockIdentifier.OrangeTerracotta]: GenericBlockState;
  [BlockIdentifier.Fire]: import("./blocks").FireBlock;
  [BlockIdentifier.PurpurDoubleSlab]: import("./blocks").PurpurDoubleSlabBlock;
  [BlockIdentifier.ExposedChiseledCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.InfestedStone]: import("./blocks").InfestedStoneBlock;
  [BlockIdentifier.EndPortalFrame]: import("./blocks").EndPortalFrameBlock;
  [BlockIdentifier.Prismarine]: import("./blocks").PrismarineBlock;
  [BlockIdentifier.MagentaCandleCake]: import("./blocks").MagentaCandleCakeBlock;
  [BlockIdentifier.DeepslateGoldOre]: GenericBlockState;
  [BlockIdentifier.HardOrangeStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Glass]: GenericBlockState;
  [BlockIdentifier.MossBlock]: GenericBlockState;
  [BlockIdentifier.NetherBrickDoubleSlab]: import("./blocks").NetherBrickDoubleSlabBlock;
  [BlockIdentifier.ExposedCutCopper]: GenericBlockState;
  [BlockIdentifier.PrismarineBrickDoubleSlab]: import("./blocks").PrismarineBrickDoubleSlabBlock;
  [BlockIdentifier.Bookshelf]: GenericBlockState;
  [BlockIdentifier.WaxedWeatheredCutCopperStairs]: import("./blocks").WaxedWeatheredCutCopperStairsBlock;
  [BlockIdentifier.MangroveRoots]: GenericBlockState;
  [BlockIdentifier.AcaciaStairs]: import("./blocks").AcaciaStairsBlock;
  [BlockIdentifier.PolishedAndesiteStairs]: import("./blocks").PolishedAndesiteStairsBlock;
  [BlockIdentifier.CherrySlab]: import("./blocks").CherrySlabBlock;
  [BlockIdentifier.SmoothRedSandstoneDoubleSlab]: import("./blocks").SmoothRedSandstoneDoubleSlabBlock;
  [BlockIdentifier.LitBlastFurnace]: import("./blocks").LitBlastFurnaceBlock;
  [BlockIdentifier.Element11]: GenericBlockState;
  [BlockIdentifier.Sculk]: GenericBlockState;
  [BlockIdentifier.TuffBrickStairs]: import("./blocks").TuffBrickStairsBlock;
  [BlockIdentifier.ChemistryTable]: import("./blocks").ChemistryTableBlock;
  [BlockIdentifier.DeadFireCoral]: import("./blocks").DeadFireCoralBlock;
  [BlockIdentifier.StoneBrickSlab]: import("./blocks").StoneBrickSlabBlock;
  [BlockIdentifier.StrippedSpruceLog]: import("./blocks").StrippedSpruceLogBlock;
  [BlockIdentifier.WaxedOxidizedCopperBulb]: import("./blocks").WaxedOxidizedCopperBulbBlock;
  [BlockIdentifier.DeepslateBrickStairs]: import("./blocks").DeepslateBrickStairsBlock;
  [BlockIdentifier.WarpedNylium]: GenericBlockState;
  [BlockIdentifier.DeepslateEmeraldOre]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.StrippedCrimsonStem]: import("./blocks").StrippedCrimsonStemBlock;
  [BlockIdentifier.AcaciaSapling]: import("./blocks").AcaciaSaplingBlock;
  [BlockIdentifier.StonecutterBlock]: import("./blocks").StonecutterBlockBlock;
  [BlockIdentifier.AndesiteSlab]: import("./blocks").AndesiteSlabBlock;
  [BlockIdentifier.CyanShulkerBox]: GenericBlockState;
  [BlockIdentifier.UnpoweredComparator]: import("./blocks").UnpoweredComparatorBlock;
  [BlockIdentifier.LimeCandle]: import("./blocks").LimeCandleBlock;
  [BlockIdentifier.Target]: GenericBlockState;
  [BlockIdentifier.WoodenButton]: import("./blocks").WoodenButtonBlock;
  [BlockIdentifier.MangroveDoor]: import("./blocks").MangroveDoorBlock;
  [BlockIdentifier.EndStoneBrickDoubleSlab]: import("./blocks").EndStoneBrickDoubleSlabBlock;
  [BlockIdentifier.WeatheredCopperDoor]: import("./blocks").WeatheredCopperDoorBlock;
  [BlockIdentifier.PearlescentFroglight]: import("./blocks").PearlescentFroglightBlock;
  [BlockIdentifier.TallGrass]: import("./blocks").TallGrassBlock;
  [BlockIdentifier.LightBlock15]: import("./blocks").LightBlock15Block;
  [BlockIdentifier.Element64]: GenericBlockState;
  [BlockIdentifier.NetherSprouts]: GenericBlockState;
  [BlockIdentifier.Element92]: GenericBlockState;
  [BlockIdentifier.CyanStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DeadHornCoralBlock]: import("./blocks").DeadHornCoralBlockBlock;
  [BlockIdentifier.Element12]: GenericBlockState;
  [BlockIdentifier.DeadHornCoralFan]: import("./blocks").DeadHornCoralFanBlock;
  [BlockIdentifier.Furnace]: import("./blocks").FurnaceBlock;
  [BlockIdentifier.WarpedSlab]: import("./blocks").WarpedSlabBlock;
  [BlockIdentifier.Netherrack]: GenericBlockState;
  [BlockIdentifier.WarpedStem]: import("./blocks").WarpedStemBlock;
  [BlockIdentifier.Chain]: import("./blocks").ChainBlock;
  [BlockIdentifier.HornCoralFan]: import("./blocks").HornCoralFanBlock;
  [BlockIdentifier.GreenShulkerBox]: GenericBlockState;
  [BlockIdentifier.BrickStairs]: import("./blocks").BrickStairsBlock;
  [BlockIdentifier.PurpleCarpet]: GenericBlockState;
  [BlockIdentifier.FireCoralFan]: import("./blocks").FireCoralFanBlock;
  [BlockIdentifier.Element69]: GenericBlockState;
  [BlockIdentifier.SpruceTrapdoor]: import("./blocks").SpruceTrapdoorBlock;
  [BlockIdentifier.PurpleGlazedTerracotta]: import("./blocks").PurpleGlazedTerracottaBlock;
  [BlockIdentifier.ChainCommandBlock]: import("./blocks").ChainCommandBlockBlock;
  [BlockIdentifier.SpruceFenceGate]: import("./blocks").SpruceFenceGateBlock;
  [BlockIdentifier.RedNetherBrickStairs]: import("./blocks").RedNetherBrickStairsBlock;
  [BlockIdentifier.GreenGlazedTerracotta]: import("./blocks").GreenGlazedTerracottaBlock;
  [BlockIdentifier.DeepslateRedstoneOre]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DeadBrainCoralBlock]: import("./blocks").DeadBrainCoralBlockBlock;
  [BlockIdentifier.MangroveFence]: GenericBlockState;
  [BlockIdentifier.BirchTrapdoor]: import("./blocks").BirchTrapdoorBlock;
  [BlockIdentifier.TuffBricks]: GenericBlockState;
  [BlockIdentifier.Mud]: GenericBlockState;
  [BlockIdentifier.Ice]: GenericBlockState;
  [BlockIdentifier.Air]: GenericBlockState;
  [BlockIdentifier.Bed]: import("./blocks").BedBlock;
  [BlockIdentifier.LightBlueWool]: GenericBlockState;
  [BlockIdentifier.BlackConcrete]: GenericBlockState;
  [BlockIdentifier.Tnt]: import("./blocks").TntBlock;
  [BlockIdentifier.DeadTubeCoralFan]: import("./blocks").DeadTubeCoralFanBlock;
  [BlockIdentifier.PolishedDioriteStairs]: import("./blocks").PolishedDioriteStairsBlock;
  [BlockIdentifier.Element83]: GenericBlockState;
  [BlockIdentifier.OrangeConcrete]: GenericBlockState;
  [BlockIdentifier.Netherreactor]: GenericBlockState;
  [BlockIdentifier.LimeCarpet]: GenericBlockState;
  [BlockIdentifier.DeadFireCoralFan]: import("./blocks").DeadFireCoralFanBlock;
  [BlockIdentifier.DecoratedPot]: import("./blocks").DecoratedPotBlock;
  [BlockIdentifier.GraniteDoubleSlab]: import("./blocks").GraniteDoubleSlabBlock;
  [BlockIdentifier.EnchantingTable]: GenericBlockState;
  [BlockIdentifier.BubbleCoralWallFan]: import("./blocks").BubbleCoralWallFanBlock;
  [BlockIdentifier.OrangeTulip]: import("./blocks").OrangeTulipBlock;
  [BlockIdentifier.Azalea]: GenericBlockState;
  [BlockIdentifier.Bell]: import("./blocks").BellBlock;
  [BlockIdentifier.MudBricks]: GenericBlockState;
  [BlockIdentifier.BirchWallSign]: import("./blocks").BirchWallSignBlock;
  [BlockIdentifier.BambooWallSign]: import("./blocks").BambooWallSignBlock;
  [BlockIdentifier.AcaciaWood]: import("./blocks").AcaciaWoodBlock;
  [BlockIdentifier.Hopper]: import("./blocks").HopperBlock;
  [BlockIdentifier.HardRedStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.PrismarineBricks]: import("./blocks").PrismarineBricksBlock;
  [BlockIdentifier.Lectern]: import("./blocks").LecternBlock;
  [BlockIdentifier.AcaciaButton]: import("./blocks").AcaciaButtonBlock;
  [BlockIdentifier.StandingBanner]: import("./blocks").StandingBannerBlock;
  [BlockIdentifier.SeaLantern]: GenericBlockState;
  [BlockIdentifier.WaxedOxidizedDoubleCutCopperSlab]: import("./blocks").WaxedOxidizedDoubleCutCopperSlabBlock;
  [BlockIdentifier.LightBlueShulkerBox]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.MangrovePropagule]: import("./blocks").MangrovePropaguleBlock;
  [BlockIdentifier.PolishedDioriteDoubleSlab]: import("./blocks").PolishedDioriteDoubleSlabBlock;
  [BlockIdentifier.MossyCobblestoneDoubleSlab]: import("./blocks").MossyCobblestoneDoubleSlabBlock;
  [BlockIdentifier.BirchStairs]: import("./blocks").BirchStairsBlock;
  [BlockIdentifier.SpruceSlab]: import("./blocks").SpruceSlabBlock;
  [BlockIdentifier.BlackstoneStairs]: import("./blocks").BlackstoneStairsBlock;
  [BlockIdentifier.BlueIce]: GenericBlockState;
  [BlockIdentifier.HardRedStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Lantern]: import("./blocks").LanternBlock;
  [BlockIdentifier.DarkOakFence]: GenericBlockState;
  [BlockIdentifier.BirchDoor]: import("./blocks").BirchDoorBlock;
  [BlockIdentifier.DeepslateLapisOre]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CrimsonHangingSign]: import("./blocks").CrimsonHangingSignBlock;
  [BlockIdentifier.DeepslateCoalOre]: GenericBlockState;
  [BlockIdentifier.WeatheredCutCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BambooStandingSign]: import("./blocks").BambooStandingSignBlock;
  [BlockIdentifier.StrippedMangroveLog]: import("./blocks").StrippedMangroveLogBlock;
  [BlockIdentifier.PolishedTuff]: GenericBlockState;
  [BlockIdentifier.MagentaStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WeatheredCopperBulb]: import("./blocks").WeatheredCopperBulbBlock;
  [BlockIdentifier.HardWhiteStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.HardCyanStainedGlassPane]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.ChiseledNetherBricks]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WarpedButton]: import("./blocks").WarpedButtonBlock;
  [BlockIdentifier.RedConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DeadBubbleCoral]: import("./blocks").DeadBubbleCoralBlock;
  [BlockIdentifier.CherrySapling]: import("./blocks").CherrySaplingBlock;
  [BlockIdentifier.CherryLog]: import("./blocks").CherryLogBlock;
  [BlockIdentifier.PolishedTuffStairs]: import("./blocks").PolishedTuffStairsBlock;
  [BlockIdentifier.DragonEgg]: GenericBlockState;
  [BlockIdentifier.NetherBrick]: GenericBlockState;
  [BlockIdentifier.DeepslateIronOre]: GenericBlockState;
  [BlockIdentifier.Element3]: GenericBlockState;
  [BlockIdentifier.Element2]: GenericBlockState;
  [BlockIdentifier.Element5]: GenericBlockState;
  [BlockIdentifier.Element4]: GenericBlockState;
  [BlockIdentifier.Element7]: GenericBlockState;
  [BlockIdentifier.Element9]: GenericBlockState;
  [BlockIdentifier.Camera]: GenericBlockState;
  [BlockIdentifier.WaxedCutCopper]: GenericBlockState;
  [BlockIdentifier.Element47]: GenericBlockState;
  [BlockIdentifier.CobbledDeepslateSlab]: import("./blocks").CobbledDeepslateSlabBlock;
  [BlockIdentifier.Lilac]: import("./blocks").LilacBlock;
  [BlockIdentifier.CrimsonStandingSign]: import("./blocks").CrimsonStandingSignBlock;
  [BlockIdentifier.EmeraldOre]: GenericBlockState;
  [BlockIdentifier.BrownMushroomBlock]: import("./blocks").BrownMushroomBlockBlock;
  [BlockIdentifier.PetrifiedOakSlab]: import("./blocks").PetrifiedOakSlabBlock;
  [BlockIdentifier.CarvedPumpkin]: import("./blocks").CarvedPumpkinBlock;
  [BlockIdentifier.Dropper]: import("./blocks").DropperBlock;
  [BlockIdentifier.Candle]: import("./blocks").CandleBlock;
  [BlockIdentifier.PolishedAndesiteSlab]: import("./blocks").PolishedAndesiteSlabBlock;
  [BlockIdentifier.AcaciaSlab]: import("./blocks").AcaciaSlabBlock;
  [BlockIdentifier.CobbledDeepslateWall]: import("./blocks").CobbledDeepslateWallBlock;
  [BlockIdentifier.PointedDripstone]: import("./blocks").PointedDripstoneBlock;
  [BlockIdentifier.CutRedSandstoneSlab]: import("./blocks").CutRedSandstoneSlabBlock;
  [BlockIdentifier.ChiseledTuffBricks]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.ChemicalHeat]: GenericBlockState;
  [BlockIdentifier.TripWire]: import("./blocks").TripWireBlock;
  [BlockIdentifier.CaveVinesHeadWithBerries]: import("./blocks").CaveVinesHeadWithBerriesBlock;
  [BlockIdentifier.ChiseledRedSandstone]: import("./blocks").ChiseledRedSandstoneBlock;
  [BlockIdentifier.BrickSlab]: import("./blocks").BrickSlabBlock;
  [BlockIdentifier.BrewingStand]: import("./blocks").BrewingStandBlock;
  [BlockIdentifier.BambooSapling]: import("./blocks").BambooSaplingBlock;
  [BlockIdentifier.SmoothQuartzSlab]: import("./blocks").SmoothQuartzSlabBlock;
  [BlockIdentifier.WhiteCandleCake]: import("./blocks").WhiteCandleCakeBlock;
  [BlockIdentifier.EndPortal]: GenericBlockState;
  [BlockIdentifier.JungleDoubleSlab]: import("./blocks").JungleDoubleSlabBlock;
  [BlockIdentifier.SpruceWood]: import("./blocks").SpruceWoodBlock;
  [BlockIdentifier.Blackstone]: GenericBlockState;
  [BlockIdentifier.LitDeepslateRedstoneOre]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.Element10]: GenericBlockState;
  [BlockIdentifier.Element14]: GenericBlockState;
  [BlockIdentifier.Element15]: GenericBlockState;
  [BlockIdentifier.Element36]: GenericBlockState;
  [BlockIdentifier.Element37]: GenericBlockState;
  [BlockIdentifier.Element34]: GenericBlockState;
  [BlockIdentifier.Element35]: GenericBlockState;
  [BlockIdentifier.Element32]: GenericBlockState;
  [BlockIdentifier.Element33]: GenericBlockState;
  [BlockIdentifier.Element31]: GenericBlockState;
  [BlockIdentifier.Element38]: GenericBlockState;
  [BlockIdentifier.Element29]: GenericBlockState;
  [BlockIdentifier.Element21]: GenericBlockState;
  [BlockIdentifier.Element20]: GenericBlockState;
  [BlockIdentifier.Element23]: GenericBlockState;
  [BlockIdentifier.Element22]: GenericBlockState;
  [BlockIdentifier.Element25]: GenericBlockState;
  [BlockIdentifier.Element24]: GenericBlockState;
  [BlockIdentifier.Element27]: GenericBlockState;
  [BlockIdentifier.Element26]: GenericBlockState;
  [BlockIdentifier.Element59]: GenericBlockState;
  [BlockIdentifier.Element54]: GenericBlockState;
  [BlockIdentifier.Element55]: GenericBlockState;
  [BlockIdentifier.Element56]: GenericBlockState;
  [BlockIdentifier.Element57]: GenericBlockState;
  [BlockIdentifier.Element53]: GenericBlockState;
  [BlockIdentifier.Element49]: GenericBlockState;
  [BlockIdentifier.Element48]: GenericBlockState;
  [BlockIdentifier.Element45]: GenericBlockState;
  [BlockIdentifier.Element43]: GenericBlockState;
  [BlockIdentifier.Element42]: GenericBlockState;
  [BlockIdentifier.Element41]: GenericBlockState;
  [BlockIdentifier.Element40]: GenericBlockState;
  [BlockIdentifier.Element72]: GenericBlockState;
  [BlockIdentifier.Element70]: GenericBlockState;
  [BlockIdentifier.Element71]: GenericBlockState;
  [BlockIdentifier.Element76]: GenericBlockState;
  [BlockIdentifier.Element75]: GenericBlockState;
  [BlockIdentifier.Element78]: GenericBlockState;
  [BlockIdentifier.Element79]: GenericBlockState;
  [BlockIdentifier.Element65]: GenericBlockState;
  [BlockIdentifier.Element67]: GenericBlockState;
  [BlockIdentifier.PolishedDeepslateWall]: import("./blocks").PolishedDeepslateWallBlock;
  [BlockIdentifier.Element66]: GenericBlockState;
  [BlockIdentifier.Element61]: GenericBlockState;
  [BlockIdentifier.Element60]: GenericBlockState;
  [BlockIdentifier.Element63]: GenericBlockState;
  [BlockIdentifier.Element98]: GenericBlockState;
  [BlockIdentifier.Element90]: GenericBlockState;
  [BlockIdentifier.Element91]: GenericBlockState;
  [BlockIdentifier.Element94]: GenericBlockState;
  [BlockIdentifier.Element96]: GenericBlockState;
  [BlockIdentifier.Element88]: GenericBlockState;
  [BlockIdentifier.Element82]: GenericBlockState;
  [BlockIdentifier.Element81]: GenericBlockState;
  [BlockIdentifier.Element80]: GenericBlockState;
  [BlockIdentifier.Element87]: GenericBlockState;
  [BlockIdentifier.Element86]: GenericBlockState;
  [BlockIdentifier.Element84]: GenericBlockState;
  [BlockIdentifier.LitSmoker]: import("./blocks").LitSmokerBlock;
  [BlockIdentifier.SmoothQuartzStairs]: import("./blocks").SmoothQuartzStairsBlock;
  [BlockIdentifier.LightGrayCarpet]: GenericBlockState;
  [BlockIdentifier.PurpurBlock]: import("./blocks").PurpurBlockBlock;
  [BlockIdentifier.CherryWallSign]: import("./blocks").CherryWallSignBlock;
  [BlockIdentifier.CyanCandle]: import("./blocks").CyanCandleBlock;
  [BlockIdentifier.RepeatingCommandBlock]: import("./blocks").RepeatingCommandBlockBlock;
  [BlockIdentifier.CrimsonFungus]: GenericBlockState;
  [BlockIdentifier.CherryPlanks]: GenericBlockState;
  [BlockIdentifier.PolishedDeepslate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.TuffDoubleSlab]: import("./blocks").TuffDoubleSlabBlock;
  [BlockIdentifier.PurpurStairs]: import("./blocks").PurpurStairsBlock;
  [BlockIdentifier.TubeCoral]: import("./blocks").TubeCoralBlock;
  [BlockIdentifier.WaxedCopperDoor]: import("./blocks").WaxedCopperDoorBlock;
  [BlockIdentifier.Portal]: import("./blocks").PortalBlock;
  [BlockIdentifier.Peony]: import("./blocks").PeonyBlock;
  [BlockIdentifier.Crafter]: import("./blocks").CrafterBlock;
  [BlockIdentifier.SprucePlanks]: GenericBlockState;
  [BlockIdentifier.AmethystCluster]: import("./blocks").AmethystClusterBlock;
  [BlockIdentifier.WaxedChiseledCopper]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.WaxedCutCopperSlab]: import("./blocks").WaxedCutCopperSlabBlock;
  [BlockIdentifier.DriedKelpBlock]: GenericBlockState;
  [BlockIdentifier.HardLightGrayStainedGlass]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.CrimsonFence]: GenericBlockState;
  [BlockIdentifier.ChiseledTuff]: GenericBlockState;
  [BlockIdentifier.LimeConcretePowder]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.BirchFence]: GenericBlockState;
  [BlockIdentifier.TurtleEgg]: import("./blocks").TurtleEggBlock;
  [BlockIdentifier.BrownTerracotta]: GenericBlockState;
  [BlockIdentifier.CobblestoneDoubleSlab]: import("./blocks").CobblestoneDoubleSlabBlock;
  [BlockIdentifier.DeepslateDiamondOre]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.LightGrayWool]: GenericBlockState;
  [BlockIdentifier.SoulCampfire]: import("./blocks").SoulCampfireBlock;
  [BlockIdentifier.WoodenPressurePlate]: import("./blocks").WoodenPressurePlateBlock;
  [BlockIdentifier.WaxedOxidizedCopperGrate]: Record<
    string,
    string | number | boolean
  >;
  [BlockIdentifier.DamagedAnvil]: import("./blocks").DamagedAnvilBlock;
  [BlockIdentifier.WhiteConcrete]: GenericBlockState;
  [BlockIdentifier.AcaciaFence]: GenericBlockState;
  [BlockIdentifier.GrassPath]: GenericBlockState;
  [BlockIdentifier.OrangeCandleCake]: import("./blocks").OrangeCandleCakeBlock;
  [BlockIdentifier.WeatheredCopper]: GenericBlockState;
  [BlockIdentifier.LimeTerracotta]: GenericBlockState;
  [BlockIdentifier.CherryFenceGate]: import("./blocks").CherryFenceGateBlock;
  [BlockIdentifier.GrayGlazedTerracotta]: import("./blocks").GrayGlazedTerracottaBlock;
  [BlockIdentifier.Lodestone]: GenericBlockState;
  [BlockIdentifier.BambooMosaic]: GenericBlockState;
  [BlockIdentifier.PurpleWool]: GenericBlockState;
  [BlockIdentifier.IronBlock]: GenericBlockState;
  [BlockIdentifier.CartographyTable]: GenericBlockState;
  [BlockIdentifier.Dandelion]: GenericBlockState;
}
