/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'binarystream.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.android-arm64.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'binarystream.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.android-arm-eabi.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'binarystream.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'binarystream.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'binarystream.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'binarystream.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./binarystream.darwin-universal.node')
      } else {
        nativeBinding = require('@serenityjs/binarystream-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'binarystream.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.darwin-x64.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'binarystream.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.darwin-arm64.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'binarystream.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./binarystream.freebsd-x64.node')
      } else {
        nativeBinding = require('@serenityjs/binarystream-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'binarystream.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./binarystream.linux-x64-musl.node')
            } else {
              nativeBinding = require('@serenityjs/binarystream-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'binarystream.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./binarystream.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@serenityjs/binarystream-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'binarystream.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./binarystream.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@serenityjs/binarystream-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'binarystream.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./binarystream.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@serenityjs/binarystream-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        localFileExisted = existsSync(
          join(__dirname, 'binarystream.linux-arm-gnueabihf.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.linux-arm-gnueabihf.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-linux-arm-gnueabihf')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'binarystream.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./binarystream.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@serenityjs/binarystream-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'binarystream.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./binarystream.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@serenityjs/binarystream-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'binarystream.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./binarystream.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@serenityjs/binarystream-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { BinaryStream, Endianness, Bool, Uint8, Uint16, Uint24, Uint32, Uint64, UShort, ULong, Byte, Int8, Int16, Int24, Int32, Int64, Short, Long, Float32, Float64, VarInt, ZigZag, VarLong, ZigZong, String16, String32, VarString, Uuid } = nativeBinding

module.exports.BinaryStream = BinaryStream
module.exports.Endianness = Endianness
module.exports.Bool = Bool
module.exports.Uint8 = Uint8
module.exports.Uint16 = Uint16
module.exports.Uint24 = Uint24
module.exports.Uint32 = Uint32
module.exports.Uint64 = Uint64
module.exports.UShort = UShort
module.exports.ULong = ULong
module.exports.Byte = Byte
module.exports.Int8 = Int8
module.exports.Int16 = Int16
module.exports.Int24 = Int24
module.exports.Int32 = Int32
module.exports.Int64 = Int64
module.exports.Short = Short
module.exports.Long = Long
module.exports.Float32 = Float32
module.exports.Float64 = Float64
module.exports.VarInt = VarInt
module.exports.ZigZag = ZigZag
module.exports.VarLong = VarLong
module.exports.ZigZong = ZigZong
module.exports.String16 = String16
module.exports.String32 = String32
module.exports.VarString = VarString
module.exports.Uuid = Uuid
