import {
	PlayerBuildComponent,
	PlayerMineComponent,
	PlayerDoorsAndSwitchesComponent,
	PlayerOpenContainersComponent,
	PlayerAttackPlayersComponent,
	PlayerAttackMobsComponent,
	PlayerOperatorCommandsComponent,
	PlayerInvulnerableComponent,
	PlayerFlyingComponent,
	PlayerMayFlyComponent,
	PlayerInstantBuildComponent,
	PlayerLightningComponent,
	PlayerWalkSpeedComponent,
	PlayerFlySpeedComponent,
	PlayerTeleportComponent,
	PlayerMutedComponent,
	PlayerWorldBuilderComponent,
	PlayerNoClipComponent,
	PlayerPrivilegedBuilderComponent,
	PlayerCountComponent,
	PlayerHungerComponent,
	PlayerExperienceComponent,
	PlayerLevelComponent,
} from '../../../player/components/index.js';
import type { EntityComponent } from '../Component.js';
import {
	EntityCursorComponent,
	EntityInventoryComponent,
	EntityMovementComponent,
	EntityHealthComponent,
} from '../index.js';

const PLAYER_COMPONENTS: (typeof EntityComponent)[] = [
	EntityInventoryComponent,
	EntityCursorComponent,
	EntityMovementComponent,
	EntityHealthComponent,
	PlayerHungerComponent,
	PlayerLevelComponent,
	PlayerExperienceComponent,
	PlayerBuildComponent,
	PlayerMineComponent,
	PlayerDoorsAndSwitchesComponent,
	PlayerOpenContainersComponent,
	PlayerAttackPlayersComponent,
	PlayerAttackMobsComponent,
	PlayerOperatorCommandsComponent,
	PlayerTeleportComponent,
	PlayerInvulnerableComponent,
	PlayerFlyingComponent,
	PlayerMayFlyComponent,
	PlayerInstantBuildComponent,
	PlayerLightningComponent,
	PlayerFlySpeedComponent,
	PlayerWalkSpeedComponent,
	PlayerMutedComponent,
	PlayerWorldBuilderComponent,
	PlayerNoClipComponent,
	PlayerPrivilegedBuilderComponent,
	PlayerCountComponent,
];

export { PLAYER_COMPONENTS };
