enum MapDecorationType {
  MarkerWhite,
  MarkerGreen,
  MarkerRed,
  MarkerBlue,
  XWhite,
  TriangleRed,
  SquareWhite,
  MarkerSign,
  MarkerPink,
  MarkerOrange,
  MarkerYellow,
  MarkerTeal,
  TriangleGreen,
  SmallSquareWhite,
  Mansion,
  Monument,
  NoDraw,
  VillageDesert,
  VillagePlains,
  VillageSavanna,
  VillageSnowy,
  VillageTaiga,
  JungleTemple,
  WitchHut,
  TrialChambers,
  Count,
  Player = MarkerWhite,
  PlayerOffMap = SquareWhite,
  PlayerOffLimits = SmallSquareWhite,
  PlayerHidden = NoDraw,
  ItemFrame = MarkerGreen
}

export { MapDecorationType };
