enum GameRule {
  CommandBlockOutput = "commandBlockOutput",
  DoDaylightCycle = "doDayLightCycle",
  DoEntityDrops = "doEntityDrops",
  DoFireTick = "doFireTick",
  RecipesUnlock = "recipesUnlock",
  DoLimitedCrafting = "doLimitedCrafting",
  DoMobLoot = "doMobLoot",
  DoMobSpawning = "doMobSpawning",
  DoTileDrops = "doTileDrops",
  DoWeatherCycle = "doWeatherCycle",
  DrowningDamage = "drowningDamage",
  FallDamage = "fallDamage",
  FireDamage = "fireDamage",
  KeepInventory = "keepInventory",
  MobGriefing = "mobGriefing",
  PvP = "pvp",
  ShowCoordinates = "showCoordinates",
  ShowDaysPlayed = "showDaysPlayed",
  NaturalRegeneration = "naturalRegeneration",
  TNTExplodes = "tntExplodes",
  SendCommandFeedback = "sendCommandFeedback",
  DoInsomnia = "doInsomnia",
  CommandBlocksEnabled = "commandBlocksEnabled",
  DoImmediateRespawn = "doImmediateRespawn",
  ShowDeathMessages = "showDeathMessages",
  ShowTags = "showTags",
  FreezeDamage = "freezeDamage",
  RespawnBlocksExplode = "respawnBlocksExplode",
  ShowBorderEffect = "showBorderEffect",
  ShowRecipeMessages = "showRecipeMessages",
  ProjectilesCanBreakBlocks = "projectilesCanBreakBlocks",
  TNTExplosionDropDecay = "tntExplosionDropDecay",
  RandomTickSpeed = "randomTickSpeed",
  LocatorBar = "locatorBar"
}

export { GameRule };
