enum TelemetryEventType {
  AchievementAwarded = 0,
  EntityInteract = 1,
  PortalBuilt = 2,
  PortalUsed = 3,
  MobKilled = 4,
  CauldronUsed = 5,
  PlayerDeath = 6,
  BossKilled = 7,
  AgentCommand = 8,
  AgentCreated = 9,
  BannerPatternRemoved = 10,
  CommandExecuted = 11,
  FishBucketed = 12,
  MobBorn = 13,
  PetDied = 14,
  CauldronBlockUsed = 15,
  ComposterBlockUsed = 16,
  BellBlockUsed = 17,
  ActorDefinition = 18,
  RaidUpdate = 19,
  PlayerMovementAnomaly = 20,
  PlayerMovementCorrected = 21,
  HoneyHarvested = 22,
  TargetBlockHit = 23,
  PiglinBarter = 24,
  WaxedOrUnwaxedCopper = 25,
  CodeBuilderRuntimeAction = 26,
  CodeBuilderScoreboard = 27,
  StriderRiddenInLavaInOverworld = 28,
  SneakCloseToSculkSensor = 29,
  CarefulRestoration = 30,
  ItemUsed = 31
}

export { TelemetryEventType };
