enum WindowsIds {
	DropContents = -100,
	Beacon = -24,
	TradingOutput = -23,
	TradingUseInputs = -22,
	TradingInput2 = -21,
	TradingInput1 = -20,
	EnchantOutput = -17,
	EnchantMaterial = -16,
	EnchantInput = -15,
	AnvilOutput = -13,
	AnvilResult = -12,
	AnvilMaterial = -11,
	ContainerInput = -10,
	CraftingUseIngredient = -5,
	CraftingResult = -4,
	CraftingRemoveIngredient = -3,
	CraftingAddIngredient = -2,
	None = -1,
	Inventory = 0,
	First = 1,
	Last = 100,
	Offhand = 119,
	Armor = 120,
	Creative = 121,
	Hotbar = 122,
	FixedInventory = 123,
	Ui = 124,
}

export { WindowsIds };
