// WARNING, DO NOT EDIT!
// This file is automatically generated on start up.

export interface PinkTulipBlock {
	flower_type?: import("./states").FlowerType;
}
export interface DetectorRailBlock {
	rail_data_bit?: boolean;
	rail_direction?: number;
}
export interface LightGrayCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface PolishedBasaltBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface BlueCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface DarkOakWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface TuffBrickWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface AcaciaWallSignBlock {
	facing_direction?: number;
}
export interface BambooPressurePlateBlock {
	redstone_signal?: number;
}
export interface BirchStandingSignBlock {
	ground_sign_direction?: number;
}
export interface WaxedCutCopperStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface CornflowerBlock {
	flower_type?: import("./states").FlowerType;
}
export interface OxidizedCutCopperStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface WarpedDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface PolishedGraniteStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface RedMushroomBlockBlock {
	huge_mushroom_bits?: number;
}
export interface DeadBubbleCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface BambooBlockBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface WoodenDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface PistonArmCollisionBlock {
	facing_direction?: number;
}
export interface RedSandstoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface DarkPrismarineStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface SculkShriekerBlock {
	active?: boolean;
	can_summon?: boolean;
}
export interface BambooMosaicStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface VineBlock {
	vine_direction_bits?: number;
}
export interface WhiteTulipBlock {
	flower_type?: import("./states").FlowerType;
}
export interface PolishedTuffSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
}
export interface CutCopperStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface ExposedCopperDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface BlackstoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface SpruceStandingSignBlock {
	ground_sign_direction?: number;
}
export interface FenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface DeepslateTileSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface MagentaCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface DeepslateTileDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface DarkOakButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface StoneBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface WaxedOxidizedCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface WarpedWallSignBlock {
	facing_direction?: number;
}
export interface LadderBlock {
	facing_direction?: number;
}
export interface ChiseledStoneBricksBlock {
	stone_brick_type?: import("./states").StoneBrickType;
}
export interface SprucePressurePlateBlock {
	redstone_signal?: number;
}
export interface DeadHornCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface CobblestoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface WaxedCopperTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface NetherBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface GraniteStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface OxidizedCopperBulbBlock {
	lit?: boolean;
	powered_bit?: boolean;
}
export interface CobbledDeepslateStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface StrippedAcaciaWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface JungleButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface DeadBubbleCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface PoweredRepeaterBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
	repeater_delay?: number;
}
export interface SpruceStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface LoomBlock {
	direction?: number;
}
export interface OxidizedDoubleCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface JungleDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface DarkoakWallSignBlock {
	facing_direction?: number;
}
export interface GrayCandleCakeBlock {
	lit?: boolean;
}
export interface ExposedCopperTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface SmoothSandstoneBlock {
	sand_stone_type?: import("./states").SandStoneType;
}
export interface PolishedBlackstoneButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface StrippedBirchWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface RedCandleCakeBlock {
	lit?: boolean;
}
export interface MossyStoneBricksBlock {
	stone_brick_type?: import("./states").StoneBrickType;
}
export interface CherryPressurePlateBlock {
	redstone_signal?: number;
}
export interface CherryHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface BlackCandleCakeBlock {
	lit?: boolean;
}
export interface CrimsonWallSignBlock {
	facing_direction?: number;
}
export interface PolishedBlackstoneBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface LightBlock1Block {
	block_light_level?: number;
}
export interface SmoothSandstoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface DarkOakDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface WheatBlock {
	growth?: number;
}
export interface GrindstoneBlock {
	attachment?: import("./states").Attachment;
	direction?: number;
}
export interface DarkOakSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface PolishedGraniteDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface AzureBluetBlock {
	flower_type?: import("./states").FlowerType;
}
export interface StoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface PolishedBlackstoneBrickWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface SnowLayerBlock {
	covered_bit?: boolean;
	height?: number;
}
export interface BrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface BlackCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface CactusBlock {
	age?: number;
}
export interface GlowFrameBlock {
	facing_direction?: number;
	item_frame_map_bit?: boolean;
	item_frame_photo_bit?: boolean;
}
export interface MudBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface BambooMosaicSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface DarkPrismarineSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface PrismarineBricksStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface DioriteSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface CrimsonHyphaeBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface StrippedDarkOakLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface JungleLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface BubbleCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface BambooSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface NetherWartBlock {
	age?: number;
}
export interface StrippedMangroveWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface CutRedSandstoneBlock {
	sand_stone_type?: import("./states").SandStoneType;
}
export interface SmoothRedSandstoneBlock {
	sand_stone_type?: import("./states").SandStoneType;
}
export interface LilyOfTheValleyBlock {
	flower_type?: import("./states").FlowerType;
}
export interface BlueOrchidBlock {
	flower_type?: import("./states").FlowerType;
}
export interface LimeGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface TrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface DeadBrainCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface AcaciaStandingSignBlock {
	ground_sign_direction?: number;
}
export interface SeagrassBlock {
	sea_grass_type?: import("./states").SeaGrassType;
}
export interface TubeCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface CherryStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface BarrelBlock {
	facing_direction?: number;
	open_bit?: boolean;
}
export interface BigDripleafBlock {
	big_dripleaf_head?: boolean;
	big_dripleaf_tilt?: import("./states").BigDripleafTilt;
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface QuartzSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface FireCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface WaxedExposedCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface DeadHornCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface InfestedMossyStoneBricksBlock {
	monster_egg_stone_type?: import("./states").MonsterEggStoneType;
}
export interface CakeBlock {
	bite_counter?: number;
}
export interface DarkOakDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface StrippedCrimsonHyphaeBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface DarkOakHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface DeepslateBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface StrippedOakWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface PurpurSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface PitcherCropBlock {
	growth?: number;
	upper_block_bit?: boolean;
}
export interface WarpedStandingSignBlock {
	ground_sign_direction?: number;
}
export interface EnderChestBlock {
	facing_direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface TuffSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
}
export interface RedstoneWireBlock {
	redstone_signal?: number;
}
export interface WarpedPressurePlateBlock {
	redstone_signal?: number;
}
export interface GreenCandleCakeBlock {
	lit?: boolean;
}
export interface ExposedCopperBulbBlock {
	lit?: boolean;
	powered_bit?: boolean;
}
export interface BambooMosaicDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface DarkPrismarineDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface OakStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface OakLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface SculkVeinBlock {
	multi_face_direction_bits?: number;
}
export interface ExposedDoubleCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface CandleCakeBlock {
	lit?: boolean;
}
export interface SmoothQuartzBlock {
	chisel_type?: import("./states").ChiselType;
	pillar_axis?: import("./states").PillarAxis;
}
export interface FernBlock {
	tall_grass_type?: import("./states").TallGrassType;
}
export interface LightBlueCandleCakeBlock {
	lit?: boolean;
}
export interface PoppyBlock {
	flower_type?: import("./states").FlowerType;
}
export interface CrimsonStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface StoneBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface GrayCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface PolishedDeepslateSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface BambooDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface MelonStemBlock {
	facing_direction?: number;
	growth?: number;
}
export interface StrippedOakLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface FlowerPotBlock {
	update_bit?: boolean;
}
export interface ChiseledBookshelfBlock {
	books_stored?: number;
	direction?: number;
}
export interface SpruceLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface PolishedDeepslateStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface ShortGrassBlock {
	tall_grass_type?: import("./states").TallGrassType;
}
export interface SmallAmethystBudBlock {
	facing_direction?: number;
	"minecraft:block_face"?: import("./states").MinecraftblockFace;
}
export interface ActivatorRailBlock {
	rail_data_bit?: boolean;
	rail_direction?: number;
}
export interface MangroveButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface IronTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface PotatoesBlock {
	growth?: number;
}
export interface LargeAmethystBudBlock {
	facing_direction?: number;
	"minecraft:block_face"?: import("./states").MinecraftblockFace;
}
export interface MuddyMangroveRootsBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface TrialSpawnerBlock {
	ominous?: boolean;
	trial_spawner_state?: number;
}
export interface StrippedJungleWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface DeadTubeCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface SoulTorchBlock {
	torch_facing_direction?: import("./states").TorchFacingDirection;
}
export interface MangroveLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface SandstoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface BirchWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface PolishedBlackstonePressurePlateBlock {
	redstone_signal?: number;
}
export interface MossyStoneBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface AlliumBlock {
	flower_type?: import("./states").FlowerType;
}
export interface WeatheredDoubleCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface LavaBlock {
	liquid_depth?: number;
}
export interface LightBlock14Block {
	block_light_level?: number;
}
export interface AcaciaFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface CyanCandleCakeBlock {
	lit?: boolean;
}
export interface OrangeCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface ColoredTorchBpBlock {
	color_bit?: boolean;
	torch_facing_direction?: import("./states").TorchFacingDirection;
}
export interface ScaffoldingBlock {
	stability?: number;
	stability_check?: boolean;
}
export interface PoweredComparatorBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
	output_lit_bit?: boolean;
	output_subtract_bit?: boolean;
}
export interface LightBlock8Block {
	block_light_level?: number;
}
export interface SpruceSaplingBlock {
	age_bit?: boolean;
	sapling_type?: import("./states").SaplingType;
}
export interface CutSandstoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface BlastFurnaceBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface CutSandstoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface DarkOakSaplingBlock {
	age_bit?: boolean;
	sapling_type?: import("./states").SaplingType;
}
export interface SandstoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface PinkPetalsBlock {
	direction?: number;
	growth?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface SoulFireBlock {
	age?: number;
}
export interface MangroveDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface GreenCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface SmoothQuartzDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface OxidizedCopperTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface BrainCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface ChestBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface DeadBubbleCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface BlackstoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface StrippedSpruceWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface CauldronBlock {
	cauldron_liquid?: import("./states").CauldronLiquid;
	fill_level?: number;
}
export interface DeepslateBrickWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface DarkoakStandingSignBlock {
	ground_sign_direction?: number;
}
export interface TubeCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface JungleWallSignBlock {
	facing_direction?: number;
}
export interface EndBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface PolishedBlackstoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface PolishedDeepslateDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface NetherBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface HeavyWeightedPressurePlateBlock {
	redstone_signal?: number;
}
export interface StoneButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface RedNetherBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface PitcherPlantBlock {
	upper_block_bit?: boolean;
}
export interface WaxedCopperBulbBlock {
	lit?: boolean;
	powered_bit?: boolean;
}
export interface AndesiteStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface SpongeBlock {
	sponge_type?: import("./states").SpongeType;
}
export interface BoneBlockBlock {
	deprecated?: number;
	pillar_axis?: import("./states").PillarAxis;
}
export interface NormalStoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface WarpedHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface DioriteDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface EndStoneBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface FrameBlock {
	facing_direction?: number;
	item_frame_map_bit?: boolean;
	item_frame_photo_bit?: boolean;
}
export interface SmokerBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface BirchHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface PolishedTuffWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface UnlitRedstoneTorchBlock {
	torch_facing_direction?: import("./states").TorchFacingDirection;
}
export interface StrippedJungleLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface PolishedGraniteSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface LightBlock9Block {
	block_light_level?: number;
}
export interface OxidizedCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface BeehiveBlock {
	direction?: number;
	honey_level?: number;
}
export interface LightBlock7Block {
	block_light_level?: number;
}
export interface CherryDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface LightBlock6Block {
	block_light_level?: number;
}
export interface LightBlock5Block {
	block_light_level?: number;
}
export interface WaxedOxidizedCutCopperStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface LightBlock4Block {
	block_light_level?: number;
}
export interface SmallDripleafBlockBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
	upper_block_bit?: boolean;
}
export interface LimeCandleCakeBlock {
	lit?: boolean;
}
export interface MangroveLeavesBlock {
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface LightBlock3Block {
	block_light_level?: number;
}
export interface AcaciaLeavesBlock {
	new_leaf_type?: import("./states").NewLeafType;
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface DispenserBlock {
	facing_direction?: number;
	triggered_bit?: boolean;
}
export interface LightBlock2Block {
	block_light_level?: number;
}
export interface LightBlock0Block {
	block_light_level?: number;
}
export interface AndesiteDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface UnpoweredRepeaterBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
	repeater_delay?: number;
}
export interface OakSaplingBlock {
	age_bit?: boolean;
	sapling_type?: import("./states").SaplingType;
}
export interface FireCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface BirchLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface PolishedBlackstoneBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface BubbleCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface CrimsonDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface KelpBlock {
	kelp_age?: number;
}
export interface UnderwaterTorchBlock {
	torch_facing_direction?: import("./states").TorchFacingDirection;
}
export interface RespawnAnchorBlock {
	respawn_anchor_charge?: number;
}
export interface DeadFireCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface SeaPickleBlock {
	cluster_count?: number;
	dead_bit?: boolean;
}
export interface RedSandstoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface RedSandBlock {
	sand_type?: import("./states").SandType;
}
export interface HayBlockBlock {
	deprecated?: number;
	pillar_axis?: import("./states").PillarAxis;
}
export interface SuspiciousGravelBlock {
	brushed_progress?: number;
	hanging?: boolean;
}
export interface JungleWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface PolishedTuffDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
}
export interface OxidizedCopperDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface ChiseledQuartzBlockBlock {
	chisel_type?: import("./states").ChiselType;
	pillar_axis?: import("./states").PillarAxis;
}
export interface InfestedCrackedStoneBricksBlock {
	monster_egg_stone_type?: import("./states").MonsterEggStoneType;
}
export interface DeepslateBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface OakLeavesBlock {
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface BrainCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface BambooStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface TorchBlock {
	torch_facing_direction?: import("./states").TorchFacingDirection;
}
export interface GlowLichenBlock {
	multi_face_direction_bits?: number;
}
export interface CopperTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface RedCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface MudBrickWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface CherryTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface LitPumpkinBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface YellowGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface PistonBlock {
	facing_direction?: number;
}
export interface WaterBlock {
	liquid_depth?: number;
}
export interface WeatheredCopperTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface SpruceButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface WallBannerBlock {
	facing_direction?: number;
}
export interface DeadFireCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface WaxedWeatheredCopperBulbBlock {
	lit?: boolean;
	powered_bit?: boolean;
}
export interface VerdantFroglightBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface MossyCobblestoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface MagentaGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface QuartzDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface MangroveSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface WallSignBlock {
	facing_direction?: number;
}
export interface InfestedDeepslateBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface OrangeGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface BirchSaplingBlock {
	age_bit?: boolean;
	sapling_type?: import("./states").SaplingType;
}
export interface AnvilBlock {
	damage?: import("./states").Damage;
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface SuspiciousSandBlock {
	brushed_progress?: number;
	hanging?: boolean;
}
export interface JungleLeavesBlock {
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface LightningRodBlock {
	facing_direction?: number;
}
export interface CobblestoneWallBlock {
	wall_block_type?: import("./states").WallBlockType;
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface DeepslateBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface TubeCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface SpruceDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface RedSandstoneBlock {
	sand_stone_type?: import("./states").SandStoneType;
}
export interface DarkOakLogBlock {
	new_log_type?: import("./states").NewLogType;
	pillar_axis?: import("./states").PillarAxis;
}
export interface AcaciaHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface LightBlock13Block {
	block_light_level?: number;
}
export interface OchreFroglightBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface PolishedBlackstoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface TuffWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface MangrovePressurePlateBlock {
	redstone_signal?: number;
}
export interface ObserverBlock {
	"minecraft:facing_direction"?: import("./states").MinecraftfacingDirection;
	powered_bit?: boolean;
}
export interface PinkGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface BrownGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface BrownCandleCakeBlock {
	lit?: boolean;
}
export interface PinkCandleCakeBlock {
	lit?: boolean;
}
export interface QuartzBlockBlock {
	chisel_type?: import("./states").ChiselType;
	pillar_axis?: import("./states").PillarAxis;
}
export interface RedstoneTorchBlock {
	torch_facing_direction?: import("./states").TorchFacingDirection;
}
export interface BirchLeavesBlock {
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface SilverGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface BirchPressurePlateBlock {
	redstone_signal?: number;
}
export interface SandstoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface StrippedBambooBlockBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface CrackedStoneBricksBlock {
	stone_brick_type?: import("./states").StoneBrickType;
}
export interface DeadTubeCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface BirchFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface SculkCatalystBlock {
	bloom?: boolean;
}
export interface HornCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface OakDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface StrippedWarpedStemBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface DaylightDetectorBlock {
	redstone_signal?: number;
}
export interface SmoothSandstoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface JunglePressurePlateBlock {
	redstone_signal?: number;
}
export interface DoubleCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface BirchButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface SandstoneBlock {
	sand_stone_type?: import("./states").SandStoneType;
}
export interface BlackstoneWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface LightWeightedPressurePlateBlock {
	redstone_signal?: number;
}
export interface BambooBlock {
	age_bit?: boolean;
	bamboo_leaf_size?: import("./states").BambooLeafSize;
	bamboo_stalk_thickness?: import("./states").BambooStalkThickness;
}
export interface RedNetherBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface StickyPistonArmCollisionBlock {
	facing_direction?: number;
}
export interface ExposedCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface WarpedStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface BedrockBlock {
	infiniburn_bit?: boolean;
}
export interface LightBlock10Block {
	block_light_level?: number;
}
export interface TuffBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
}
export interface RoseBushBlock {
	double_plant_type?: import("./states").DoublePlantType;
	upper_block_bit?: boolean;
}
export interface PurpleCandleCakeBlock {
	lit?: boolean;
}
export interface PrismarineBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface PolishedBlackstoneWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface QuartzPillarBlock {
	chisel_type?: import("./states").ChiselType;
	pillar_axis?: import("./states").PillarAxis;
}
export interface JungleHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface CherryWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface BirchSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface CrimsonDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface JungleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface StonePressurePlateBlock {
	redstone_signal?: number;
}
export interface QuartzStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface WaxedExposedCutCopperStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface MudBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface FarmlandBlock {
	moisturized_amount?: number;
}
export interface DeadBrainCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface PinkCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface NormalStoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface BrownCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface LightBlock12Block {
	block_light_level?: number;
}
export interface RailBlock {
	rail_direction?: number;
}
export interface SoulLanternBlock {
	hanging?: boolean;
}
export interface CarrotsBlock {
	growth?: number;
}
export interface AcaciaTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface StoneBricksBlock {
	stone_brick_type?: import("./states").StoneBrickType;
}
export interface MossyCobblestoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface WaxedWeatheredCopperDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface DarkPrismarineBlock {
	prismarine_block_type?: import("./states").PrismarineBlockType;
}
export interface InfestedCobblestoneBlock {
	monster_egg_stone_type?: import("./states").MonsterEggStoneType;
}
export interface BrainCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface MangroveWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface RedGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface DarkOakFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface CherryButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface WarpedDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface StructureVoidBlock {
	structure_void_type?: import("./states").StructureVoidType;
}
export interface BambooFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface WaxedExposedCopperBulbBlock {
	lit?: boolean;
	powered_bit?: boolean;
}
export interface BubbleCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface PolishedBlackstoneBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface NormalStoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface PurpleCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface CalibratedSculkSensorBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
	sculk_sensor_phase?: number;
}
export interface OakSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface SandBlock {
	sand_type?: import("./states").SandType;
}
export interface MangroveStandingSignBlock {
	ground_sign_direction?: number;
}
export interface JungleStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface MossyStoneBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface CutRedSandstoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface AzaleaLeavesBlock {
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface BambooDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface SmoothStoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface InfestedChiseledStoneBricksBlock {
	monster_egg_stone_type?: import("./states").MonsterEggStoneType;
}
export interface DeadTubeCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface AcaciaDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface LightBlueGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface PrismarineSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface PrismarineDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface LightBlock11Block {
	block_light_level?: number;
}
export interface CherryDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface WeatheredCutCopperStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface AcaciaLogBlock {
	new_log_type?: import("./states").NewLogType;
	pillar_axis?: import("./states").PillarAxis;
}
export interface FlowingLavaBlock {
	liquid_depth?: number;
}
export interface CrimsonTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface BasaltBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface WaxedWeatheredCopperTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface CyanGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface YellowCandleCakeBlock {
	lit?: boolean;
}
export interface StickyPistonBlock {
	facing_direction?: number;
}
export interface MediumAmethystBudBlock {
	facing_direction?: number;
	"minecraft:block_face"?: import("./states").MinecraftblockFace;
}
export interface LightBlueCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface DeepslateTileStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface SculkSensorBlock {
	powered_bit?: boolean;
	sculk_sensor_phase?: number;
}
export interface CopperBulbBlock {
	lit?: boolean;
	powered_bit?: boolean;
}
export interface DioriteStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface SmoothStoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface SpruceLeavesBlock {
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface CrimsonFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface SmoothSandstoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface StrippedCherryLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface HornCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface CopperDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface CrimsonButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface PrismarineStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface IronDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface MangroveTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface DaylightDetectorInvertedBlock {
	redstone_signal?: number;
}
export interface ChorusFlowerBlock {
	age?: number;
}
export interface TorchflowerCropBlock {
	growth?: number;
}
export interface PumpkinBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface GraniteSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface WaxedWeatheredCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface ExposedCutCopperStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface MangroveStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface PolishedDioriteSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface RedSandstoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface MangroveFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface BubbleColumnBlock {
	drag_down?: boolean;
}
export interface SunflowerBlock {
	double_plant_type?: import("./states").DoublePlantType;
	upper_block_bit?: boolean;
}
export interface BambooHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface BirchDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface WaxedWeatheredDoubleCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface FrostedIceBlock {
	age?: number;
}
export interface SpruceDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface ChiseledSandstoneBlock {
	sand_stone_type?: import("./states").SandStoneType;
}
export interface ChippedAnvilBlock {
	damage?: import("./states").Damage;
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface WarpedTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface FlowingWaterBlock {
	liquid_depth?: number;
}
export interface CaveVinesBlock {
	growing_plant_age?: number;
}
export interface OakHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface StrippedDarkOakWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface OakWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface WaxedExposedDoubleCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface WaxedOxidizedCopperTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface StrippedCherryWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface AcaciaPressurePlateBlock {
	redstone_signal?: number;
}
export interface SmoothRedSandstoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface JigsawBlock {
	facing_direction?: number;
	rotation?: number;
}
export interface BorderBlockBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface YellowCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface DarkOakStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface DeepslateTileWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface CutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface InfestedStoneBricksBlock {
	monster_egg_stone_type?: import("./states").MonsterEggStoneType;
}
export interface BambooTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface DarkOakTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface MangroveWallSignBlock {
	facing_direction?: number;
}
export interface BeetrootBlock {
	growth?: number;
}
export interface HornCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface SkullBlock {
	facing_direction?: number;
}
export interface LightGrayCandleCakeBlock {
	lit?: boolean;
}
export interface WhiteCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface GoldenRailBlock {
	rail_data_bit?: boolean;
	rail_direction?: number;
}
export interface LitFurnaceBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface PetrifiedOakDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface StructureBlockBlock {
	structure_block_type?: import("./states").StructureBlockType;
}
export interface DeprecatedAnvilBlock {
	damage?: import("./states").Damage;
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface FireCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface JungleFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface DeadBrainCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface JungleTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface SpruceWallSignBlock {
	facing_direction?: number;
}
export interface WarpedFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface ComposterBlock {
	composter_fill_level?: number;
}
export interface WaxedDoubleCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface WaxedExposedCopperDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface BlueGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface WeepingVinesBlock {
	weeping_vines_age?: number;
}
export interface MudBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface SmoothRedSandstoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface CrimsonPressurePlateBlock {
	redstone_signal?: number;
}
export interface WhiteGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface StrippedWarpedHyphaeBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface PumpkinStemBlock {
	facing_direction?: number;
	growth?: number;
}
export interface LeverBlock {
	lever_direction?: import("./states").LeverDirection;
	open_bit?: boolean;
}
export interface TrappedChestBlock {
	facing_direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface BrainCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface StandingSignBlock {
	ground_sign_direction?: number;
}
export interface CommandBlockBlock {
	conditional_bit?: boolean;
	facing_direction?: number;
}
export interface TwistingVinesBlock {
	twisting_vines_age?: number;
}
export interface AcaciaDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface PolishedAndesiteDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface ReedsBlock {
	age?: number;
}
export interface BeeNestBlock {
	direction?: number;
	honey_level?: number;
}
export interface CampfireBlock {
	direction?: number;
	extinguished?: boolean;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface DarkOakPressurePlateBlock {
	redstone_signal?: number;
}
export interface CobbledDeepslateDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface SpruceHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface EndRodBlock {
	facing_direction?: number;
}
export interface CherryLeavesBlock {
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface BlackGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface StrippedAcaciaLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface SnifferEggBlock {
	cracked_state?: import("./states").CrackedState;
}
export interface CaveVinesBodyWithBerriesBlock {
	growing_plant_age?: number;
}
export interface CherryStandingSignBlock {
	ground_sign_direction?: number;
}
export interface MangroveHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface WaxedExposedCopperTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface MossyStoneBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface CrimsonStemBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface ColoredTorchRgBlock {
	color_bit?: boolean;
	torch_facing_direction?: import("./states").TorchFacingDirection;
}
export interface TuffBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
}
export interface VaultBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
	ominous?: boolean;
	vault_state?: import("./states").VaultState;
}
export interface AzaleaLeavesFloweredBlock {
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface CrimsonSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface WarpedHyphaeBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface OxeyeDaisyBlock {
	flower_type?: import("./states").FlowerType;
}
export interface BambooButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface TuffStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface WaxedOxidizedCopperDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface TripwireHookBlock {
	attached_bit?: boolean;
	direction?: number;
	powered_bit?: boolean;
}
export interface StrippedBirchLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface RedTulipBlock {
	flower_type?: import("./states").FlowerType;
}
export interface CutSandstoneBlock {
	sand_stone_type?: import("./states").SandStoneType;
}
export interface BlueCandleCakeBlock {
	lit?: boolean;
}
export interface LargeFernBlock {
	double_plant_type?: import("./states").DoublePlantType;
	upper_block_bit?: boolean;
}
export interface SweetBerryBushBlock {
	growth?: number;
}
export interface PolishedBlackstoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface JungleSaplingBlock {
	age_bit?: boolean;
	sapling_type?: import("./states").SaplingType;
}
export interface JungleStandingSignBlock {
	ground_sign_direction?: number;
}
export interface WeatheredCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface CocoaBlock {
	age?: number;
	direction?: number;
}
export interface DarkOakLeavesBlock {
	new_leaf_type?: import("./states").NewLeafType;
	persistent_bit?: boolean;
	update_bit?: boolean;
}
export interface FireBlock {
	age?: number;
}
export interface PurpurDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface InfestedStoneBlock {
	monster_egg_stone_type?: import("./states").MonsterEggStoneType;
}
export interface EndPortalFrameBlock {
	direction?: number;
	end_portal_eye_bit?: boolean;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface PrismarineBlock {
	prismarine_block_type?: import("./states").PrismarineBlockType;
}
export interface MagentaCandleCakeBlock {
	lit?: boolean;
}
export interface NetherBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface PrismarineBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface WaxedWeatheredCutCopperStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface AcaciaStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface PolishedAndesiteStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface CherrySlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface SmoothRedSandstoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface LitBlastFurnaceBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface TuffBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface ChemistryTableBlock {
	chemistry_table_type?: import("./states").ChemistryTableType;
	direction?: number;
}
export interface DeadFireCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface StoneBrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface StrippedSpruceLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface WaxedOxidizedCopperBulbBlock {
	lit?: boolean;
	powered_bit?: boolean;
}
export interface DeepslateBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface StrippedCrimsonStemBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface AcaciaSaplingBlock {
	age_bit?: boolean;
	sapling_type?: import("./states").SaplingType;
}
export interface StonecutterBlockBlock {
	facing_direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface AndesiteSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface UnpoweredComparatorBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
	output_lit_bit?: boolean;
	output_subtract_bit?: boolean;
}
export interface LimeCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface WoodenButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface MangroveDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface EndStoneBrickDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface WeatheredCopperDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface PearlescentFroglightBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface TallGrassBlock {
	double_plant_type?: import("./states").DoublePlantType;
	upper_block_bit?: boolean;
}
export interface LightBlock15Block {
	block_light_level?: number;
}
export interface DeadHornCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface DeadHornCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface FurnaceBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface WarpedSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface WarpedStemBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface ChainBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface HornCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface BrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface FireCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface SpruceTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface PurpleGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface ChainCommandBlockBlock {
	conditional_bit?: boolean;
	facing_direction?: number;
}
export interface SpruceFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface RedNetherBrickStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface GreenGlazedTerracottaBlock {
	facing_direction?: number;
}
export interface DeadBrainCoralBlockBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface BirchTrapdoorBlock {
	direction?: number;
	open_bit?: boolean;
	upside_down_bit?: boolean;
}
export interface BedBlock {
	direction?: number;
	head_piece_bit?: boolean;
	occupied_bit?: boolean;
}
export interface TntBlock {
	allow_underwater_bit?: boolean;
	explode_bit?: boolean;
}
export interface DeadTubeCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface PolishedDioriteStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface DeadFireCoralFanBlock {
	coral_color?: import("./states").CoralColor;
	coral_fan_direction?: number;
}
export interface DecoratedPotBlock {
	direction?: number;
}
export interface GraniteDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface BubbleCoralWallFanBlock {
	coral_direction?: number;
	coral_hang_type_bit?: boolean;
	dead_bit?: boolean;
}
export interface OrangeTulipBlock {
	flower_type?: import("./states").FlowerType;
}
export interface BellBlock {
	attachment?: import("./states").Attachment;
	direction?: number;
	toggle_bit?: boolean;
}
export interface BirchWallSignBlock {
	facing_direction?: number;
}
export interface BambooWallSignBlock {
	facing_direction?: number;
}
export interface AcaciaWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface HopperBlock {
	facing_direction?: number;
	toggle_bit?: boolean;
}
export interface PrismarineBricksBlock {
	prismarine_block_type?: import("./states").PrismarineBlockType;
}
export interface LecternBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
	powered_bit?: boolean;
}
export interface AcaciaButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface StandingBannerBlock {
	ground_sign_direction?: number;
}
export interface WaxedOxidizedDoubleCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface MangrovePropaguleBlock {
	hanging?: boolean;
	propagule_stage?: number;
}
export interface PolishedDioriteDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface MossyCobblestoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_2?: import("./states").StoneSlabType2;
	top_slot_bit?: boolean;
}
export interface BirchStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface SpruceSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface BlackstoneStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface LanternBlock {
	hanging?: boolean;
}
export interface BirchDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface CrimsonHangingSignBlock {
	attached_bit?: boolean;
	facing_direction?: number;
	ground_sign_direction?: number;
	hanging?: boolean;
}
export interface BambooStandingSignBlock {
	ground_sign_direction?: number;
}
export interface StrippedMangroveLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface WeatheredCopperBulbBlock {
	lit?: boolean;
	powered_bit?: boolean;
}
export interface WarpedButtonBlock {
	button_pressed_bit?: boolean;
	facing_direction?: number;
}
export interface DeadBubbleCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface CherrySaplingBlock {
	age_bit?: boolean;
}
export interface CherryLogBlock {
	pillar_axis?: import("./states").PillarAxis;
}
export interface PolishedTuffStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface CobbledDeepslateSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface LilacBlock {
	double_plant_type?: import("./states").DoublePlantType;
	upper_block_bit?: boolean;
}
export interface CrimsonStandingSignBlock {
	ground_sign_direction?: number;
}
export interface BrownMushroomBlockBlock {
	huge_mushroom_bits?: number;
}
export interface PetrifiedOakSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface CarvedPumpkinBlock {
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface DropperBlock {
	facing_direction?: number;
	triggered_bit?: boolean;
}
export interface CandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface PolishedAndesiteSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_3?: import("./states").StoneSlabType3;
	top_slot_bit?: boolean;
}
export interface AcaciaSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface CobbledDeepslateWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface PointedDripstoneBlock {
	dripstone_thickness?: import("./states").DripstoneThickness;
	hanging?: boolean;
}
export interface CutRedSandstoneSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface TripWireBlock {
	attached_bit?: boolean;
	disarmed_bit?: boolean;
	powered_bit?: boolean;
	suspended_bit?: boolean;
}
export interface CaveVinesHeadWithBerriesBlock {
	growing_plant_age?: number;
}
export interface ChiseledRedSandstoneBlock {
	sand_stone_type?: import("./states").SandStoneType;
}
export interface BrickSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface BrewingStandBlock {
	brewing_stand_slot_a_bit?: boolean;
	brewing_stand_slot_b_bit?: boolean;
	brewing_stand_slot_c_bit?: boolean;
}
export interface BambooSaplingBlock {
	age_bit?: boolean;
}
export interface SmoothQuartzSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type_4?: import("./states").StoneSlabType4;
	top_slot_bit?: boolean;
}
export interface WhiteCandleCakeBlock {
	lit?: boolean;
}
export interface JungleDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface SpruceWoodBlock {
	pillar_axis?: import("./states").PillarAxis;
	stripped_bit?: boolean;
}
export interface PolishedDeepslateWallBlock {
	wall_connection_type_east?: import("./states").WallConnectionTypeEast;
	wall_connection_type_north?: import("./states").WallConnectionTypeNorth;
	wall_connection_type_south?: import("./states").WallConnectionTypeSouth;
	wall_connection_type_west?: import("./states").WallConnectionTypeWest;
	wall_post_bit?: boolean;
}
export interface LitSmokerBlock {
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface SmoothQuartzStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface PurpurBlockBlock {
	chisel_type?: import("./states").ChiselType;
	pillar_axis?: import("./states").PillarAxis;
}
export interface CherryWallSignBlock {
	facing_direction?: number;
}
export interface CyanCandleBlock {
	candles?: number;
	lit?: boolean;
}
export interface RepeatingCommandBlockBlock {
	conditional_bit?: boolean;
	facing_direction?: number;
}
export interface TuffDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
}
export interface PurpurStairsBlock {
	upside_down_bit?: boolean;
	weirdo_direction?: number;
}
export interface TubeCoralBlock {
	coral_color?: import("./states").CoralColor;
	dead_bit?: boolean;
}
export interface WaxedCopperDoorBlock {
	direction?: number;
	door_hinge_bit?: boolean;
	open_bit?: boolean;
	upper_block_bit?: boolean;
}
export interface PortalBlock {
	portal_axis?: import("./states").PortalAxis;
}
export interface PeonyBlock {
	double_plant_type?: import("./states").DoublePlantType;
	upper_block_bit?: boolean;
}
export interface CrafterBlock {
	crafting?: boolean;
	orientation?: import("./states").Orientation;
	triggered_bit?: boolean;
}
export interface AmethystClusterBlock {
	facing_direction?: number;
	"minecraft:block_face"?: import("./states").MinecraftblockFace;
}
export interface WaxedCutCopperSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	top_slot_bit?: boolean;
}
export interface TurtleEggBlock {
	cracked_state?: import("./states").CrackedState;
	turtle_egg_count?: import("./states").TurtleEggCount;
}
export interface CobblestoneDoubleSlabBlock {
	"minecraft:vertical_half"?: import("./states").MinecraftverticalHalf;
	stone_slab_type?: import("./states").StoneSlabType;
	top_slot_bit?: boolean;
}
export interface SoulCampfireBlock {
	direction?: number;
	extinguished?: boolean;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface WoodenPressurePlateBlock {
	redstone_signal?: number;
}
export interface DamagedAnvilBlock {
	damage?: import("./states").Damage;
	direction?: number;
	"minecraft:cardinal_direction"?: import("./states").MinecraftcardinalDirection;
}
export interface OrangeCandleCakeBlock {
	lit?: boolean;
}
export interface CherryFenceGateBlock {
	direction?: number;
	in_wall_bit?: boolean;
	open_bit?: boolean;
}
export interface GrayGlazedTerracottaBlock {
	facing_direction?: number;
}
