// WARNING, DO NOT EDIT!
// This file is automatically generated on start up.

import { BlockIdentifier } from "../enums/identifier";

export interface BlockState {
	[BlockIdentifier.PinkTulip]: import("./blocks").PinkTulipBlock;
	[BlockIdentifier.BuddingAmethyst]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightBlueConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Gravel]: Record<string, string | number | boolean>;
	[BlockIdentifier.DetectorRail]: import("./blocks").DetectorRailBlock;
	[BlockIdentifier.CyanTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardPinkStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.LightGrayCandle]: import("./blocks").LightGrayCandleBlock;
	[BlockIdentifier.NetherGoldOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedBasalt]: import("./blocks").PolishedBasaltBlock;
	[BlockIdentifier.BlueCandle]: import("./blocks").BlueCandleBlock;
	[BlockIdentifier.DarkOakWood]: import("./blocks").DarkOakWoodBlock;
	[BlockIdentifier.TuffBrickWall]: import("./blocks").TuffBrickWallBlock;
	[BlockIdentifier.AcaciaWallSign]: import("./blocks").AcaciaWallSignBlock;
	[BlockIdentifier.BambooPressurePlate]: import("./blocks").BambooPressurePlateBlock;
	[BlockIdentifier.MelonBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.RedWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.GoldOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchStandingSign]: import("./blocks").BirchStandingSignBlock;
	[BlockIdentifier.Element93]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedCutCopperStairs]: import("./blocks").WaxedCutCopperStairsBlock;
	[BlockIdentifier.Cornflower]: import("./blocks").CornflowerBlock;
	[BlockIdentifier.RedNetherBrick]: Record<string, string | number | boolean>;
	[BlockIdentifier.OxidizedCutCopperStairs]: import("./blocks").OxidizedCutCopperStairsBlock;
	[BlockIdentifier.WarpedDoor]: import("./blocks").WarpedDoorBlock;
	[BlockIdentifier.PolishedGraniteStairs]: import("./blocks").PolishedGraniteStairsBlock;
	[BlockIdentifier.RedMushroomBlock]: import("./blocks").RedMushroomBlockBlock;
	[BlockIdentifier.Element30]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeadBubbleCoralWallFan]: import("./blocks").DeadBubbleCoralWallFanBlock;
	[BlockIdentifier.BlueCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.BambooBlock]: import("./blocks").BambooBlockBlock;
	[BlockIdentifier.DeepslateBricks]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedCopper]: Record<string, string | number | boolean>;
	[BlockIdentifier.WhiteWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.WoodenDoor]: import("./blocks").WoodenDoorBlock;
	[BlockIdentifier.PistonArmCollision]: import("./blocks").PistonArmCollisionBlock;
	[BlockIdentifier.RedSandstoneSlab]: import("./blocks").RedSandstoneSlabBlock;
	[BlockIdentifier.DarkPrismarineStairs]: import("./blocks").DarkPrismarineStairsBlock;
	[BlockIdentifier.EndBricks]: Record<string, string | number | boolean>;
	[BlockIdentifier.SculkShrieker]: import("./blocks").SculkShriekerBlock;
	[BlockIdentifier.BambooMosaicStairs]: import("./blocks").BambooMosaicStairsBlock;
	[BlockIdentifier.Vine]: import("./blocks").VineBlock;
	[BlockIdentifier.WaxedOxidizedChiseledCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WhiteTulip]: import("./blocks").WhiteTulipBlock;
	[BlockIdentifier.Granite]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedTuffSlab]: import("./blocks").PolishedTuffSlabBlock;
	[BlockIdentifier.BrownMushroom]: Record<string, string | number | boolean>;
	[BlockIdentifier.CutCopperStairs]: import("./blocks").CutCopperStairsBlock;
	[BlockIdentifier.BlueStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Element0]: Record<string, string | number | boolean>;
	[BlockIdentifier.ExposedCopperDoor]: import("./blocks").ExposedCopperDoorBlock;
	[BlockIdentifier.BlackstoneDoubleSlab]: import("./blocks").BlackstoneDoubleSlabBlock;
	[BlockIdentifier.SpruceStandingSign]: import("./blocks").SpruceStandingSignBlock;
	[BlockIdentifier.Element118]: Record<string, string | number | boolean>;
	[BlockIdentifier.FenceGate]: import("./blocks").FenceGateBlock;
	[BlockIdentifier.DeepslateTileSlab]: import("./blocks").DeepslateTileSlabBlock;
	[BlockIdentifier.PowderSnow]: Record<string, string | number | boolean>;
	[BlockIdentifier.MagentaCandle]: import("./blocks").MagentaCandleBlock;
	[BlockIdentifier.DeepslateTileDoubleSlab]: import("./blocks").DeepslateTileDoubleSlabBlock;
	[BlockIdentifier.Calcite]: Record<string, string | number | boolean>;
	[BlockIdentifier.GrayTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.CyanCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.CyanStainedGlass]: Record<string, string | number | boolean>;
	[BlockIdentifier.DarkOakButton]: import("./blocks").DarkOakButtonBlock;
	[BlockIdentifier.DeepslateCopperOre]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.StoneBrickStairs]: import("./blocks").StoneBrickStairsBlock;
	[BlockIdentifier.WaxedOxidizedCutCopperSlab]: import("./blocks").WaxedOxidizedCutCopperSlabBlock;
	[BlockIdentifier.WarpedWallSign]: import("./blocks").WarpedWallSignBlock;
	[BlockIdentifier.Ladder]: import("./blocks").LadderBlock;
	[BlockIdentifier.ChiseledStoneBricks]: import("./blocks").ChiseledStoneBricksBlock;
	[BlockIdentifier.SprucePressurePlate]: import("./blocks").SprucePressurePlateBlock;
	[BlockIdentifier.DiamondOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedOxidizedCutCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DeadHornCoralWallFan]: import("./blocks").DeadHornCoralWallFanBlock;
	[BlockIdentifier.GrayConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element73]: Record<string, string | number | boolean>;
	[BlockIdentifier.CobblestoneSlab]: import("./blocks").CobblestoneSlabBlock;
	[BlockIdentifier.GreenTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardPurpleStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WaxedCopperTrapdoor]: import("./blocks").WaxedCopperTrapdoorBlock;
	[BlockIdentifier.NetherBrickStairs]: import("./blocks").NetherBrickStairsBlock;
	[BlockIdentifier.HardBlueStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.YellowShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.ChiseledCopper]: Record<string, string | number | boolean>;
	[BlockIdentifier.GraniteStairs]: import("./blocks").GraniteStairsBlock;
	[BlockIdentifier.GrayWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.GreenConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.LimeStainedGlass]: Record<string, string | number | boolean>;
	[BlockIdentifier.OxidizedCopperBulb]: import("./blocks").OxidizedCopperBulbBlock;
	[BlockIdentifier.CobbledDeepslateStairs]: import("./blocks").CobbledDeepslateStairsBlock;
	[BlockIdentifier.WaxedExposedCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.StrippedAcaciaWood]: import("./blocks").StrippedAcaciaWoodBlock;
	[BlockIdentifier.Element16]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleButton]: import("./blocks").JungleButtonBlock;
	[BlockIdentifier.DeadBubbleCoralFan]: import("./blocks").DeadBubbleCoralFanBlock;
	[BlockIdentifier.PoweredRepeater]: import("./blocks").PoweredRepeaterBlock;
	[BlockIdentifier.SpruceStairs]: import("./blocks").SpruceStairsBlock;
	[BlockIdentifier.Loom]: import("./blocks").LoomBlock;
	[BlockIdentifier.HardGreenStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Element104]: Record<string, string | number | boolean>;
	[BlockIdentifier.YellowStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.OxidizedDoubleCutCopperSlab]: import("./blocks").OxidizedDoubleCutCopperSlabBlock;
	[BlockIdentifier.JungleDoor]: import("./blocks").JungleDoorBlock;
	[BlockIdentifier.Diorite]: Record<string, string | number | boolean>;
	[BlockIdentifier.DarkoakWallSign]: import("./blocks").DarkoakWallSignBlock;
	[BlockIdentifier.InfoUpdate2]: Record<string, string | number | boolean>;
	[BlockIdentifier.DripstoneBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.GrayCandleCake]: import("./blocks").GrayCandleCakeBlock;
	[BlockIdentifier.ExposedCopperTrapdoor]: import("./blocks").ExposedCopperTrapdoorBlock;
	[BlockIdentifier.BlueTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.HangingRoots]: Record<string, string | number | boolean>;
	[BlockIdentifier.SmoothSandstone]: import("./blocks").SmoothSandstoneBlock;
	[BlockIdentifier.PolishedBlackstoneButton]: import("./blocks").PolishedBlackstoneButtonBlock;
	[BlockIdentifier.StrippedBirchWood]: import("./blocks").StrippedBirchWoodBlock;
	[BlockIdentifier.RedCandleCake]: import("./blocks").RedCandleCakeBlock;
	[BlockIdentifier.MossyStoneBricks]: import("./blocks").MossyStoneBricksBlock;
	[BlockIdentifier.HardLightBlueStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CherryPressurePlate]: import("./blocks").CherryPressurePlateBlock;
	[BlockIdentifier.HardBrownStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CherryHangingSign]: import("./blocks").CherryHangingSignBlock;
	[BlockIdentifier.YellowWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.BlackCandleCake]: import("./blocks").BlackCandleCakeBlock;
	[BlockIdentifier.CrimsonWallSign]: import("./blocks").CrimsonWallSignBlock;
	[BlockIdentifier.PolishedBlackstoneBrickStairs]: import("./blocks").PolishedBlackstoneBrickStairsBlock;
	[BlockIdentifier.LightBlock1]: import("./blocks").LightBlock1Block;
	[BlockIdentifier.Element46]: Record<string, string | number | boolean>;
	[BlockIdentifier.SmoothSandstoneSlab]: import("./blocks").SmoothSandstoneSlabBlock;
	[BlockIdentifier.GrayCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.DarkOakDoor]: import("./blocks").DarkOakDoorBlock;
	[BlockIdentifier.Wheat]: import("./blocks").WheatBlock;
	[BlockIdentifier.Grindstone]: import("./blocks").GrindstoneBlock;
	[BlockIdentifier.OakFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.YellowStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DarkOakSlab]: import("./blocks").DarkOakSlabBlock;
	[BlockIdentifier.PolishedGraniteDoubleSlab]: import("./blocks").PolishedGraniteDoubleSlabBlock;
	[BlockIdentifier.HoneycombBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.EndGateway]: Record<string, string | number | boolean>;
	[BlockIdentifier.AzureBluet]: import("./blocks").AzureBluetBlock;
	[BlockIdentifier.StoneStairs]: import("./blocks").StoneStairsBlock;
	[BlockIdentifier.Beacon]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedBlackstoneBrickWall]: import("./blocks").PolishedBlackstoneBrickWallBlock;
	[BlockIdentifier.SnowLayer]: import("./blocks").SnowLayerBlock;
	[BlockIdentifier.HardPinkStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BrickDoubleSlab]: import("./blocks").BrickDoubleSlabBlock;
	[BlockIdentifier.WhiteCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.BlackCandle]: import("./blocks").BlackCandleBlock;
	[BlockIdentifier.Cactus]: import("./blocks").CactusBlock;
	[BlockIdentifier.GlowFrame]: import("./blocks").GlowFrameBlock;
	[BlockIdentifier.MudBrickDoubleSlab]: import("./blocks").MudBrickDoubleSlabBlock;
	[BlockIdentifier.BambooMosaicSlab]: import("./blocks").BambooMosaicSlabBlock;
	[BlockIdentifier.BambooFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.DarkPrismarineSlab]: import("./blocks").DarkPrismarineSlabBlock;
	[BlockIdentifier.PrismarineBricksStairs]: import("./blocks").PrismarineBricksStairsBlock;
	[BlockIdentifier.Mycelium]: Record<string, string | number | boolean>;
	[BlockIdentifier.DioriteSlab]: import("./blocks").DioriteSlabBlock;
	[BlockIdentifier.RedConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.CrimsonHyphae]: import("./blocks").CrimsonHyphaeBlock;
	[BlockIdentifier.BlackTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.StrippedDarkOakLog]: import("./blocks").StrippedDarkOakLogBlock;
	[BlockIdentifier.HardOrangeStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.OxidizedCopperGrate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.JungleLog]: import("./blocks").JungleLogBlock;
	[BlockIdentifier.BubbleCoralFan]: import("./blocks").BubbleCoralFanBlock;
	[BlockIdentifier.BambooSlab]: import("./blocks").BambooSlabBlock;
	[BlockIdentifier.LitRedstoneOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.NetherWart]: import("./blocks").NetherWartBlock;
	[BlockIdentifier.OrangeStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.StrippedMangroveWood]: import("./blocks").StrippedMangroveWoodBlock;
	[BlockIdentifier.CutRedSandstone]: import("./blocks").CutRedSandstoneBlock;
	[BlockIdentifier.LimeShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardBlackStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.SmoothRedSandstone]: import("./blocks").SmoothRedSandstoneBlock;
	[BlockIdentifier.LilyOfTheValley]: import("./blocks").LilyOfTheValleyBlock;
	[BlockIdentifier.BlueOrchid]: import("./blocks").BlueOrchidBlock;
	[BlockIdentifier.LimeGlazedTerracotta]: import("./blocks").LimeGlazedTerracottaBlock;
	[BlockIdentifier.Trapdoor]: import("./blocks").TrapdoorBlock;
	[BlockIdentifier.HardGlassPane]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeadBrainCoralFan]: import("./blocks").DeadBrainCoralFanBlock;
	[BlockIdentifier.AcaciaStandingSign]: import("./blocks").AcaciaStandingSignBlock;
	[BlockIdentifier.UndyedShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.QuartzOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.InfoUpdate]: Record<string, string | number | boolean>;
	[BlockIdentifier.Seagrass]: import("./blocks").SeagrassBlock;
	[BlockIdentifier.TubeCoralFan]: import("./blocks").TubeCoralFanBlock;
	[BlockIdentifier.Unknown]: Record<string, string | number | boolean>;
	[BlockIdentifier.CherryStairs]: import("./blocks").CherryStairsBlock;
	[BlockIdentifier.Barrel]: import("./blocks").BarrelBlock;
	[BlockIdentifier.BigDripleaf]: import("./blocks").BigDripleafBlock;
	[BlockIdentifier.QuartzSlab]: import("./blocks").QuartzSlabBlock;
	[BlockIdentifier.FireCoralBlock]: import("./blocks").FireCoralBlockBlock;
	[BlockIdentifier.WaxedExposedCutCopperSlab]: import("./blocks").WaxedExposedCutCopperSlabBlock;
	[BlockIdentifier.DeadHornCoral]: import("./blocks").DeadHornCoralBlock;
	[BlockIdentifier.InfestedMossyStoneBricks]: import("./blocks").InfestedMossyStoneBricksBlock;
	[BlockIdentifier.Element68]: Record<string, string | number | boolean>;
	[BlockIdentifier.RedstoneLamp]: Record<string, string | number | boolean>;
	[BlockIdentifier.MossyCobblestone]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element113]: Record<string, string | number | boolean>;
	[BlockIdentifier.BlueStainedGlass]: Record<string, string | number | boolean>;
	[BlockIdentifier.Cake]: import("./blocks").CakeBlock;
	[BlockIdentifier.DarkOakDoubleSlab]: import("./blocks").DarkOakDoubleSlabBlock;
	[BlockIdentifier.StrippedCrimsonHyphae]: import("./blocks").StrippedCrimsonHyphaeBlock;
	[BlockIdentifier.DarkOakHangingSign]: import("./blocks").DarkOakHangingSignBlock;
	[BlockIdentifier.GreenConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.Deepslate]: import("./blocks").DeepslateBlock;
	[BlockIdentifier.StrippedOakWood]: import("./blocks").StrippedOakWoodBlock;
	[BlockIdentifier.PurpurSlab]: import("./blocks").PurpurSlabBlock;
	[BlockIdentifier.MagentaCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.PitcherCrop]: import("./blocks").PitcherCropBlock;
	[BlockIdentifier.BrownWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.PinkWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.WarpedStandingSign]: import("./blocks").WarpedStandingSignBlock;
	[BlockIdentifier.Deadbush]: Record<string, string | number | boolean>;
	[BlockIdentifier.EnderChest]: import("./blocks").EnderChestBlock;
	[BlockIdentifier.WaxedExposedChiseledCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.TuffSlab]: import("./blocks").TuffSlabBlock;
	[BlockIdentifier.RedstoneWire]: import("./blocks").RedstoneWireBlock;
	[BlockIdentifier.WarpedPressurePlate]: import("./blocks").WarpedPressurePlateBlock;
	[BlockIdentifier.GreenCandleCake]: import("./blocks").GreenCandleCakeBlock;
	[BlockIdentifier.DiamondBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.ExposedCopperBulb]: import("./blocks").ExposedCopperBulbBlock;
	[BlockIdentifier.Element58]: Record<string, string | number | boolean>;
	[BlockIdentifier.BambooMosaicDoubleSlab]: import("./blocks").BambooMosaicDoubleSlabBlock;
	[BlockIdentifier.DarkPrismarineDoubleSlab]: import("./blocks").DarkPrismarineDoubleSlabBlock;
	[BlockIdentifier.CryingObsidian]: Record<string, string | number | boolean>;
	[BlockIdentifier.OakStairs]: import("./blocks").OakStairsBlock;
	[BlockIdentifier.HardGrayStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.OakLog]: import("./blocks").OakLogBlock;
	[BlockIdentifier.WaxedWeatheredCutCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Andesite]: Record<string, string | number | boolean>;
	[BlockIdentifier.BrownStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.SculkVein]: import("./blocks").SculkVeinBlock;
	[BlockIdentifier.PinkStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.ExposedDoubleCutCopperSlab]: import("./blocks").ExposedDoubleCutCopperSlabBlock;
	[BlockIdentifier.CandleCake]: import("./blocks").CandleCakeBlock;
	[BlockIdentifier.MagentaShulkerBox]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PurpleTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.SmoothQuartz]: import("./blocks").SmoothQuartzBlock;
	[BlockIdentifier.PackedIce]: Record<string, string | number | boolean>;
	[BlockIdentifier.IronBars]: Record<string, string | number | boolean>;
	[BlockIdentifier.OxidizedCutCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PolishedGranite]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element39]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightBlueStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Fern]: import("./blocks").FernBlock;
	[BlockIdentifier.PackedMud]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightBlueCandleCake]: import("./blocks").LightBlueCandleCakeBlock;
	[BlockIdentifier.Element1]: Record<string, string | number | boolean>;
	[BlockIdentifier.Poppy]: import("./blocks").PoppyBlock;
	[BlockIdentifier.MossCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.CrimsonStairs]: import("./blocks").CrimsonStairsBlock;
	[BlockIdentifier.GreenStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WarpedFungus]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element102]: Record<string, string | number | boolean>;
	[BlockIdentifier.StoneBrickDoubleSlab]: import("./blocks").StoneBrickDoubleSlabBlock;
	[BlockIdentifier.CopperOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.GrayCandle]: import("./blocks").GrayCandleBlock;
	[BlockIdentifier.PolishedDeepslateSlab]: import("./blocks").PolishedDeepslateSlabBlock;
	[BlockIdentifier.BambooDoor]: import("./blocks").BambooDoorBlock;
	[BlockIdentifier.BlackConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.MelonStem]: import("./blocks").MelonStemBlock;
	[BlockIdentifier.AmethystBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.GoldBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.StrippedOakLog]: import("./blocks").StrippedOakLogBlock;
	[BlockIdentifier.FlowerPot]: import("./blocks").FlowerPotBlock;
	[BlockIdentifier.ChiseledBookshelf]: import("./blocks").ChiseledBookshelfBlock;
	[BlockIdentifier.JungleFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.SpruceLog]: import("./blocks").SpruceLogBlock;
	[BlockIdentifier.PolishedDeepslateStairs]: import("./blocks").PolishedDeepslateStairsBlock;
	[BlockIdentifier.HardLimeStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.ShortGrass]: import("./blocks").ShortGrassBlock;
	[BlockIdentifier.LapisBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.WeatheredChiseledCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CoarseDirt]: Record<string, string | number | boolean>;
	[BlockIdentifier.SmallAmethystBud]: import("./blocks").SmallAmethystBudBlock;
	[BlockIdentifier.ActivatorRail]: import("./blocks").ActivatorRailBlock;
	[BlockIdentifier.Podzol]: Record<string, string | number | boolean>;
	[BlockIdentifier.MangroveButton]: import("./blocks").MangroveButtonBlock;
	[BlockIdentifier.IronTrapdoor]: import("./blocks").IronTrapdoorBlock;
	[BlockIdentifier.Potatoes]: import("./blocks").PotatoesBlock;
	[BlockIdentifier.LargeAmethystBud]: import("./blocks").LargeAmethystBudBlock;
	[BlockIdentifier.MuddyMangroveRoots]: import("./blocks").MuddyMangroveRootsBlock;
	[BlockIdentifier.HardLightBlueStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.TrialSpawner]: import("./blocks").TrialSpawnerBlock;
	[BlockIdentifier.StrippedJungleWood]: import("./blocks").StrippedJungleWoodBlock;
	[BlockIdentifier.DeadTubeCoralBlock]: import("./blocks").DeadTubeCoralBlockBlock;
	[BlockIdentifier.Noteblock]: Record<string, string | number | boolean>;
	[BlockIdentifier.Tuff]: Record<string, string | number | boolean>;
	[BlockIdentifier.Reserved6]: Record<string, string | number | boolean>;
	[BlockIdentifier.SoulTorch]: import("./blocks").SoulTorchBlock;
	[BlockIdentifier.QuartzBricks]: Record<string, string | number | boolean>;
	[BlockIdentifier.MangroveLog]: import("./blocks").MangroveLogBlock;
	[BlockIdentifier.SandstoneSlab]: import("./blocks").SandstoneSlabBlock;
	[BlockIdentifier.WhiteShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchWood]: import("./blocks").BirchWoodBlock;
	[BlockIdentifier.PolishedBlackstonePressurePlate]: import("./blocks").PolishedBlackstonePressurePlateBlock;
	[BlockIdentifier.MossyStoneBrickSlab]: import("./blocks").MossyStoneBrickSlabBlock;
	[BlockIdentifier.RawGoldBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.Allium]: import("./blocks").AlliumBlock;
	[BlockIdentifier.CrackedPolishedBlackstoneBricks]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.MobSpawner]: Record<string, string | number | boolean>;
	[BlockIdentifier.CopperGrate]: Record<string, string | number | boolean>;
	[BlockIdentifier.WeatheredDoubleCutCopperSlab]: import("./blocks").WeatheredDoubleCutCopperSlabBlock;
	[BlockIdentifier.DeepslateTiles]: Record<string, string | number | boolean>;
	[BlockIdentifier.BlackWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.Lava]: import("./blocks").LavaBlock;
	[BlockIdentifier.LightBlock14]: import("./blocks").LightBlock14Block;
	[BlockIdentifier.AcaciaFenceGate]: import("./blocks").AcaciaFenceGateBlock;
	[BlockIdentifier.CyanCandleCake]: import("./blocks").CyanCandleCakeBlock;
	[BlockIdentifier.OrangeCandle]: import("./blocks").OrangeCandleBlock;
	[BlockIdentifier.ColoredTorchBp]: import("./blocks").ColoredTorchBpBlock;
	[BlockIdentifier.Scaffolding]: import("./blocks").ScaffoldingBlock;
	[BlockIdentifier.PoweredComparator]: import("./blocks").PoweredComparatorBlock;
	[BlockIdentifier.LightBlock8]: import("./blocks").LightBlock8Block;
	[BlockIdentifier.SpruceSapling]: import("./blocks").SpruceSaplingBlock;
	[BlockIdentifier.CutSandstoneDoubleSlab]: import("./blocks").CutSandstoneDoubleSlabBlock;
	[BlockIdentifier.BlastFurnace]: import("./blocks").BlastFurnaceBlock;
	[BlockIdentifier.CutSandstoneSlab]: import("./blocks").CutSandstoneSlabBlock;
	[BlockIdentifier.SpruceFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardYellowStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.HardGreenStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DarkOakSapling]: import("./blocks").DarkOakSaplingBlock;
	[BlockIdentifier.SandstoneDoubleSlab]: import("./blocks").SandstoneDoubleSlabBlock;
	[BlockIdentifier.PinkPetals]: import("./blocks").PinkPetalsBlock;
	[BlockIdentifier.SoulFire]: import("./blocks").SoulFireBlock;
	[BlockIdentifier.PinkCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.MangroveDoubleSlab]: import("./blocks").MangroveDoubleSlabBlock;
	[BlockIdentifier.BrownCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.GreenCandle]: import("./blocks").GreenCandleBlock;
	[BlockIdentifier.PurpleStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.SmoothQuartzDoubleSlab]: import("./blocks").SmoothQuartzDoubleSlabBlock;
	[BlockIdentifier.OxidizedCopperTrapdoor]: import("./blocks").OxidizedCopperTrapdoorBlock;
	[BlockIdentifier.LightGrayStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BrainCoral]: import("./blocks").BrainCoralBlock;
	[BlockIdentifier.Obsidian]: Record<string, string | number | boolean>;
	[BlockIdentifier.Chest]: import("./blocks").ChestBlock;
	[BlockIdentifier.DeadBubbleCoralBlock]: import("./blocks").DeadBubbleCoralBlockBlock;
	[BlockIdentifier.LightGrayStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BlackstoneSlab]: import("./blocks").BlackstoneSlabBlock;
	[BlockIdentifier.StrippedSpruceWood]: import("./blocks").StrippedSpruceWoodBlock;
	[BlockIdentifier.Cauldron]: import("./blocks").CauldronBlock;
	[BlockIdentifier.Glowingobsidian]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeepslateBrickWall]: import("./blocks").DeepslateBrickWallBlock;
	[BlockIdentifier.DarkoakStandingSign]: import("./blocks").DarkoakStandingSignBlock;
	[BlockIdentifier.WaxedExposedCopperGrate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.TubeCoralBlock]: import("./blocks").TubeCoralBlockBlock;
	[BlockIdentifier.AcaciaPlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element85]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleWallSign]: import("./blocks").JungleWallSignBlock;
	[BlockIdentifier.EndBrickStairs]: import("./blocks").EndBrickStairsBlock;
	[BlockIdentifier.PolishedBlackstoneDoubleSlab]: import("./blocks").PolishedBlackstoneDoubleSlabBlock;
	[BlockIdentifier.OrangeCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.ExposedCopper]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedDeepslateDoubleSlab]: import("./blocks").PolishedDeepslateDoubleSlabBlock;
	[BlockIdentifier.NetherBrickSlab]: import("./blocks").NetherBrickSlabBlock;
	[BlockIdentifier.HeavyWeightedPressurePlate]: import("./blocks").HeavyWeightedPressurePlateBlock;
	[BlockIdentifier.Element89]: Record<string, string | number | boolean>;
	[BlockIdentifier.StoneButton]: import("./blocks").StoneButtonBlock;
	[BlockIdentifier.Stone]: Record<string, string | number | boolean>;
	[BlockIdentifier.RedNetherBrickDoubleSlab]: import("./blocks").RedNetherBrickDoubleSlabBlock;
	[BlockIdentifier.PitcherPlant]: import("./blocks").PitcherPlantBlock;
	[BlockIdentifier.Element101]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedCopperBulb]: import("./blocks").WaxedCopperBulbBlock;
	[BlockIdentifier.AndesiteStairs]: import("./blocks").AndesiteStairsBlock;
	[BlockIdentifier.Sponge]: import("./blocks").SpongeBlock;
	[BlockIdentifier.BoneBlock]: import("./blocks").BoneBlockBlock;
	[BlockIdentifier.NormalStoneStairs]: import("./blocks").NormalStoneStairsBlock;
	[BlockIdentifier.WarpedHangingSign]: import("./blocks").WarpedHangingSignBlock;
	[BlockIdentifier.GreenStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DioriteDoubleSlab]: import("./blocks").DioriteDoubleSlabBlock;
	[BlockIdentifier.GrayStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.EndStoneBrickSlab]: import("./blocks").EndStoneBrickSlabBlock;
	[BlockIdentifier.Frame]: import("./blocks").FrameBlock;
	[BlockIdentifier.Smoker]: import("./blocks").SmokerBlock;
	[BlockIdentifier.HardenedClay]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchHangingSign]: import("./blocks").BirchHangingSignBlock;
	[BlockIdentifier.PolishedTuffWall]: import("./blocks").PolishedTuffWallBlock;
	[BlockIdentifier.UnlitRedstoneTorch]: import("./blocks").UnlitRedstoneTorchBlock;
	[BlockIdentifier.StrippedJungleLog]: import("./blocks").StrippedJungleLogBlock;
	[BlockIdentifier.LapisOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardBlueStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PolishedGraniteSlab]: import("./blocks").PolishedGraniteSlabBlock;
	[BlockIdentifier.LightBlock9]: import("./blocks").LightBlock9Block;
	[BlockIdentifier.OxidizedCutCopperSlab]: import("./blocks").OxidizedCutCopperSlabBlock;
	[BlockIdentifier.Beehive]: import("./blocks").BeehiveBlock;
	[BlockIdentifier.LimeStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.LightBlock7]: import("./blocks").LightBlock7Block;
	[BlockIdentifier.CherryDoubleSlab]: import("./blocks").CherryDoubleSlabBlock;
	[BlockIdentifier.LightBlock6]: import("./blocks").LightBlock6Block;
	[BlockIdentifier.LightBlock5]: import("./blocks").LightBlock5Block;
	[BlockIdentifier.WaxedOxidizedCutCopperStairs]: import("./blocks").WaxedOxidizedCutCopperStairsBlock;
	[BlockIdentifier.LightBlock4]: import("./blocks").LightBlock4Block;
	[BlockIdentifier.WarpedRoots]: Record<string, string | number | boolean>;
	[BlockIdentifier.SmallDripleafBlock]: import("./blocks").SmallDripleafBlockBlock;
	[BlockIdentifier.GreenWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.LimeCandleCake]: import("./blocks").LimeCandleCakeBlock;
	[BlockIdentifier.MangroveLeaves]: import("./blocks").MangroveLeavesBlock;
	[BlockIdentifier.LightBlock3]: import("./blocks").LightBlock3Block;
	[BlockIdentifier.AcaciaLeaves]: import("./blocks").AcaciaLeavesBlock;
	[BlockIdentifier.Barrier]: Record<string, string | number | boolean>;
	[BlockIdentifier.RawIronBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.Dispenser]: import("./blocks").DispenserBlock;
	[BlockIdentifier.CrimsonRoots]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightBlock2]: import("./blocks").LightBlock2Block;
	[BlockIdentifier.LightBlock0]: import("./blocks").LightBlock0Block;
	[BlockIdentifier.Stonecutter]: Record<string, string | number | boolean>;
	[BlockIdentifier.AndesiteDoubleSlab]: import("./blocks").AndesiteDoubleSlabBlock;
	[BlockIdentifier.UnpoweredRepeater]: import("./blocks").UnpoweredRepeaterBlock;
	[BlockIdentifier.OakSapling]: import("./blocks").OakSaplingBlock;
	[BlockIdentifier.LightGrayTerracotta]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PinkStainedGlass]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardMagentaStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BrownStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.FireCoral]: import("./blocks").FireCoralBlock;
	[BlockIdentifier.CobbledDeepslate]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element99]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchLog]: import("./blocks").BirchLogBlock;
	[BlockIdentifier.OrangeStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.OrangeWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedBlackstoneBrickDoubleSlab]: import("./blocks").PolishedBlackstoneBrickDoubleSlabBlock;
	[BlockIdentifier.BubbleCoralBlock]: import("./blocks").BubbleCoralBlockBlock;
	[BlockIdentifier.CrimsonDoubleSlab]: import("./blocks").CrimsonDoubleSlabBlock;
	[BlockIdentifier.Kelp]: import("./blocks").KelpBlock;
	[BlockIdentifier.UnderwaterTorch]: import("./blocks").UnderwaterTorchBlock;
	[BlockIdentifier.RespawnAnchor]: import("./blocks").RespawnAnchorBlock;
	[BlockIdentifier.DeadFireCoralWallFan]: import("./blocks").DeadFireCoralWallFanBlock;
	[BlockIdentifier.LightGrayConcrete]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BirchPlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.SeaPickle]: import("./blocks").SeaPickleBlock;
	[BlockIdentifier.RedSandstoneDoubleSlab]: import("./blocks").RedSandstoneDoubleSlabBlock;
	[BlockIdentifier.Element74]: Record<string, string | number | boolean>;
	[BlockIdentifier.RedSand]: import("./blocks").RedSandBlock;
	[BlockIdentifier.HayBlock]: import("./blocks").HayBlockBlock;
	[BlockIdentifier.SuspiciousGravel]: import("./blocks").SuspiciousGravelBlock;
	[BlockIdentifier.HeavyCore]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleWood]: import("./blocks").JungleWoodBlock;
	[BlockIdentifier.RedStainedGlass]: Record<string, string | number | boolean>;
	[BlockIdentifier.PurpleShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedTuffDoubleSlab]: import("./blocks").PolishedTuffDoubleSlabBlock;
	[BlockIdentifier.OxidizedCopperDoor]: import("./blocks").OxidizedCopperDoorBlock;
	[BlockIdentifier.WaxedWeatheredCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.ChiseledQuartzBlock]: import("./blocks").ChiseledQuartzBlockBlock;
	[BlockIdentifier.InfestedCrackedStoneBricks]: import("./blocks").InfestedCrackedStoneBricksBlock;
	[BlockIdentifier.LightBlueTerracotta]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DeepslateBrickSlab]: import("./blocks").DeepslateBrickSlabBlock;
	[BlockIdentifier.FloweringAzalea]: Record<string, string | number | boolean>;
	[BlockIdentifier.InvisibleBedrock]: Record<string, string | number | boolean>;
	[BlockIdentifier.OakLeaves]: import("./blocks").OakLeavesBlock;
	[BlockIdentifier.BrainCoralFan]: import("./blocks").BrainCoralFanBlock;
	[BlockIdentifier.BambooStairs]: import("./blocks").BambooStairsBlock;
	[BlockIdentifier.Torch]: import("./blocks").TorchBlock;
	[BlockIdentifier.GlowLichen]: import("./blocks").GlowLichenBlock;
	[BlockIdentifier.CopperTrapdoor]: import("./blocks").CopperTrapdoorBlock;
	[BlockIdentifier.RedCandle]: import("./blocks").RedCandleBlock;
	[BlockIdentifier.MudBrickWall]: import("./blocks").MudBrickWallBlock;
	[BlockIdentifier.HoneyBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.CherryTrapdoor]: import("./blocks").CherryTrapdoorBlock;
	[BlockIdentifier.BrownConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.LitPumpkin]: import("./blocks").LitPumpkinBlock;
	[BlockIdentifier.PinkConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.YellowGlazedTerracotta]: import("./blocks").YellowGlazedTerracottaBlock;
	[BlockIdentifier.SmoothBasalt]: Record<string, string | number | boolean>;
	[BlockIdentifier.WarpedPlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.Piston]: import("./blocks").PistonBlock;
	[BlockIdentifier.CherryFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.MangrovePlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardLightGrayStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.RedTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.Water]: import("./blocks").WaterBlock;
	[BlockIdentifier.WeatheredCopperTrapdoor]: import("./blocks").WeatheredCopperTrapdoorBlock;
	[BlockIdentifier.Element77]: Record<string, string | number | boolean>;
	[BlockIdentifier.WeatheredCopperGrate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.SpruceButton]: import("./blocks").SpruceButtonBlock;
	[BlockIdentifier.WallBanner]: import("./blocks").WallBannerBlock;
	[BlockIdentifier.DeadFireCoralBlock]: import("./blocks").DeadFireCoralBlockBlock;
	[BlockIdentifier.MagentaWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedWeatheredCopperGrate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WaxedWeatheredCopperBulb]: import("./blocks").WaxedWeatheredCopperBulbBlock;
	[BlockIdentifier.VerdantFroglight]: import("./blocks").VerdantFroglightBlock;
	[BlockIdentifier.MossyCobblestoneSlab]: import("./blocks").MossyCobblestoneSlabBlock;
	[BlockIdentifier.MagentaGlazedTerracotta]: import("./blocks").MagentaGlazedTerracottaBlock;
	[BlockIdentifier.PolishedAndesite]: Record<string, string | number | boolean>;
	[BlockIdentifier.PurpleStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.QuartzDoubleSlab]: import("./blocks").QuartzDoubleSlabBlock;
	[BlockIdentifier.MangroveSlab]: import("./blocks").MangroveSlabBlock;
	[BlockIdentifier.WallSign]: import("./blocks").WallSignBlock;
	[BlockIdentifier.InfestedDeepslate]: import("./blocks").InfestedDeepslateBlock;
	[BlockIdentifier.OrangeGlazedTerracotta]: import("./blocks").OrangeGlazedTerracottaBlock;
	[BlockIdentifier.BirchSapling]: import("./blocks").BirchSaplingBlock;
	[BlockIdentifier.ClientRequestPlaceholderBlock]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.HardBrownStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Torchflower]: Record<string, string | number | boolean>;
	[BlockIdentifier.SporeBlossom]: Record<string, string | number | boolean>;
	[BlockIdentifier.Waterlily]: Record<string, string | number | boolean>;
	[BlockIdentifier.EmeraldBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.Conduit]: Record<string, string | number | boolean>;
	[BlockIdentifier.Anvil]: import("./blocks").AnvilBlock;
	[BlockIdentifier.SuspiciousSand]: import("./blocks").SuspiciousSandBlock;
	[BlockIdentifier.AncientDebris]: Record<string, string | number | boolean>;
	[BlockIdentifier.DarkOakPlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleLeaves]: import("./blocks").JungleLeavesBlock;
	[BlockIdentifier.LightningRod]: import("./blocks").LightningRodBlock;
	[BlockIdentifier.NetherBrickFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.BlackStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.MagentaConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.CobblestoneWall]: import("./blocks").CobblestoneWallBlock;
	[BlockIdentifier.LightBlueStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DeepslateBrickDoubleSlab]: import("./blocks").DeepslateBrickDoubleSlabBlock;
	[BlockIdentifier.TubeCoralWallFan]: import("./blocks").TubeCoralWallFanBlock;
	[BlockIdentifier.SpruceDoubleSlab]: import("./blocks").SpruceDoubleSlabBlock;
	[BlockIdentifier.RedSandstone]: import("./blocks").RedSandstoneBlock;
	[BlockIdentifier.DarkOakLog]: import("./blocks").DarkOakLogBlock;
	[BlockIdentifier.OakPlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.RedstoneOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.AcaciaHangingSign]: import("./blocks").AcaciaHangingSignBlock;
	[BlockIdentifier.LightBlock13]: import("./blocks").LightBlock13Block;
	[BlockIdentifier.OchreFroglight]: import("./blocks").OchreFroglightBlock;
	[BlockIdentifier.PolishedBlackstoneStairs]: import("./blocks").PolishedBlackstoneStairsBlock;
	[BlockIdentifier.TuffWall]: import("./blocks").TuffWallBlock;
	[BlockIdentifier.MangrovePressurePlate]: import("./blocks").MangrovePressurePlateBlock;
	[BlockIdentifier.Observer]: import("./blocks").ObserverBlock;
	[BlockIdentifier.PinkGlazedTerracotta]: import("./blocks").PinkGlazedTerracottaBlock;
	[BlockIdentifier.YellowTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.BrownGlazedTerracotta]: import("./blocks").BrownGlazedTerracottaBlock;
	[BlockIdentifier.BrownCandleCake]: import("./blocks").BrownCandleCakeBlock;
	[BlockIdentifier.PinkCandleCake]: import("./blocks").PinkCandleCakeBlock;
	[BlockIdentifier.QuartzBlock]: import("./blocks").QuartzBlockBlock;
	[BlockIdentifier.RedstoneTorch]: import("./blocks").RedstoneTorchBlock;
	[BlockIdentifier.BirchLeaves]: import("./blocks").BirchLeavesBlock;
	[BlockIdentifier.SilverGlazedTerracotta]: import("./blocks").SilverGlazedTerracottaBlock;
	[BlockIdentifier.CyanConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.OxidizedCopper]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchPressurePlate]: import("./blocks").BirchPressurePlateBlock;
	[BlockIdentifier.Element19]: Record<string, string | number | boolean>;
	[BlockIdentifier.SandstoneStairs]: import("./blocks").SandstoneStairsBlock;
	[BlockIdentifier.StrippedBambooBlock]: import("./blocks").StrippedBambooBlockBlock;
	[BlockIdentifier.CrackedStoneBricks]: import("./blocks").CrackedStoneBricksBlock;
	[BlockIdentifier.DeadTubeCoralWallFan]: import("./blocks").DeadTubeCoralWallFanBlock;
	[BlockIdentifier.BirchFenceGate]: import("./blocks").BirchFenceGateBlock;
	[BlockIdentifier.SculkCatalyst]: import("./blocks").SculkCatalystBlock;
	[BlockIdentifier.Element115]: Record<string, string | number | boolean>;
	[BlockIdentifier.Cobblestone]: Record<string, string | number | boolean>;
	[BlockIdentifier.HornCoral]: import("./blocks").HornCoralBlock;
	[BlockIdentifier.WhiteConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.YellowConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.OakDoubleSlab]: import("./blocks").OakDoubleSlabBlock;
	[BlockIdentifier.StrippedWarpedStem]: import("./blocks").StrippedWarpedStemBlock;
	[BlockIdentifier.DaylightDetector]: import("./blocks").DaylightDetectorBlock;
	[BlockIdentifier.SmoothSandstoneStairs]: import("./blocks").SmoothSandstoneStairsBlock;
	[BlockIdentifier.JunglePressurePlate]: import("./blocks").JunglePressurePlateBlock;
	[BlockIdentifier.HardWhiteStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DoubleCutCopperSlab]: import("./blocks").DoubleCutCopperSlabBlock;
	[BlockIdentifier.BirchButton]: import("./blocks").BirchButtonBlock;
	[BlockIdentifier.CrimsonPlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.Sandstone]: import("./blocks").SandstoneBlock;
	[BlockIdentifier.BlackstoneWall]: import("./blocks").BlackstoneWallBlock;
	[BlockIdentifier.LightWeightedPressurePlate]: import("./blocks").LightWeightedPressurePlateBlock;
	[BlockIdentifier.PolishedBlackstone]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Bamboo]: import("./blocks").BambooBlock;
	[BlockIdentifier.RedNetherBrickSlab]: import("./blocks").RedNetherBrickSlabBlock;
	[BlockIdentifier.IronOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedWeatheredChiseledCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Element17]: Record<string, string | number | boolean>;
	[BlockIdentifier.StickyPistonArmCollision]: import("./blocks").StickyPistonArmCollisionBlock;
	[BlockIdentifier.Element51]: Record<string, string | number | boolean>;
	[BlockIdentifier.GrayStainedGlass]: Record<string, string | number | boolean>;
	[BlockIdentifier.ExposedCutCopperSlab]: import("./blocks").ExposedCutCopperSlabBlock;
	[BlockIdentifier.Element52]: Record<string, string | number | boolean>;
	[BlockIdentifier.WarpedStairs]: import("./blocks").WarpedStairsBlock;
	[BlockIdentifier.Bedrock]: import("./blocks").BedrockBlock;
	[BlockIdentifier.SmithingTable]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightBlock10]: import("./blocks").LightBlock10Block;
	[BlockIdentifier.TuffBrickSlab]: import("./blocks").TuffBrickSlabBlock;
	[BlockIdentifier.RoseBush]: import("./blocks").RoseBushBlock;
	[BlockIdentifier.GreenCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.PurpleCandleCake]: import("./blocks").PurpleCandleCakeBlock;
	[BlockIdentifier.PrismarineBrickSlab]: import("./blocks").PrismarineBrickSlabBlock;
	[BlockIdentifier.CyanConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.NetheriteBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.RedstoneBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedBlackstoneWall]: import("./blocks").PolishedBlackstoneWallBlock;
	[BlockIdentifier.QuartzPillar]: import("./blocks").QuartzPillarBlock;
	[BlockIdentifier.WaxedExposedCutCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.GildedBlackstone]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleHangingSign]: import("./blocks").JungleHangingSignBlock;
	[BlockIdentifier.BlueConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CherryWood]: import("./blocks").CherryWoodBlock;
	[BlockIdentifier.BirchSlab]: import("./blocks").BirchSlabBlock;
	[BlockIdentifier.EndStone]: Record<string, string | number | boolean>;
	[BlockIdentifier.CrimsonDoor]: import("./blocks").CrimsonDoorBlock;
	[BlockIdentifier.JungleSlab]: import("./blocks").JungleSlabBlock;
	[BlockIdentifier.WaxedOxidizedCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Glowstone]: Record<string, string | number | boolean>;
	[BlockIdentifier.StonePressurePlate]: import("./blocks").StonePressurePlateBlock;
	[BlockIdentifier.QuartzStairs]: import("./blocks").QuartzStairsBlock;
	[BlockIdentifier.WaxedExposedCutCopperStairs]: import("./blocks").WaxedExposedCutCopperStairsBlock;
	[BlockIdentifier.HardLimeStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.MudBrickSlab]: import("./blocks").MudBrickSlabBlock;
	[BlockIdentifier.CrackedDeepslateTiles]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Farmland]: import("./blocks").FarmlandBlock;
	[BlockIdentifier.DeadBrainCoralWallFan]: import("./blocks").DeadBrainCoralWallFanBlock;
	[BlockIdentifier.PinkCandle]: import("./blocks").PinkCandleBlock;
	[BlockIdentifier.NormalStoneDoubleSlab]: import("./blocks").NormalStoneDoubleSlabBlock;
	[BlockIdentifier.BrownCandle]: import("./blocks").BrownCandleBlock;
	[BlockIdentifier.LightBlock12]: import("./blocks").LightBlock12Block;
	[BlockIdentifier.Rail]: import("./blocks").RailBlock;
	[BlockIdentifier.SoulLantern]: import("./blocks").SoulLanternBlock;
	[BlockIdentifier.Carrots]: import("./blocks").CarrotsBlock;
	[BlockIdentifier.AcaciaTrapdoor]: import("./blocks").AcaciaTrapdoorBlock;
	[BlockIdentifier.StoneBricks]: import("./blocks").StoneBricksBlock;
	[BlockIdentifier.MossyCobblestoneStairs]: import("./blocks").MossyCobblestoneStairsBlock;
	[BlockIdentifier.HardMagentaStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PinkTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedWeatheredCopperDoor]: import("./blocks").WaxedWeatheredCopperDoorBlock;
	[BlockIdentifier.DarkPrismarine]: import("./blocks").DarkPrismarineBlock;
	[BlockIdentifier.InfestedCobblestone]: import("./blocks").InfestedCobblestoneBlock;
	[BlockIdentifier.BrainCoralWallFan]: import("./blocks").BrainCoralWallFanBlock;
	[BlockIdentifier.MangroveWood]: import("./blocks").MangroveWoodBlock;
	[BlockIdentifier.CraftingTable]: Record<string, string | number | boolean>;
	[BlockIdentifier.RedGlazedTerracotta]: import("./blocks").RedGlazedTerracottaBlock;
	[BlockIdentifier.DarkOakFenceGate]: import("./blocks").DarkOakFenceGateBlock;
	[BlockIdentifier.CherryButton]: import("./blocks").CherryButtonBlock;
	[BlockIdentifier.CrimsonNylium]: Record<string, string | number | boolean>;
	[BlockIdentifier.WarpedDoubleSlab]: import("./blocks").WarpedDoubleSlabBlock;
	[BlockIdentifier.StructureVoid]: import("./blocks").StructureVoidBlock;
	[BlockIdentifier.BambooFenceGate]: import("./blocks").BambooFenceGateBlock;
	[BlockIdentifier.PurpleConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.WhiteStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WaxedExposedCopperBulb]: import("./blocks").WaxedExposedCopperBulbBlock;
	[BlockIdentifier.BubbleCoral]: import("./blocks").BubbleCoralBlock;
	[BlockIdentifier.CoalOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedBlackstoneBrickSlab]: import("./blocks").PolishedBlackstoneBrickSlabBlock;
	[BlockIdentifier.NormalStoneSlab]: import("./blocks").NormalStoneSlabBlock;
	[BlockIdentifier.PurpleCandle]: import("./blocks").PurpleCandleBlock;
	[BlockIdentifier.Snow]: Record<string, string | number | boolean>;
	[BlockIdentifier.CalibratedSculkSensor]: import("./blocks").CalibratedSculkSensorBlock;
	[BlockIdentifier.YellowConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.OakSlab]: import("./blocks").OakSlabBlock;
	[BlockIdentifier.Sand]: import("./blocks").SandBlock;
	[BlockIdentifier.MangroveStandingSign]: import("./blocks").MangroveStandingSignBlock;
	[BlockIdentifier.Slime]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element117]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleStairs]: import("./blocks").JungleStairsBlock;
	[BlockIdentifier.MossyStoneBrickDoubleSlab]: import("./blocks").MossyStoneBrickDoubleSlabBlock;
	[BlockIdentifier.CutRedSandstoneDoubleSlab]: import("./blocks").CutRedSandstoneDoubleSlabBlock;
	[BlockIdentifier.AzaleaLeaves]: import("./blocks").AzaleaLeavesBlock;
	[BlockIdentifier.BambooDoubleSlab]: import("./blocks").BambooDoubleSlabBlock;
	[BlockIdentifier.ChiseledPolishedBlackstone]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.SmoothStoneSlab]: import("./blocks").SmoothStoneSlabBlock;
	[BlockIdentifier.InfestedChiseledStoneBricks]: import("./blocks").InfestedChiseledStoneBricksBlock;
	[BlockIdentifier.BrownConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PinkConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CrackedDeepslateBricks]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DeadTubeCoral]: import("./blocks").DeadTubeCoralBlock;
	[BlockIdentifier.AcaciaDoor]: import("./blocks").AcaciaDoorBlock;
	[BlockIdentifier.OrangeShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.NetherWartBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightBlueGlazedTerracotta]: import("./blocks").LightBlueGlazedTerracottaBlock;
	[BlockIdentifier.PrismarineSlab]: import("./blocks").PrismarineSlabBlock;
	[BlockIdentifier.PrismarineDoubleSlab]: import("./blocks").PrismarineDoubleSlabBlock;
	[BlockIdentifier.LightBlock11]: import("./blocks").LightBlock11Block;
	[BlockIdentifier.CherryDoor]: import("./blocks").CherryDoorBlock;
	[BlockIdentifier.WeatheredCutCopperStairs]: import("./blocks").WeatheredCutCopperStairsBlock;
	[BlockIdentifier.AcaciaLog]: import("./blocks").AcaciaLogBlock;
	[BlockIdentifier.FlowingLava]: import("./blocks").FlowingLavaBlock;
	[BlockIdentifier.WhiteTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.CrimsonTrapdoor]: import("./blocks").CrimsonTrapdoorBlock;
	[BlockIdentifier.BlueShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.Basalt]: import("./blocks").BasaltBlock;
	[BlockIdentifier.WaxedWeatheredCopperTrapdoor]: import("./blocks").WaxedWeatheredCopperTrapdoorBlock;
	[BlockIdentifier.HardCyanStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PolishedDiorite]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element13]: Record<string, string | number | boolean>;
	[BlockIdentifier.CyanGlazedTerracotta]: import("./blocks").CyanGlazedTerracottaBlock;
	[BlockIdentifier.LitRedstoneLamp]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardPurpleStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.YellowCandleCake]: import("./blocks").YellowCandleCakeBlock;
	[BlockIdentifier.StickyPiston]: import("./blocks").StickyPistonBlock;
	[BlockIdentifier.MediumAmethystBud]: import("./blocks").MediumAmethystBudBlock;
	[BlockIdentifier.BrownShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.PinkShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightBlueCandle]: import("./blocks").LightBlueCandleBlock;
	[BlockIdentifier.DeepslateTileStairs]: import("./blocks").DeepslateTileStairsBlock;
	[BlockIdentifier.SculkSensor]: import("./blocks").SculkSensorBlock;
	[BlockIdentifier.CopperBulb]: import("./blocks").CopperBulbBlock;
	[BlockIdentifier.Element6]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element97]: Record<string, string | number | boolean>;
	[BlockIdentifier.DioriteStairs]: import("./blocks").DioriteStairsBlock;
	[BlockIdentifier.SmoothStoneDoubleSlab]: import("./blocks").SmoothStoneDoubleSlabBlock;
	[BlockIdentifier.SpruceLeaves]: import("./blocks").SpruceLeavesBlock;
	[BlockIdentifier.RedStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.FrogSpawn]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element111]: Record<string, string | number | boolean>;
	[BlockIdentifier.CrimsonFenceGate]: import("./blocks").CrimsonFenceGateBlock;
	[BlockIdentifier.RedCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.SmoothSandstoneDoubleSlab]: import("./blocks").SmoothSandstoneDoubleSlabBlock;
	[BlockIdentifier.RedShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.DirtWithRoots]: Record<string, string | number | boolean>;
	[BlockIdentifier.StrippedCherryLog]: import("./blocks").StrippedCherryLogBlock;
	[BlockIdentifier.HornCoralWallFan]: import("./blocks").HornCoralWallFanBlock;
	[BlockIdentifier.CopperDoor]: import("./blocks").CopperDoorBlock;
	[BlockIdentifier.CrimsonButton]: import("./blocks").CrimsonButtonBlock;
	[BlockIdentifier.MagentaConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PrismarineStairs]: import("./blocks").PrismarineStairsBlock;
	[BlockIdentifier.IronDoor]: import("./blocks").IronDoorBlock;
	[BlockIdentifier.MangroveTrapdoor]: import("./blocks").MangroveTrapdoorBlock;
	[BlockIdentifier.DaylightDetectorInverted]: import("./blocks").DaylightDetectorInvertedBlock;
	[BlockIdentifier.JunglePlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.ChorusFlower]: import("./blocks").ChorusFlowerBlock;
	[BlockIdentifier.TorchflowerCrop]: import("./blocks").TorchflowerCropBlock;
	[BlockIdentifier.CrackedNetherBricks]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Pumpkin]: import("./blocks").PumpkinBlock;
	[BlockIdentifier.SmoothStone]: Record<string, string | number | boolean>;
	[BlockIdentifier.GraniteSlab]: import("./blocks").GraniteSlabBlock;
	[BlockIdentifier.LimeConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedWeatheredCutCopperSlab]: import("./blocks").WaxedWeatheredCutCopperSlabBlock;
	[BlockIdentifier.RedMushroom]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardYellowStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.MagentaTerracotta]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BlackCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.ExposedCutCopperStairs]: import("./blocks").ExposedCutCopperStairsBlock;
	[BlockIdentifier.MangroveStairs]: import("./blocks").MangroveStairsBlock;
	[BlockIdentifier.PolishedDioriteSlab]: import("./blocks").PolishedDioriteSlabBlock;
	[BlockIdentifier.RedSandstoneStairs]: import("./blocks").RedSandstoneStairsBlock;
	[BlockIdentifier.LightBlueConcrete]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.MangroveFenceGate]: import("./blocks").MangroveFenceGateBlock;
	[BlockIdentifier.BubbleColumn]: import("./blocks").BubbleColumnBlock;
	[BlockIdentifier.Sunflower]: import("./blocks").SunflowerBlock;
	[BlockIdentifier.Allow]: Record<string, string | number | boolean>;
	[BlockIdentifier.GrayConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BambooHangingSign]: import("./blocks").BambooHangingSignBlock;
	[BlockIdentifier.WitherRose]: Record<string, string | number | boolean>;
	[BlockIdentifier.CopperBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchDoubleSlab]: import("./blocks").BirchDoubleSlabBlock;
	[BlockIdentifier.WaxedWeatheredDoubleCutCopperSlab]: import("./blocks").WaxedWeatheredDoubleCutCopperSlabBlock;
	[BlockIdentifier.PolishedBlackstoneBricks]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CutCopper]: Record<string, string | number | boolean>;
	[BlockIdentifier.FrostedIce]: import("./blocks").FrostedIceBlock;
	[BlockIdentifier.SpruceDoor]: import("./blocks").SpruceDoorBlock;
	[BlockIdentifier.ChiseledSandstone]: import("./blocks").ChiseledSandstoneBlock;
	[BlockIdentifier.ChippedAnvil]: import("./blocks").ChippedAnvilBlock;
	[BlockIdentifier.WarpedTrapdoor]: import("./blocks").WarpedTrapdoorBlock;
	[BlockIdentifier.OrangeConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.FlowingWater]: import("./blocks").FlowingWaterBlock;
	[BlockIdentifier.BrickBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardGlass]: Record<string, string | number | boolean>;
	[BlockIdentifier.CaveVines]: import("./blocks").CaveVinesBlock;
	[BlockIdentifier.MagentaStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Element62]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightBlueCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.OakHangingSign]: import("./blocks").OakHangingSignBlock;
	[BlockIdentifier.StrippedDarkOakWood]: import("./blocks").StrippedDarkOakWoodBlock;
	[BlockIdentifier.WhiteStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.OakWood]: import("./blocks").OakWoodBlock;
	[BlockIdentifier.WaxedExposedDoubleCutCopperSlab]: import("./blocks").WaxedExposedDoubleCutCopperSlabBlock;
	[BlockIdentifier.WaxedOxidizedCopperTrapdoor]: import("./blocks").WaxedOxidizedCopperTrapdoorBlock;
	[BlockIdentifier.Jukebox]: Record<string, string | number | boolean>;
	[BlockIdentifier.StrippedCherryWood]: import("./blocks").StrippedCherryWoodBlock;
	[BlockIdentifier.AcaciaPressurePlate]: import("./blocks").AcaciaPressurePlateBlock;
	[BlockIdentifier.SmoothRedSandstoneSlab]: import("./blocks").SmoothRedSandstoneSlabBlock;
	[BlockIdentifier.Jigsaw]: import("./blocks").JigsawBlock;
	[BlockIdentifier.BorderBlock]: import("./blocks").BorderBlockBlock;
	[BlockIdentifier.Shroomlight]: Record<string, string | number | boolean>;
	[BlockIdentifier.YellowCandle]: import("./blocks").YellowCandleBlock;
	[BlockIdentifier.DarkOakStairs]: import("./blocks").DarkOakStairsBlock;
	[BlockIdentifier.DeepslateTileWall]: import("./blocks").DeepslateTileWallBlock;
	[BlockIdentifier.GlassPane]: Record<string, string | number | boolean>;
	[BlockIdentifier.ChiseledDeepslate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CutCopperSlab]: import("./blocks").CutCopperSlabBlock;
	[BlockIdentifier.InfestedStoneBricks]: import("./blocks").InfestedStoneBricksBlock;
	[BlockIdentifier.BambooTrapdoor]: import("./blocks").BambooTrapdoorBlock;
	[BlockIdentifier.OxidizedChiseledCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DarkOakTrapdoor]: import("./blocks").DarkOakTrapdoorBlock;
	[BlockIdentifier.MangroveWallSign]: import("./blocks").MangroveWallSignBlock;
	[BlockIdentifier.Beetroot]: import("./blocks").BeetrootBlock;
	[BlockIdentifier.RawCopperBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.HornCoralBlock]: import("./blocks").HornCoralBlockBlock;
	[BlockIdentifier.Skull]: import("./blocks").SkullBlock;
	[BlockIdentifier.LightGrayCandleCake]: import("./blocks").LightGrayCandleCakeBlock;
	[BlockIdentifier.Element95]: Record<string, string | number | boolean>;
	[BlockIdentifier.WhiteCandle]: import("./blocks").WhiteCandleBlock;
	[BlockIdentifier.GoldenRail]: import("./blocks").GoldenRailBlock;
	[BlockIdentifier.LitFurnace]: import("./blocks").LitFurnaceBlock;
	[BlockIdentifier.CyanWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.PetrifiedOakDoubleSlab]: import("./blocks").PetrifiedOakDoubleSlabBlock;
	[BlockIdentifier.StructureBlock]: import("./blocks").StructureBlockBlock;
	[BlockIdentifier.TintedGlass]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeprecatedAnvil]: import("./blocks").DeprecatedAnvilBlock;
	[BlockIdentifier.GrayShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.FireCoralWallFan]: import("./blocks").FireCoralWallFanBlock;
	[BlockIdentifier.JungleFenceGate]: import("./blocks").JungleFenceGateBlock;
	[BlockIdentifier.ExposedCopperGrate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WaxedCopperGrate]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeadBrainCoral]: import("./blocks").DeadBrainCoralBlock;
	[BlockIdentifier.JungleTrapdoor]: import("./blocks").JungleTrapdoorBlock;
	[BlockIdentifier.SpruceWallSign]: import("./blocks").SpruceWallSignBlock;
	[BlockIdentifier.CoalBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.WarpedFenceGate]: import("./blocks").WarpedFenceGateBlock;
	[BlockIdentifier.Composter]: import("./blocks").ComposterBlock;
	[BlockIdentifier.Element44]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedDoubleCutCopperSlab]: import("./blocks").WaxedDoubleCutCopperSlabBlock;
	[BlockIdentifier.WaxedExposedCopperDoor]: import("./blocks").WaxedExposedCopperDoorBlock;
	[BlockIdentifier.BlueGlazedTerracotta]: import("./blocks").BlueGlazedTerracottaBlock;
	[BlockIdentifier.BlueWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.Clay]: Record<string, string | number | boolean>;
	[BlockIdentifier.WeepingVines]: import("./blocks").WeepingVinesBlock;
	[BlockIdentifier.ChorusPlant]: Record<string, string | number | boolean>;
	[BlockIdentifier.MudBrickStairs]: import("./blocks").MudBrickStairsBlock;
	[BlockIdentifier.SmoothRedSandstoneStairs]: import("./blocks").SmoothRedSandstoneStairsBlock;
	[BlockIdentifier.Element100]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element103]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element105]: Record<string, string | number | boolean>;
	[BlockIdentifier.CrimsonPressurePlate]: import("./blocks").CrimsonPressurePlateBlock;
	[BlockIdentifier.Element106]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element107]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardGrayStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Element108]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element109]: Record<string, string | number | boolean>;
	[BlockIdentifier.LightGrayShulkerBox]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Element112]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element110]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element116]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element114]: Record<string, string | number | boolean>;
	[BlockIdentifier.WhiteGlazedTerracotta]: import("./blocks").WhiteGlazedTerracottaBlock;
	[BlockIdentifier.StrippedWarpedHyphae]: import("./blocks").StrippedWarpedHyphaeBlock;
	[BlockIdentifier.Element50]: Record<string, string | number | boolean>;
	[BlockIdentifier.PumpkinStem]: import("./blocks").PumpkinStemBlock;
	[BlockIdentifier.Lever]: import("./blocks").LeverBlock;
	[BlockIdentifier.MovingBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.TrappedChest]: import("./blocks").TrappedChestBlock;
	[BlockIdentifier.LightGrayConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BrainCoralBlock]: import("./blocks").BrainCoralBlockBlock;
	[BlockIdentifier.StandingSign]: import("./blocks").StandingSignBlock;
	[BlockIdentifier.PurpleConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BambooPlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.CommandBlock]: import("./blocks").CommandBlockBlock;
	[BlockIdentifier.TwistingVines]: import("./blocks").TwistingVinesBlock;
	[BlockIdentifier.AcaciaDoubleSlab]: import("./blocks").AcaciaDoubleSlabBlock;
	[BlockIdentifier.PolishedAndesiteDoubleSlab]: import("./blocks").PolishedAndesiteDoubleSlabBlock;
	[BlockIdentifier.Magma]: Record<string, string | number | boolean>;
	[BlockIdentifier.Dirt]: Record<string, string | number | boolean>;
	[BlockIdentifier.Reeds]: import("./blocks").ReedsBlock;
	[BlockIdentifier.Deny]: Record<string, string | number | boolean>;
	[BlockIdentifier.BeeNest]: import("./blocks").BeeNestBlock;
	[BlockIdentifier.Campfire]: import("./blocks").CampfireBlock;
	[BlockIdentifier.SoulSoil]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element8]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element28]: Record<string, string | number | boolean>;
	[BlockIdentifier.DarkOakPressurePlate]: import("./blocks").DarkOakPressurePlateBlock;
	[BlockIdentifier.SoulSand]: Record<string, string | number | boolean>;
	[BlockIdentifier.CobbledDeepslateDoubleSlab]: import("./blocks").CobbledDeepslateDoubleSlabBlock;
	[BlockIdentifier.SpruceHangingSign]: import("./blocks").SpruceHangingSignBlock;
	[BlockIdentifier.ReinforcedDeepslate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.EndRod]: import("./blocks").EndRodBlock;
	[BlockIdentifier.FletchingTable]: Record<string, string | number | boolean>;
	[BlockIdentifier.CherryLeaves]: import("./blocks").CherryLeavesBlock;
	[BlockIdentifier.BlackGlazedTerracotta]: import("./blocks").BlackGlazedTerracottaBlock;
	[BlockIdentifier.StrippedAcaciaLog]: import("./blocks").StrippedAcaciaLogBlock;
	[BlockIdentifier.SnifferEgg]: import("./blocks").SnifferEggBlock;
	[BlockIdentifier.WarpedFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.CaveVinesBodyWithBerries]: import("./blocks").CaveVinesBodyWithBerriesBlock;
	[BlockIdentifier.CherryStandingSign]: import("./blocks").CherryStandingSignBlock;
	[BlockIdentifier.MangroveHangingSign]: import("./blocks").MangroveHangingSignBlock;
	[BlockIdentifier.WaxedExposedCopperTrapdoor]: import("./blocks").WaxedExposedCopperTrapdoorBlock;
	[BlockIdentifier.MossyStoneBrickStairs]: import("./blocks").MossyStoneBrickStairsBlock;
	[BlockIdentifier.CrimsonStem]: import("./blocks").CrimsonStemBlock;
	[BlockIdentifier.ColoredTorchRg]: import("./blocks").ColoredTorchRgBlock;
	[BlockIdentifier.TuffBrickDoubleSlab]: import("./blocks").TuffBrickDoubleSlabBlock;
	[BlockIdentifier.Vault]: import("./blocks").VaultBlock;
	[BlockIdentifier.AzaleaLeavesFlowered]: import("./blocks").AzaleaLeavesFloweredBlock;
	[BlockIdentifier.Element18]: Record<string, string | number | boolean>;
	[BlockIdentifier.CrimsonSlab]: import("./blocks").CrimsonSlabBlock;
	[BlockIdentifier.WarpedHyphae]: import("./blocks").WarpedHyphaeBlock;
	[BlockIdentifier.OxeyeDaisy]: import("./blocks").OxeyeDaisyBlock;
	[BlockIdentifier.BambooButton]: import("./blocks").BambooButtonBlock;
	[BlockIdentifier.WarpedWartBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.TuffStairs]: import("./blocks").TuffStairsBlock;
	[BlockIdentifier.YellowCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.BlackStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WaxedOxidizedCopperDoor]: import("./blocks").WaxedOxidizedCopperDoorBlock;
	[BlockIdentifier.GrassBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.TripwireHook]: import("./blocks").TripwireHookBlock;
	[BlockIdentifier.HardBlackStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.StrippedBirchLog]: import("./blocks").StrippedBirchLogBlock;
	[BlockIdentifier.RedTulip]: import("./blocks").RedTulipBlock;
	[BlockIdentifier.CutSandstone]: import("./blocks").CutSandstoneBlock;
	[BlockIdentifier.LimeWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.BlueCandleCake]: import("./blocks").BlueCandleCakeBlock;
	[BlockIdentifier.LargeFern]: import("./blocks").LargeFernBlock;
	[BlockIdentifier.SweetBerryBush]: import("./blocks").SweetBerryBushBlock;
	[BlockIdentifier.PolishedBlackstoneSlab]: import("./blocks").PolishedBlackstoneSlabBlock;
	[BlockIdentifier.BlackShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleSapling]: import("./blocks").JungleSaplingBlock;
	[BlockIdentifier.BlueConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleStandingSign]: import("./blocks").JungleStandingSignBlock;
	[BlockIdentifier.Web]: Record<string, string | number | boolean>;
	[BlockIdentifier.WeatheredCutCopperSlab]: import("./blocks").WeatheredCutCopperSlabBlock;
	[BlockIdentifier.Cocoa]: import("./blocks").CocoaBlock;
	[BlockIdentifier.DarkOakLeaves]: import("./blocks").DarkOakLeavesBlock;
	[BlockIdentifier.OrangeTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.Fire]: import("./blocks").FireBlock;
	[BlockIdentifier.PurpurDoubleSlab]: import("./blocks").PurpurDoubleSlabBlock;
	[BlockIdentifier.ExposedChiseledCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.InfestedStone]: import("./blocks").InfestedStoneBlock;
	[BlockIdentifier.EndPortalFrame]: import("./blocks").EndPortalFrameBlock;
	[BlockIdentifier.Prismarine]: import("./blocks").PrismarineBlock;
	[BlockIdentifier.MagentaCandleCake]: import("./blocks").MagentaCandleCakeBlock;
	[BlockIdentifier.DeepslateGoldOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardOrangeStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Glass]: Record<string, string | number | boolean>;
	[BlockIdentifier.MossBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.NetherBrickDoubleSlab]: import("./blocks").NetherBrickDoubleSlabBlock;
	[BlockIdentifier.ExposedCutCopper]: Record<string, string | number | boolean>;
	[BlockIdentifier.PrismarineBrickDoubleSlab]: import("./blocks").PrismarineBrickDoubleSlabBlock;
	[BlockIdentifier.Bookshelf]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedWeatheredCutCopperStairs]: import("./blocks").WaxedWeatheredCutCopperStairsBlock;
	[BlockIdentifier.MangroveRoots]: Record<string, string | number | boolean>;
	[BlockIdentifier.AcaciaStairs]: import("./blocks").AcaciaStairsBlock;
	[BlockIdentifier.PolishedAndesiteStairs]: import("./blocks").PolishedAndesiteStairsBlock;
	[BlockIdentifier.CherrySlab]: import("./blocks").CherrySlabBlock;
	[BlockIdentifier.SmoothRedSandstoneDoubleSlab]: import("./blocks").SmoothRedSandstoneDoubleSlabBlock;
	[BlockIdentifier.LitBlastFurnace]: import("./blocks").LitBlastFurnaceBlock;
	[BlockIdentifier.Element11]: Record<string, string | number | boolean>;
	[BlockIdentifier.Sculk]: Record<string, string | number | boolean>;
	[BlockIdentifier.TuffBrickStairs]: import("./blocks").TuffBrickStairsBlock;
	[BlockIdentifier.ChemistryTable]: import("./blocks").ChemistryTableBlock;
	[BlockIdentifier.DeadFireCoral]: import("./blocks").DeadFireCoralBlock;
	[BlockIdentifier.StoneBrickSlab]: import("./blocks").StoneBrickSlabBlock;
	[BlockIdentifier.StrippedSpruceLog]: import("./blocks").StrippedSpruceLogBlock;
	[BlockIdentifier.WaxedOxidizedCopperBulb]: import("./blocks").WaxedOxidizedCopperBulbBlock;
	[BlockIdentifier.DeepslateBrickStairs]: import("./blocks").DeepslateBrickStairsBlock;
	[BlockIdentifier.WarpedNylium]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeepslateEmeraldOre]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.StrippedCrimsonStem]: import("./blocks").StrippedCrimsonStemBlock;
	[BlockIdentifier.AcaciaSapling]: import("./blocks").AcaciaSaplingBlock;
	[BlockIdentifier.StonecutterBlock]: import("./blocks").StonecutterBlockBlock;
	[BlockIdentifier.AndesiteSlab]: import("./blocks").AndesiteSlabBlock;
	[BlockIdentifier.CyanShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.UnpoweredComparator]: import("./blocks").UnpoweredComparatorBlock;
	[BlockIdentifier.LimeCandle]: import("./blocks").LimeCandleBlock;
	[BlockIdentifier.Target]: Record<string, string | number | boolean>;
	[BlockIdentifier.WoodenButton]: import("./blocks").WoodenButtonBlock;
	[BlockIdentifier.MangroveDoor]: import("./blocks").MangroveDoorBlock;
	[BlockIdentifier.EndStoneBrickDoubleSlab]: import("./blocks").EndStoneBrickDoubleSlabBlock;
	[BlockIdentifier.WeatheredCopperDoor]: import("./blocks").WeatheredCopperDoorBlock;
	[BlockIdentifier.PearlescentFroglight]: import("./blocks").PearlescentFroglightBlock;
	[BlockIdentifier.TallGrass]: import("./blocks").TallGrassBlock;
	[BlockIdentifier.LightBlock15]: import("./blocks").LightBlock15Block;
	[BlockIdentifier.Element64]: Record<string, string | number | boolean>;
	[BlockIdentifier.NetherSprouts]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element92]: Record<string, string | number | boolean>;
	[BlockIdentifier.CyanStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DeadHornCoralBlock]: import("./blocks").DeadHornCoralBlockBlock;
	[BlockIdentifier.Element12]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeadHornCoralFan]: import("./blocks").DeadHornCoralFanBlock;
	[BlockIdentifier.Furnace]: import("./blocks").FurnaceBlock;
	[BlockIdentifier.WarpedSlab]: import("./blocks").WarpedSlabBlock;
	[BlockIdentifier.Netherrack]: Record<string, string | number | boolean>;
	[BlockIdentifier.WarpedStem]: import("./blocks").WarpedStemBlock;
	[BlockIdentifier.Chain]: import("./blocks").ChainBlock;
	[BlockIdentifier.HornCoralFan]: import("./blocks").HornCoralFanBlock;
	[BlockIdentifier.GreenShulkerBox]: Record<string, string | number | boolean>;
	[BlockIdentifier.BrickStairs]: import("./blocks").BrickStairsBlock;
	[BlockIdentifier.PurpleCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.FireCoralFan]: import("./blocks").FireCoralFanBlock;
	[BlockIdentifier.Element69]: Record<string, string | number | boolean>;
	[BlockIdentifier.SpruceTrapdoor]: import("./blocks").SpruceTrapdoorBlock;
	[BlockIdentifier.PurpleGlazedTerracotta]: import("./blocks").PurpleGlazedTerracottaBlock;
	[BlockIdentifier.ChainCommandBlock]: import("./blocks").ChainCommandBlockBlock;
	[BlockIdentifier.SpruceFenceGate]: import("./blocks").SpruceFenceGateBlock;
	[BlockIdentifier.RedNetherBrickStairs]: import("./blocks").RedNetherBrickStairsBlock;
	[BlockIdentifier.GreenGlazedTerracotta]: import("./blocks").GreenGlazedTerracottaBlock;
	[BlockIdentifier.DeepslateRedstoneOre]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DeadBrainCoralBlock]: import("./blocks").DeadBrainCoralBlockBlock;
	[BlockIdentifier.MangroveFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchTrapdoor]: import("./blocks").BirchTrapdoorBlock;
	[BlockIdentifier.TuffBricks]: Record<string, string | number | boolean>;
	[BlockIdentifier.Mud]: Record<string, string | number | boolean>;
	[BlockIdentifier.Ice]: Record<string, string | number | boolean>;
	[BlockIdentifier.Air]: Record<string, string | number | boolean>;
	[BlockIdentifier.Bed]: import("./blocks").BedBlock;
	[BlockIdentifier.LightBlueWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.BlackConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.Tnt]: import("./blocks").TntBlock;
	[BlockIdentifier.DeadTubeCoralFan]: import("./blocks").DeadTubeCoralFanBlock;
	[BlockIdentifier.PolishedDioriteStairs]: import("./blocks").PolishedDioriteStairsBlock;
	[BlockIdentifier.Element83]: Record<string, string | number | boolean>;
	[BlockIdentifier.OrangeConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.Netherreactor]: Record<string, string | number | boolean>;
	[BlockIdentifier.LimeCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeadFireCoralFan]: import("./blocks").DeadFireCoralFanBlock;
	[BlockIdentifier.DecoratedPot]: import("./blocks").DecoratedPotBlock;
	[BlockIdentifier.GraniteDoubleSlab]: import("./blocks").GraniteDoubleSlabBlock;
	[BlockIdentifier.EnchantingTable]: Record<string, string | number | boolean>;
	[BlockIdentifier.BubbleCoralWallFan]: import("./blocks").BubbleCoralWallFanBlock;
	[BlockIdentifier.OrangeTulip]: import("./blocks").OrangeTulipBlock;
	[BlockIdentifier.Azalea]: Record<string, string | number | boolean>;
	[BlockIdentifier.Bell]: import("./blocks").BellBlock;
	[BlockIdentifier.MudBricks]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchWallSign]: import("./blocks").BirchWallSignBlock;
	[BlockIdentifier.BambooWallSign]: import("./blocks").BambooWallSignBlock;
	[BlockIdentifier.AcaciaWood]: import("./blocks").AcaciaWoodBlock;
	[BlockIdentifier.Hopper]: import("./blocks").HopperBlock;
	[BlockIdentifier.HardRedStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.PrismarineBricks]: import("./blocks").PrismarineBricksBlock;
	[BlockIdentifier.Lectern]: import("./blocks").LecternBlock;
	[BlockIdentifier.AcaciaButton]: import("./blocks").AcaciaButtonBlock;
	[BlockIdentifier.StandingBanner]: import("./blocks").StandingBannerBlock;
	[BlockIdentifier.SeaLantern]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedOxidizedDoubleCutCopperSlab]: import("./blocks").WaxedOxidizedDoubleCutCopperSlabBlock;
	[BlockIdentifier.LightBlueShulkerBox]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.MangrovePropagule]: import("./blocks").MangrovePropaguleBlock;
	[BlockIdentifier.PolishedDioriteDoubleSlab]: import("./blocks").PolishedDioriteDoubleSlabBlock;
	[BlockIdentifier.MossyCobblestoneDoubleSlab]: import("./blocks").MossyCobblestoneDoubleSlabBlock;
	[BlockIdentifier.BirchStairs]: import("./blocks").BirchStairsBlock;
	[BlockIdentifier.SpruceSlab]: import("./blocks").SpruceSlabBlock;
	[BlockIdentifier.BlackstoneStairs]: import("./blocks").BlackstoneStairsBlock;
	[BlockIdentifier.BlueIce]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardRedStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Lantern]: import("./blocks").LanternBlock;
	[BlockIdentifier.DarkOakFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.BirchDoor]: import("./blocks").BirchDoorBlock;
	[BlockIdentifier.DeepslateLapisOre]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CrimsonHangingSign]: import("./blocks").CrimsonHangingSignBlock;
	[BlockIdentifier.DeepslateCoalOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.WeatheredCutCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BambooStandingSign]: import("./blocks").BambooStandingSignBlock;
	[BlockIdentifier.StrippedMangroveLog]: import("./blocks").StrippedMangroveLogBlock;
	[BlockIdentifier.PolishedTuff]: Record<string, string | number | boolean>;
	[BlockIdentifier.MagentaStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WeatheredCopperBulb]: import("./blocks").WeatheredCopperBulbBlock;
	[BlockIdentifier.HardWhiteStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.HardCyanStainedGlassPane]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.ChiseledNetherBricks]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WarpedButton]: import("./blocks").WarpedButtonBlock;
	[BlockIdentifier.RedConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DeadBubbleCoral]: import("./blocks").DeadBubbleCoralBlock;
	[BlockIdentifier.CherrySapling]: import("./blocks").CherrySaplingBlock;
	[BlockIdentifier.CherryLog]: import("./blocks").CherryLogBlock;
	[BlockIdentifier.PolishedTuffStairs]: import("./blocks").PolishedTuffStairsBlock;
	[BlockIdentifier.DragonEgg]: Record<string, string | number | boolean>;
	[BlockIdentifier.NetherBrick]: Record<string, string | number | boolean>;
	[BlockIdentifier.DeepslateIronOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element3]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element2]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element5]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element4]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element7]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element9]: Record<string, string | number | boolean>;
	[BlockIdentifier.Camera]: Record<string, string | number | boolean>;
	[BlockIdentifier.WaxedCutCopper]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element47]: Record<string, string | number | boolean>;
	[BlockIdentifier.CobbledDeepslateSlab]: import("./blocks").CobbledDeepslateSlabBlock;
	[BlockIdentifier.Lilac]: import("./blocks").LilacBlock;
	[BlockIdentifier.CrimsonStandingSign]: import("./blocks").CrimsonStandingSignBlock;
	[BlockIdentifier.EmeraldOre]: Record<string, string | number | boolean>;
	[BlockIdentifier.BrownMushroomBlock]: import("./blocks").BrownMushroomBlockBlock;
	[BlockIdentifier.PetrifiedOakSlab]: import("./blocks").PetrifiedOakSlabBlock;
	[BlockIdentifier.CarvedPumpkin]: import("./blocks").CarvedPumpkinBlock;
	[BlockIdentifier.Dropper]: import("./blocks").DropperBlock;
	[BlockIdentifier.Candle]: import("./blocks").CandleBlock;
	[BlockIdentifier.PolishedAndesiteSlab]: import("./blocks").PolishedAndesiteSlabBlock;
	[BlockIdentifier.AcaciaSlab]: import("./blocks").AcaciaSlabBlock;
	[BlockIdentifier.CobbledDeepslateWall]: import("./blocks").CobbledDeepslateWallBlock;
	[BlockIdentifier.PointedDripstone]: import("./blocks").PointedDripstoneBlock;
	[BlockIdentifier.CutRedSandstoneSlab]: import("./blocks").CutRedSandstoneSlabBlock;
	[BlockIdentifier.ChiseledTuffBricks]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.ChemicalHeat]: Record<string, string | number | boolean>;
	[BlockIdentifier.TripWire]: import("./blocks").TripWireBlock;
	[BlockIdentifier.CaveVinesHeadWithBerries]: import("./blocks").CaveVinesHeadWithBerriesBlock;
	[BlockIdentifier.ChiseledRedSandstone]: import("./blocks").ChiseledRedSandstoneBlock;
	[BlockIdentifier.BrickSlab]: import("./blocks").BrickSlabBlock;
	[BlockIdentifier.BrewingStand]: import("./blocks").BrewingStandBlock;
	[BlockIdentifier.BambooSapling]: import("./blocks").BambooSaplingBlock;
	[BlockIdentifier.SmoothQuartzSlab]: import("./blocks").SmoothQuartzSlabBlock;
	[BlockIdentifier.WhiteCandleCake]: import("./blocks").WhiteCandleCakeBlock;
	[BlockIdentifier.EndPortal]: Record<string, string | number | boolean>;
	[BlockIdentifier.JungleDoubleSlab]: import("./blocks").JungleDoubleSlabBlock;
	[BlockIdentifier.SpruceWood]: import("./blocks").SpruceWoodBlock;
	[BlockIdentifier.Blackstone]: Record<string, string | number | boolean>;
	[BlockIdentifier.LitDeepslateRedstoneOre]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.Element10]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element14]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element15]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element36]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element37]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element34]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element35]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element32]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element33]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element31]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element38]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element29]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element21]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element20]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element23]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element22]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element25]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element24]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element27]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element26]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element59]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element54]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element55]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element56]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element57]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element53]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element49]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element48]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element45]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element43]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element42]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element41]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element40]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element72]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element70]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element71]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element76]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element75]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element78]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element79]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element65]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element67]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedDeepslateWall]: import("./blocks").PolishedDeepslateWallBlock;
	[BlockIdentifier.Element66]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element61]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element60]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element63]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element98]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element90]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element91]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element94]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element96]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element88]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element82]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element81]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element80]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element87]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element86]: Record<string, string | number | boolean>;
	[BlockIdentifier.Element84]: Record<string, string | number | boolean>;
	[BlockIdentifier.LitSmoker]: import("./blocks").LitSmokerBlock;
	[BlockIdentifier.SmoothQuartzStairs]: import("./blocks").SmoothQuartzStairsBlock;
	[BlockIdentifier.LightGrayCarpet]: Record<string, string | number | boolean>;
	[BlockIdentifier.PurpurBlock]: import("./blocks").PurpurBlockBlock;
	[BlockIdentifier.CherryWallSign]: import("./blocks").CherryWallSignBlock;
	[BlockIdentifier.CyanCandle]: import("./blocks").CyanCandleBlock;
	[BlockIdentifier.RepeatingCommandBlock]: import("./blocks").RepeatingCommandBlockBlock;
	[BlockIdentifier.CrimsonFungus]: Record<string, string | number | boolean>;
	[BlockIdentifier.CherryPlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.PolishedDeepslate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.TuffDoubleSlab]: import("./blocks").TuffDoubleSlabBlock;
	[BlockIdentifier.PurpurStairs]: import("./blocks").PurpurStairsBlock;
	[BlockIdentifier.TubeCoral]: import("./blocks").TubeCoralBlock;
	[BlockIdentifier.WaxedCopperDoor]: import("./blocks").WaxedCopperDoorBlock;
	[BlockIdentifier.Portal]: import("./blocks").PortalBlock;
	[BlockIdentifier.Peony]: import("./blocks").PeonyBlock;
	[BlockIdentifier.Crafter]: import("./blocks").CrafterBlock;
	[BlockIdentifier.SprucePlanks]: Record<string, string | number | boolean>;
	[BlockIdentifier.AmethystCluster]: import("./blocks").AmethystClusterBlock;
	[BlockIdentifier.WaxedChiseledCopper]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.WaxedCutCopperSlab]: import("./blocks").WaxedCutCopperSlabBlock;
	[BlockIdentifier.DriedKelpBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.HardLightGrayStainedGlass]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.CrimsonFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.ChiseledTuff]: Record<string, string | number | boolean>;
	[BlockIdentifier.LimeConcretePowder]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.BirchFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.TurtleEgg]: import("./blocks").TurtleEggBlock;
	[BlockIdentifier.BrownTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.CobblestoneDoubleSlab]: import("./blocks").CobblestoneDoubleSlabBlock;
	[BlockIdentifier.DeepslateDiamondOre]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.LightGrayWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.SoulCampfire]: import("./blocks").SoulCampfireBlock;
	[BlockIdentifier.WoodenPressurePlate]: import("./blocks").WoodenPressurePlateBlock;
	[BlockIdentifier.WaxedOxidizedCopperGrate]: Record<
		string,
		string | number | boolean
	>;
	[BlockIdentifier.DamagedAnvil]: import("./blocks").DamagedAnvilBlock;
	[BlockIdentifier.WhiteConcrete]: Record<string, string | number | boolean>;
	[BlockIdentifier.AcaciaFence]: Record<string, string | number | boolean>;
	[BlockIdentifier.GrassPath]: Record<string, string | number | boolean>;
	[BlockIdentifier.OrangeCandleCake]: import("./blocks").OrangeCandleCakeBlock;
	[BlockIdentifier.WeatheredCopper]: Record<string, string | number | boolean>;
	[BlockIdentifier.LimeTerracotta]: Record<string, string | number | boolean>;
	[BlockIdentifier.CherryFenceGate]: import("./blocks").CherryFenceGateBlock;
	[BlockIdentifier.GrayGlazedTerracotta]: import("./blocks").GrayGlazedTerracottaBlock;
	[BlockIdentifier.Lodestone]: Record<string, string | number | boolean>;
	[BlockIdentifier.BambooMosaic]: Record<string, string | number | boolean>;
	[BlockIdentifier.PurpleWool]: Record<string, string | number | boolean>;
	[BlockIdentifier.IronBlock]: Record<string, string | number | boolean>;
	[BlockIdentifier.CartographyTable]: Record<string, string | number | boolean>;
	[BlockIdentifier.Dandelion]: Record<string, string | number | boolean>;
}
