// WARNING, DO NOT EDIT!
// This file is automatically generated on start up.

export type VaultState = "inactive" | "active" | "unlocking" | "ejecting";
export type Orientation =
	| "down_east"
	| "down_north"
	| "down_south"
	| "down_west"
	| "up_east"
	| "up_north"
	| "up_south"
	| "up_west"
	| "west_up"
	| "east_up"
	| "north_up"
	| "south_up";
export type BigDripleafTilt =
	| "none"
	| "unstable"
	| "partial_tilt"
	| "full_tilt";
export type DripstoneThickness =
	| "tip"
	| "frustum"
	| "middle"
	| "base"
	| "merge";
export type WallConnectionTypeWest = "none" | "short" | "tall";
export type WallConnectionTypeSouth = "none" | "short" | "tall";
export type WallConnectionTypeEast = "none" | "short" | "tall";
export type WallConnectionTypeNorth = "none" | "short" | "tall";
export type PillarAxis = "y" | "x" | "z";
export type LeverDirection =
	| "down_east_west"
	| "east"
	| "west"
	| "south"
	| "north"
	| "up_north_south"
	| "up_east_west"
	| "down_north_south";
export type StructureBlockType =
	| "data"
	| "save"
	| "load"
	| "corner"
	| "invalid"
	| "export";
export type StructureVoidType = "void" | "air";
export type Attachment = "standing" | "hanging" | "side" | "multiple";
export type CauldronLiquid = "water" | "lava" | "powder_snow";
export type CoralColor = "blue" | "pink" | "purple" | "red" | "yellow";
export type SeaGrassType = "default" | "double_top" | "double_bot";
export type ChemistryTableType =
	| "compound_creator"
	| "material_reducer"
	| "element_constructor"
	| "lab_table";
export type DoublePlantType =
	| "sunflower"
	| "syringa"
	| "grass"
	| "fern"
	| "rose"
	| "paeonia";
export type PrismarineBlockType = "default" | "dark" | "bricks";
export type WallBlockType =
	| "cobblestone"
	| "mossy_cobblestone"
	| "granite"
	| "diorite"
	| "andesite"
	| "sandstone"
	| "brick"
	| "stone_brick"
	| "mossy_stone_brick"
	| "nether_brick"
	| "end_brick"
	| "prismarine"
	| "red_sandstone"
	| "red_nether_brick";
export type StoneBrickType =
	| "default"
	| "mossy"
	| "cracked"
	| "chiseled"
	| "smooth";
export type MonsterEggStoneType =
	| "stone"
	| "cobblestone"
	| "stone_brick"
	| "mossy_stone_brick"
	| "cracked_stone_brick"
	| "chiseled_stone_brick";
export type StoneSlabType4 =
	| "mossy_stone_brick"
	| "smooth_quartz"
	| "stone"
	| "cut_sandstone"
	| "cut_red_sandstone";
export type StoneSlabType3 =
	| "end_stone_brick"
	| "smooth_red_sandstone"
	| "polished_andesite"
	| "andesite"
	| "diorite"
	| "polished_diorite"
	| "granite"
	| "polished_granite";
export type StoneSlabType2 =
	| "red_sandstone"
	| "purpur"
	| "prismarine_rough"
	| "prismarine_dark"
	| "prismarine_brick"
	| "mossy_cobblestone"
	| "smooth_sandstone"
	| "red_nether_brick";
export type StoneSlabType =
	| "smooth_stone"
	| "sandstone"
	| "wood"
	| "cobblestone"
	| "brick"
	| "stone_brick"
	| "quartz"
	| "nether_brick";
export type FlowerType =
	| "poppy"
	| "orchid"
	| "allium"
	| "houstonia"
	| "tulip_red"
	| "tulip_orange"
	| "tulip_white"
	| "tulip_pink"
	| "oxeye"
	| "cornflower"
	| "lily_of_the_valley";
export type TallGrassType = "default" | "tall" | "fern" | "snow";
export type SandStoneType = "default" | "heiroglyphs" | "cut" | "smooth";
export type SpongeType = "dry" | "wet";
export type NewLeafType = "acacia" | "dark_oak";
export type ChiselType = "default" | "chiseled" | "lines" | "smooth";
export type NewLogType = "acacia" | "dark_oak";
export type SandType = "normal" | "red";
export type BambooLeafSize = "no_leaves" | "small_leaves" | "large_leaves";
export type BambooStalkThickness = "thin" | "thick";
export type CrackedState = "no_cracks" | "cracked" | "max_cracked";
export type TurtleEggCount = "one_egg" | "two_egg" | "three_egg" | "four_egg";
export type TorchFacingDirection =
	| "unknown"
	| "west"
	| "east"
	| "north"
	| "south"
	| "top";
export type SaplingType =
	| "oak"
	| "spruce"
	| "birch"
	| "jungle"
	| "acacia"
	| "dark_oak";
export type Damage =
	| "undamaged"
	| "slightly_damaged"
	| "very_damaged"
	| "broken";
export type PortalAxis = "unknown" | "x" | "z";
export type MinecraftverticalHalf = "bottom" | "top";
export type MinecraftblockFace =
	| "down"
	| "up"
	| "north"
	| "south"
	| "west"
	| "east";
export type MinecraftfacingDirection =
	| "down"
	| "up"
	| "north"
	| "south"
	| "west"
	| "east";
export type MinecraftcardinalDirection = "south" | "west" | "north" | "east";
