// Contains the current protocol version and Minecraft version

const PROTOCOL_VERSION = 860;
const COMPATIBLE_PROTOCOL_VERSIONS = new Set<number>([859, PROTOCOL_VERSION]);
const MINECRAFT_SEM_VERSION: [number, number, number] = [1, 21, 120];
const MINECRAFT_VERSION = MINECRAFT_SEM_VERSION.join(".");
const MINECRAFT_TICK_SPEED = 50;

const BLOCK_STATE_VERSION =
  (MINECRAFT_SEM_VERSION[0] << 24) |
  (MINECRAFT_SEM_VERSION[1] << 16) |
  (MINECRAFT_SEM_VERSION[2] << 8);

const SHIELD_NETWORK_ID = 380;

export {
  PROTOCOL_VERSION,
  MINECRAFT_SEM_VERSION,
  MINECRAFT_VERSION,
  MINECRAFT_TICK_SPEED,
  BLOCK_STATE_VERSION,
  SHIELD_NETWORK_ID,
  COMPATIBLE_PROTOCOL_VERSIONS
};

export * from "./default-ability-values";
